### ISSUE TITLE
virtualBackground image fitType is ignored for WebGL2 pipeline

### ISSUE THREAD

**Issue by lgenzelis** [twilio/twilio-video.js#2011] opened 2023-07-20 16:14 UTC
According to [the docs for @twilio/video-processors](https://twilio.github.io/twilio-video-processors.js/interfaces/virtualbackgroundprocessoroptions.html#fitType), the default `fitType` when using a virtual background is `'Fill'`, and it can be changed to `'Contain'` or `'Cover'`. That seems to be the case then we use `Canvas2D`. For example, this works fine:

```javascript
import { ImageFit, Pipeline, VirtualBackgroundProcessor } from '@twilio/video-processors';
import { createLocalVideoTrack } from 'twilio-video';

const videoTrack = await createLocalVideoTrack();

const img = new Image();
img.onload = () => {
  const virtualBackground = new VirtualBackgroundProcessor({
    assetsPath: '/twilioVideoProcessorAssets',
    backgroundImage: img,
    fitType: ImageFit.Contain,
    pipeline: Pipeline.Canvas2D,
  });

  virtualBackground.loadModel().then(() =>
    videoTrack.addProcessor(virtualBackground),
  );
};

img.src = '/path-to-image.jpg';
```

However, when we use `WebGL2`, the `fitType` parameter is ignored, and it doesn't even use the default. It just uses "Cover".

```diff
import { ImageFit, Pipeline, VirtualBackgroundProcessor } from '@twilio/video-processors';
import { createLocalVideoTrack } from 'twilio-video';

const videoTrack = await createLocalVideoTrack();

const img = new Image();
img.onload = () => {
  const virtualBackground = new VirtualBackgroundProcessor({
    assetsPath: '/twilioVideoProcessorAssets',
    backgroundImage: img,
    fitType: ImageFit.Contain,
+   // ^^^  it does not matter if we omit this or write something else, it will always behave as "Cover"
-   pipeline: Pipeline.Canvas2D,
  });

  virtualBackground.loadModel().then(() =>
    videoTrack.addProcessor(virtualBackground, {
+      inputFrameBufferType: 'video',
+      outputFrameBufferContextType: 'webgl2',
    }),
  );
};

img.src = '/path-to-image.jpg';
```

 - [X] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [X] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [X] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Software versions:**

 - [X] Browser(s): Chrome 114
 - [X] Operating System: macos 13.4.1
 - [X] twilio-video.js: 2.27.0
 - [X] @twilio/video-processors: 2.0.0

**Comment by Toki1117** [comment] 2023-07-20 17:22
I'm having the same issue, looks like only downgrading to v1.0.2 works fine for `WebGL2`

**Comment by manjeshbhargav** [comment] 2023-07-25 20:24
Hi @lgenzelis ,

I will take a look and get back to you soon.

**Comment by manjeshbhargav** [comment] 2023-07-25 20:48
Hi @lgenzelis , @Toki1117 ,

This is as designed. `fitType` does not apply to `webgl2`. I apologize for not making this clear in the documentation. I have create a ticket to update it. Thanks for bringing this to my attention.

**Comment by lgenzelis** [comment] 2023-07-31 12:54
Ok, got it! Thanks @manjeshbhargav . Since we're at it, do you know if there's any reason to use `webgl2` over `Canvas2D`?

**Comment by manjeshbhargav** [comment] 2023-07-31 21:08
@lgenzelis ,

WebGL2 makes sure to take advantage of the GPU whenever possible for compositing the background and the foreground after the inference process is complete. Canvas2D uses the HTMLCanvasElement to do the compositing. We have seen some performance improvements with WebGL2 over Canvas2D for 480p and lower videos on machines that have a decent graphics card.

**Comment by manjeshbhargav** [comment] 2023-07-31 21:15
@lgenzelis 

I have update the [fitType documentation](https://twilio.github.io/twilio-video-processors.js/interfaces/virtualbackgroundprocessoroptions.html#fittype) to reflect the accurate behavior. I will close this issue now. Thanks for bringing it to my attention.

**Closed by manjeshbhargav** 2023-07-31 21:15 UTC
Labels: bug filed, Documentation
