### ISSUE TITLE
[beta7 - Chrome Canary (version 60)] Exception when trying to remove tracks on the localParticipant on closing

### ISSUE THREAD

**Issue by jskrzypek** [twilio/twilio-video.js#89] opened 2017-04-25 07:46 UTC
I'm using 1.0.0-beta7 on angular@^4 so my stacktraces have the zone stuff included. I run the cleanup method (which calls the LP's `removeTracks()`) in the component's `ngOnDestroy()` (i.e. when closing the modal in which we display the video chat). I get the exception you can see in the stack traces included below. The track gets stopped correctly, but I wonder why this happens. Additionally I have a listener on the remote participant's `'disconnected'` event that closes the modal as well, but that doesn't cause this exception, only initiating the hangup does. Everything else seems fine after the exception fires so I don't really know if this is an issue or not, but it might be relevant to you guys.

I happened to be testing on Chrome Canary (60.0.3079.0) this AM,  and caught this. When I tested it in my normal Chrome (58.0.3029.81) I did not see this exception.

----------------------

Here's the exception when run inside a [`ngZone.runOutsideAngular()`](https://angular.io/docs/ts/latest/api/core/index/NgZone-class.html) block without the long-stack-trace:
```
Uncaught DOMException: Failed to execute 'removeStream' on 'RTCPeerConnection': The RTCPeerConnection's signalingState is 'closed'.
    at ChromeRTCPeerConnection.wrapper.(anonymous function) [as removeStream] (https://localhost:5000/bootstrap.bundle.js:49147:37)
    at PeerConnectionV2.removeMediaStream (https://localhost:5000/bootstrap.bundle.js:46335:24)
    at PeerConnectionManager.<anonymous> (https://localhost:5000/bootstrap.bundle.js:46610:22)
    at Map.forEach (native)
    at PeerConnectionManager.setMediaStreamTracks (https://localhost:5000/bootstrap.bundle.js:46609:27)
    at renegotiate (https://localhost:5000/bootstrap.bundle.js:47011:27)
    at https://localhost:5000/bootstrap.bundle.js:47004:5
    at nextTick (https://localhost:5000/bootstrap.bundle.js:49046:5)
    at ZoneDelegate.809.ZoneDelegate.invokeTask (https://localhost:5000/polyfills.bundle.js:9516:31)
    at Zone.809.Zone.runTask (https://localhost:5000/polyfills.bundle.js:9283:47)
    at ZoneTask.invoke (https://localhost:5000/polyfills.bundle.js:9578:38)
    at timer (https://localhost:5000/polyfills.bundle.js:10770:29)
```

Here's the exception within the zone and with the long stack trace:
```
DOMException: Failed to execute 'removeStream' on 'RTCPeerConnection': The RTCPeerConnection's signalingState is 'closed'.
    at ChromeRTCPeerConnection.wrapper.(anonymous function) [as removeStream] (https://localhost:5000/bootstrap.bundle.js:49224:37)
    at PeerConnectionV2.removeMediaStream (https://localhost:5000/bootstrap.bundle.js:46412:24)
    at PeerConnectionManager.<anonymous> (https://localhost:5000/bootstrap.bundle.js:46687:22)
    at Map.forEach (native)
    at PeerConnectionManager.setMediaStreamTracks (https://localhost:5000/bootstrap.bundle.js:46686:27)
    at renegotiate (https://localhost:5000/bootstrap.bundle.js:47088:27)
    at https://localhost:5000/bootstrap.bundle.js:47081:5
    at nextTick (https://localhost:5000/bootstrap.bundle.js:49123:5)
    at ZoneDelegate.809.ZoneDelegate.invokeTask (https://localhost:5000/polyfills.bundle.js:9516:31)
    at Object.onInvokeTask (https://localhost:5000/vendor.bundle.js:4330:37)
    at ZoneDelegate.809.ZoneDelegate.invokeTask (https://localhost:5000/polyfills.bundle.js:9515:36)
    at Zone.809.Zone.runTask (https://localhost:5000/polyfills.bundle.js:9283:47)
    at ZoneTask.invoke (https://localhost:5000/polyfills.bundle.js:9578:38)
    at timer (https://localhost:5000/polyfills.bundle.js:10770:29)
    at ____________________Elapsed_22_ms__At__Tue_Apr_25_2017_10_30_22_GMT_0300__IDT_ (http://localhost)
    at getStacktraceWithUncaughtError (https://localhost:5000/polyfills.bundle.js:8975:12) [angular]
    at new LongStackTrace (https://localhost:5000/polyfills.bundle.js:8969:22) [angular]
    at Object.onScheduleTask (https://localhost:5000/polyfills.bundle.js:9045:22) [angular]
    at Object.onScheduleTask (https://localhost:5000/polyfills.bundle.js:9392:29) [angular]
    at https://localhost:5000/polyfills.bundle.js:10795:33 [angular]
    at setTimeout (eval at createNamedFn (https://localhost:5000/polyfills.bundle.js:10702:17), <anonymous>:3:37) [angular]
    at scheduleNextTick (https://localhost:5000/bootstrap.bundle.js:49130:15) [angular]
    at LocalParticipantV2.trackRemoved (https://localhost:5000/bootstrap.bundle.js:47116:5) [angular]
    at LocalParticipantV2.EventEmitter.emit (https://localhost:5000/bootstrap.bundle.js:52146:17) [angular]
    at LocalParticipantV2.removeTrack (https://localhost:5000/bootstrap.bundle.js:45189:10) [angular]
    at ____________________Elapsed_4_ms__At__Tue_Apr_25_2017_10_30_22_GMT_0300__IDT_ (http://localhost)
    at getStacktraceWithUncaughtError (https://localhost:5000/polyfills.bundle.js:8975:12) [angular]
    at new LongStackTrace (https://localhost:5000/polyfills.bundle.js:8969:22) [angular]
    at Object.onScheduleTask (https://localhost:5000/polyfills.bundle.js:9045:22) [angular]
    at Object.onScheduleTask (https://localhost:5000/polyfills.bundle.js:9392:29) [angular]
    at scheduleResolveOrReject (https://localhost:5000/polyfills.bundle.js:9874:14) [angular]
    at ZoneAwarePromise.809.ZoneAwarePromise.then (https://localhost:5000/polyfills.bundle.js:9963:17) [angular]
    at https://localhost:5000/bootstrap.bundle.js:719:45 [angular]
    at Object.onInvoke (https://localhost:5000/vendor.bundle.js:4339:37) [angular]
    at ____________________Elapsed_0_ms__At__Tue_Apr_25_2017_10_30_22_GMT_0300__IDT_ (http://localhost)
    at getStacktraceWithUncaughtError (https://localhost:5000/polyfills.bundle.js:8975:12) [angular]
    at new LongStackTrace (https://localhost:5000/polyfills.bundle.js:8969:22) [angular]
    at Object.onScheduleTask (https://localhost:5000/polyfills.bundle.js:9045:22) [angular]
    at Object.onScheduleTask (https://localhost:5000/polyfills.bundle.js:9392:29) [angular]
    at scheduleResolveOrReject (https://localhost:5000/polyfills.bundle.js:9874:14) [angular]
    at resolvePromise (https://localhost:5000/polyfills.bundle.js:9823:21) [angular]
    at DialogRef.whenClosedResolve (https://localhost:5000/polyfills.bundle.js:9754:17) [angular]
    at https://localhost:5000/bootstrap.bundle.js:7550:31 [angular]
    at Object.onInvoke (https://localhost:5000/vendor.bundle.js:4339:37) [angular]
    at ____________________Elapsed_1_ms__At__Tue_Apr_25_2017_10_30_22_GMT_0300__IDT_ (http://localhost)
    at getStacktraceWithUncaughtError (https://localhost:5000/polyfills.bundle.js:8975:12) [angular]
    at new LongStackTrace (https://localhost:5000/polyfills.bundle.js:8969:22) [angular]
    at Object.onScheduleTask (https://localhost:5000/polyfills.bundle.js:9045:22) [angular]
    at Object.onScheduleTask (https://localhost:5000/polyfills.bundle.js:9392:29) [angular]
    at scheduleResolveOrReject (https://localhost:5000/polyfills.bundle.js:9874:14) [angular]
    at resolvePromise (https://localhost:5000/polyfills.bundle.js:9823:21) [angular]
    at https://localhost:5000/polyfills.bundle.js:9876:17 [angular]
    at Object.onInvokeTask (https://localhost:5000/vendor.bundle.js:4330:37) [angular]
    at ____________________Elapsed_0_ms__At__Tue_Apr_25_2017_10_30_22_GMT_0300__IDT_ (http://localhost)
    at getStacktraceWithUncaughtError (https://localhost:5000/polyfills.bundle.js:8975:12) [angular]
    at new LongStackTrace (https://localhost:5000/polyfills.bundle.js:8969:22) [angular]
    at Object.onScheduleTask (https://localhost:5000/polyfills.bundle.js:9045:22) [angular]
    at Object.onScheduleTask (https://localhost:5000/polyfills.bundle.js:9392:29) [angular]
    at scheduleResolveOrReject (https://localhost:5000/polyfills.bundle.js:9874:14) [angular]
    at resolvePromise (https://localhost:5000/polyfills.bundle.js:9823:21) [angular]
    at https://localhost:5000/polyfills.bundle.js:9754:17 [angular]
    at done (https://localhost:5000/bootstrap.bundle.js:12562:21) [angular]
    at https://localhost:5000/bootstrap.bundle.js:12556:67 [angular]
    at ____________________Elapsed_451_ms__At__Tue_Apr_25_2017_10_30_22_GMT_0300__IDT_ (http://localhost)
    at getStacktraceWithUncaughtError (https://localhost:5000/polyfills.bundle.js:8975:12) [angular]
    at new LongStackTrace (https://localhost:5000/polyfills.bundle.js:8969:22) [angular]
    at Object.onScheduleTask (https://localhost:5000/polyfills.bundle.js:9045:22) [angular]
    at Object.onScheduleTask (https://localhost:5000/polyfills.bundle.js:9392:29) [angular]
    at https://localhost:5000/polyfills.bundle.js:10795:33 [angular]
    at setTimeout (eval at createNamedFn (https://localhost:5000/polyfills.bundle.js:10702:17), <anonymous>:3:37) [angular]
    at https://localhost:5000/bootstrap.bundle.js:12556:35 [angular]
    at Object.onInvokeTask (https://localhost:5000/vendor.bundle.js:4330:37) [angular]
    at ____________________Elapsed_4_ms__At__Tue_Apr_25_2017_10_30_22_GMT_0300__IDT_ (http://localhost)
    at getStacktraceWithUncaughtError (https://localhost:5000/polyfills.bundle.js:8975:12) [angular]
    at new LongStackTrace (https://localhost:5000/polyfills.bundle.js:8969:22) [angular]
    at Object.onScheduleTask (https://localhost:5000/polyfills.bundle.js:9045:22) [angular]
    at Object.onScheduleTask (https://localhost:5000/polyfills.bundle.js:9392:29) [angular]
    at https://localhost:5000/polyfills.bundle.js:10795:33 [angular]
    at setTimeout (eval at createNamedFn (https://localhost:5000/polyfills.bundle.js:10702:17), <anonymous>:3:37) [angular]
    at https://localhost:5000/bootstrap.bundle.js:12552:13 [angular]
    at new ZoneAwarePromise (https://localhost:5000/polyfills.bundle.js:9892:29) [angular]
    at Animate.leave (https://localhost:5000/bootstrap.bundle.js:12550:16) [angular]
    at BackdropComponent.toggle (https://localhost:5000/bootstrap.bundle.js:20245:16) [angular]
    at ____________________Elapsed_0_ms__At__Tue_Apr_25_2017_10_30_22_GMT_0300__IDT_ (http://localhost)
    at getStacktraceWithUncaughtError (https://localhost:5000/polyfills.bundle.js:8975:12) [angular]
    at new LongStackTrace (https://localhost:5000/polyfills.bundle.js:8969:22) [angular]
    at Object.onScheduleTask (https://localhost:5000/polyfills.bundle.js:9045:22) [angular]
    at Object.onScheduleTask (https://localhost:5000/polyfills.bundle.js:9392:29) [angular]
    at scheduleResolveOrReject (https://localhost:5000/polyfills.bundle.js:9874:14) [angular]
    at resolvePromise (https://localhost:5000/polyfills.bundle.js:9823:21) [angular]
    at https://localhost:5000/polyfills.bundle.js:9754:17 [angular]
    at HTMLElement.done (https://localhost:5000/bootstrap.bundle.js:12562:21) [angular]
    at Object.onInvokeTask (https://localhost:5000/vendor.bundle.js:4330:37) [angular]
    at ____________________Elapsed_42_ms__At__Tue_Apr_25_2017_10_30_22_GMT_0300__IDT_ (http://localhost)
    at getStacktraceWithUncaughtError (https://localhost:5000/polyfills.bundle.js:8975:12) [angular]
    at new LongStackTrace (https://localhost:5000/polyfills.bundle.js:8969:22) [angular]
    at Object.onScheduleTask (https://localhost:5000/polyfills.bundle.js:9045:22) [angular]
    at Object.onScheduleTask (https://localhost:5000/polyfills.bundle.js:9392:29) [angular]
    at zoneAwareAddListener (https://localhost:5000/polyfills.bundle.js:10568:14) [angular]
    at HTMLElement.addEventListener (eval at createNamedFn (https://localhost:5000/polyfills.bundle.js:10702:17), <anonymous>:3:43) [angular]
    at https://localhost:5000/bootstrap.bundle.js:12564:20 [angular]
    at Object.onInvokeTask (https://localhost:5000/vendor.bundle.js:4330:37) [angular]
    at ____________________Elapsed_9_ms__At__Tue_Apr_25_2017_10_30_22_GMT_0300__IDT_ (http://localhost)
    at getStacktraceWithUncaughtError (https://localhost:5000/polyfills.bundle.js:8975:12) [angular]
    at new LongStackTrace (https://localhost:5000/polyfills.bundle.js:8969:22) [angular]
    at Object.onScheduleTask (https://localhost:5000/polyfills.bundle.js:9045:22) [angular]
    at Object.onScheduleTask (https://localhost:5000/polyfills.bundle.js:9392:29) [angular]
    at https://localhost:5000/polyfills.bundle.js:10795:33 [angular]
    at setTimeout (eval at createNamedFn (https://localhost:5000/polyfills.bundle.js:10702:17), <anonymous>:3:37) [angular]
    at https://localhost:5000/bootstrap.bundle.js:12552:13 [angular]
    at new ZoneAwarePromise (https://localhost:5000/polyfills.bundle.js:9892:29) [angular]
    at Function.Animate.leave (https://localhost:5000/bootstrap.bundle.js:12550:16) [angular]
    at DialogRef.close (https://localhost:5000/bootstrap.bundle.js:7543:38) [angular]
```

**Comment by markandrus** [comment] 2017-04-25 17:30
Hi @jskrzypek,

Thanks for the report.

> I happened to be testing on Chrome Canary (60.0.3079.0) this AM, and caught this. When I tested it in my normal Chrome (58.0.3029.81) I did not see this exception.

Likely Chrome Canary has begun adopting the newer WebRTC behaviors. Although `removeStream` (and `addStream`) go away entirely in WebRTC 1.0, they appear to have adopted the behavior of `removeTrack`, at least with respect to signaling state. See [here](http://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-removetrack):

> When the **removeTrack** method is invoked, the user agent must run the following steps:
>
> 1. Let _sender_ be the argument to removeTrack.
> 2. Let _connection_ be the `RTCPeerConnection` object on which the method was invoked.
> 3. If connection's [[isClosed]] slot is `true`, throw an `InvalidStateError`.

So we will need to update our usage accordingly in a future release.

Thanks!
Mark

**Comment by jskrzypek** [comment] 2017-04-25 18:21
> Likely Chrome Canary has begun adopting the newer WebRTC behaviors.
Makes sense, I definitely didn't see this exception on canary last week... but that's what I get for using canary, I guess 😄

**Comment by markandrus** [comment] 2017-05-04 18:50
@jskrzypek I am looking at this issue, and I'm having a lot of trouble reproducing it, even in an app using Zone.js and twilio-video.js in Chrome Canary (60). Can you share additional reproduction steps? For example, I am trying to catch either the remote Participant's "disconnected" event, or the LocalParticipant's "disconnected" event and then removing all LocalTracks—but I cannot raise the issue.

**Comment by jamesgraham** [comment] 2017-06-13 22:46
Hi @markandrus, we are seeing this issue extensively on Chrome 58.0.3029

Is this a known issue and if so is there a workaround?

**Comment by markandrus** [comment] 2017-07-07 01:06
@jamesgraham actually, I have been unable to reproduce this and we haven't heard anything from our QE Team on it. Do you have reproduction steps of your own you could share?

**Comment by markandrus** [comment] 2018-01-11 23:03
I'm closing this issue for now. If there are still occurrences of this, please write in and share, and we will take another look.

**Closed by markandrus** 2018-01-11 23:03 UTC
Labels: WebRTC

**Comment by jamesgraham** [comment] 2018-01-12 10:03
Thanks @markandrus - we have not seen this for some time - sorry we didn't update the ticket.
