### ISSUE TITLE
Safari (Mac) and Chrome (Mac) Interop Issue

### ISSUE THREAD

**Issue by chrismatthieu** [twilio/twilio-video.js#1596] opened 2021-10-06 20:32 UTC
Running the latest twilio-video version 2.17.1, latest Safari (Mac) version Version 15.0 (16612.1.29.41.4, 16612), and latest Chrome (Mac) Version 94.0.4606.71 (Official Build) (x86_64).

Safari and Chrome both join a room. Safari sees video of Chrome user but Chrome does not see video of Safari user.

I did notice a couple of errors on the Safari side and non on the Chrome side:

[Warning] 2021-10-06T20:26:54.223Z – "warn" – "[RemoteVideoTrack #3: MT69bdcab22f20511ee1b8a71c1ff64ecf]" – "Unintentionally paused:" –  (twilio-video.min.js, line 51)
<video autoplay playsinline id="remote-media-38ke-pLD35M5uQl7AAAL" style="transform: scale(-1, 1); clip-path: circle(60px at 50% 50%); height: 1px; filter: grayscale(77.2383485597673%);"></video>

<video autoplay playsinline id="remote-media-38ke-pLD35M5uQl7AAAL" style="transform: scale(-1, 1); clip-path: circle(60px at 50% 50%); height: 1px; filter: grayscale(77.2383485597673%);"></video>
[Warning] 2021-10-06T20:26:54.293Z – "warn" – "[RemoteAudioTrack #4: MTce2da3c5604646677369ed36dfb372e6]" – "Unintentionally paused:" –  (twilio-video.min.js, line 51)
<audio autoplay id="remote-audio-38ke-pLD35M5uQl7AAAL" style="transform: scale(-1, 1); clip-path: circle(60px at 50% 50%);"></audio>

<audio autoplay id="remote-audio-38ke-pLD35M5uQl7AAAL" style="transform: scale(-1, 1); clip-path: circle(60px at 50% 50%);"></audio>

--
Room name and SID below:

20:21:31 UTC 2021-10-06 | 123 - RM521ca6ca1f4e92ad18e6addb9e7d11cd | Group | 4 min 23 sec

**Comment by PikaJoyce** [comment] 2021-10-19 20:20
A small update, I've been able to reproduce this issue and I have filed an internal ticket (VIDEO-7424) in order to track this issue. Again, I'll continue to update this thread!

**Comment by makarandp0** [comment] 2021-10-29 21:04
Hello @chrismatthieu,
Looks like there was some misunderstanding - @PikaJoyce was able to reproduce issue on iOS Safari (and there are few known issues regarding those), but we have not been able to reproduce the issue between MacOS Safari to MacOS Chrome. But Again I am checking this on Safari Version 15.1 (17612.2.9.1.20), and looks like yours was 15.0 

Do you still have the consistent repro? Can you please check if you can reproduce this on latest Safari version ?

By the way I also noticed few network issues in the room-sid you provided. I see that there were few ice connection errors and also signaling errors. Perhaps they could explain chrome not being able to see the Safari participant's video.

```
Summary for Room: 123 | RM521ca6ca1f4e92ad18e6addb9e7d11cd | AC0cfe417c7827ad2b3a760c14175ef6a3
Topology: group | Adhoc: True | TURN: True | Recording on Connect: False | Video Codecs: VP8,H264 | Media Region: us1 | Audio Only: False
VMS: VM58f59e78ec8c19066ba1498424c179eb
Participants:
P1: PA362ecc38a66e1863afeeaddb2244ca08 | CA66560e25e39151c6f4da423293a60512 | h4eJAwDcfpJ_mZsgAAAD | unified | jsdk 2.17.1 | Chrome 94.0.4606 
P2: PAca815ed9d9302e7a8c47f2abeb02cdf3 | CAc88d00a76df9f1567d706a328d8337b4 | JjnfiYXUPOZYBtmWAAAF | unified | jsdk 2.17.1 | Safari 15.0 
P3: PAf951ce4bd293a090f5020146fef77514 | CA7437f539271813460a9175e8638f0194 | BAai11AdcsZKoI-jAAAH | unified | jsdk 2.17.1 | Chrome 94.0.4606 
2021-10-06T20:21:31.026Z: [add_labeled_room]
2021-10-06T20:21:31.027Z: P1 sent connect with audio + video tracks
2021-10-06T20:21:31.027Z: P1 sent offer for peer connection id 28dcd709-66f1-445d-a067-867271a2bb9d revision: 1
2021-10-06T20:21:31.028Z: [room_created]
2021-10-06T20:21:31.028Z: P1 updated subscribe rules: { include all }
2021-10-06T20:21:31.029Z: [add_room_recording] with recording rules: { exclude all }
2021-10-06T20:21:31.150Z: P1 received connected
2021-10-06T20:21:31.150Z: P1 received answer for peer connection id 28dcd709-66f1-445d-a067-867271a2bb9d revision: 1
2021-10-06T20:21:31.150Z: P1 is connected with media region us1, signaling region us2, and session timeout 30
2021-10-06T20:21:32.153Z: P1 sent ice complete for peer connection id 28dcd709-66f1-445d-a067-867271a2bb9d with no ice candidates (could be in SDP) revision: 1
2021-10-06T20:21:32.222Z: P1 sent ice complete for peer connection id 28dcd709-66f1-445d-a067-867271a2bb9d with no ice candidates (could be in SDP) revision: 1
2021-10-06T20:21:33.171Z: [ice_connection_state_change] for P1 with state FAILED
2021-10-06T20:21:33.184Z: [ice_connection_state_change] for P1 with state CONNECTED
2021-10-06T20:21:33.184Z: [ice_connection_state_change] for P1 with state COMPLETED
2021-10-06T20:22:05.845Z: P2 sent connect with video + audio tracks
2021-10-06T20:22:05.845Z: P2 sent offer for peer connection id bfe31e2b-7375-43a4-a9a7-a5eb94d8cbcf revision: 1
2021-10-06T20:22:05.846Z: P2 updated subscribe rules: { include all }
2021-10-06T20:22:05.863Z: P2 received connected
2021-10-06T20:22:05.863Z: P2 received answer for peer connection id bfe31e2b-7375-43a4-a9a7-a5eb94d8cbcf revision: 1
2021-10-06T20:22:05.863Z: P2 is connected with media region us1, signaling region us2, and session timeout 30
2021-10-06T20:22:05.863Z: P1 subscribed: MTda55886db428c41a2e48fac3c44667c0 revision: 1
2021-10-06T20:22:05.863Z: P1 subscribed: MTe77f16cb6fee7344147d73875dab48ba revision: 1
2021-10-06T20:22:05.863Z: P1 received offer for peer connection id 28dcd709-66f1-445d-a067-867271a2bb9d revision: 2
2021-10-06T20:22:05.864Z: P2 received offer for peer connection id bfe31e2b-7375-43a4-a9a7-a5eb94d8cbcf revision: 2
2021-10-06T20:22:05.864Z: P2 subscribed: MTb273421ebf1727256046f61ba4179a20 revision: 1
2021-10-06T20:22:05.864Z: P2 subscribed: MTc649480f5f5750a6cdce6b24654638eb revision: 1
2021-10-06T20:22:06.178Z: P1 sent answer for peer connection id 28dcd709-66f1-445d-a067-867271a2bb9d revision: 2
2021-10-06T20:22:06.308Z: P2 sent answer for peer connection id bfe31e2b-7375-43a4-a9a7-a5eb94d8cbcf revision: 2
2021-10-06T20:22:06.315Z: P1 sent answer for peer connection id 28dcd709-66f1-445d-a067-867271a2bb9d revision: 2
2021-10-06T20:22:06.445Z: P2 sent answer for peer connection id bfe31e2b-7375-43a4-a9a7-a5eb94d8cbcf revision: 2
2021-10-06T20:22:06.800Z: P2 sent ice complete for peer connection id bfe31e2b-7375-43a4-a9a7-a5eb94d8cbcf with no ice candidates (could be in SDP) revision: 1
2021-10-06T20:22:06.871Z: P2 sent ice complete for peer connection id bfe31e2b-7375-43a4-a9a7-a5eb94d8cbcf with no ice candidates (could be in SDP) revision: 1
2021-10-06T20:22:07.779Z: [ice_connection_state_change] for P2 with state FAILED
2021-10-06T20:22:07.799Z: [ice_connection_state_change] for P2 with state CONNECTED
2021-10-06T20:22:07.799Z: [ice_connection_state_change] for P2 with state COMPLETED
2021-10-06T20:25:07.030Z: [participant_reconnecting] for P1 
2021-10-06T20:25:10.044Z: [participant_reconnecting] for P2 
2021-10-06T20:25:33.042Z: [ice_connection_state_change] for P1 with state FAILED
2021-10-06T20:25:40.491Z: P3 sent connect with audio + video tracks
2021-10-06T20:25:40.491Z: P3 sent offer for peer connection id 4e62c323-661f-4257-88c9-66f4413e4a32 revision: 1
2021-10-06T20:25:40.493Z: P3 updated subscribe rules: { include all }
2021-10-06T20:25:40.511Z: P3 received connected
2021-10-06T20:25:40.511Z: P3 received answer for peer connection id 4e62c323-661f-4257-88c9-66f4413e4a32 revision: 1
2021-10-06T20:25:40.511Z: P3 is connected with media region us1, signaling region us2, and session timeout 30
2021-10-06T20:25:40.512Z: P1 received offer for peer connection id 28dcd709-66f1-445d-a067-867271a2bb9d revision: 3
2021-10-06T20:25:40.512Z: P1 subscribed: MT870a6f684295878d014d4b4d78d26649 revision: 2
2021-10-06T20:25:40.512Z: P1 subscribed: MT7a5e757016c8ac57c72fcc6323f9d0a3 revision: 2
2021-10-06T20:25:40.513Z: P2 received offer for peer connection id bfe31e2b-7375-43a4-a9a7-a5eb94d8cbcf revision: 3
2021-10-06T20:25:40.513Z: P2 subscribed: MT870a6f684295878d014d4b4d78d26649 revision: 2
2021-10-06T20:25:40.513Z: P2 subscribed: MT7a5e757016c8ac57c72fcc6323f9d0a3 revision: 2
2021-10-06T20:25:40.514Z: P3 received offer for peer connection id 4e62c323-661f-4257-88c9-66f4413e4a32 revision: 2
2021-10-06T20:25:40.514Z: P3 subscribed: MTe77f16cb6fee7344147d73875dab48ba revision: 1
2021-10-06T20:25:40.514Z: P3 subscribed: MTda55886db428c41a2e48fac3c44667c0 revision: 1
2021-10-06T20:25:40.514Z: P3 subscribed: MTb273421ebf1727256046f61ba4179a20 revision: 1
2021-10-06T20:25:40.514Z: P3 subscribed: MTc649480f5f5750a6cdce6b24654638eb revision: 1
2021-10-06T20:25:41.257Z: P2 received error: 53002 Signaling connection timed out: Reconnecting timeout
2021-10-06T20:25:41.257Z: [participant_disconnected] for P2 
2021-10-06T20:25:41.259Z: P1 received error: 53002 Signaling connection timed out: Reconnecting timeout
2021-10-06T20:25:41.259Z: [participant_disconnected] for P1 
2021-10-06T20:25:41.265Z: [group_billing_event] for P2 with bytes sent 3535492, bytes received 328323, recording time in secs 0
2021-10-06T20:25:41.271Z: [group_billing_event] for P1 with bytes sent 462064, bytes received 4654492, recording time in secs 0
2021-10-06T20:25:41.887Z: P3 sent answer for peer connection id 4e62c323-661f-4257-88c9-66f4413e4a32 revision: 2
2021-10-06T20:25:41.961Z: P3 sent answer for peer connection id 4e62c323-661f-4257-88c9-66f4413e4a32 revision: 2
2021-10-06T20:25:41.971Z: P3 received offer for peer connection id 4e62c323-661f-4257-88c9-66f4413e4a32 revision: 3
2021-10-06T20:25:41.971Z: P3 unsubscribed from: MTe77f16cb6fee7344147d73875dab48ba revision: 2
2021-10-06T20:25:41.971Z: P3 unsubscribed from: MTda55886db428c41a2e48fac3c44667c0 revision: 2
2021-10-06T20:25:41.971Z: P3 unsubscribed from: MTb273421ebf1727256046f61ba4179a20 revision: 2
2021-10-06T20:25:41.971Z: P3 unsubscribed from: MTc649480f5f5750a6cdce6b24654638eb revision: 2
2021-10-06T20:25:42.150Z: P3 sent answer for peer connection id 4e62c323-661f-4257-88c9-66f4413e4a32 revision: 3
2021-10-06T20:25:42.220Z: P3 sent answer for peer connection id 4e62c323-661f-4257-88c9-66f4413e4a32 revision: 3
2021-10-06T20:25:42.242Z: P3 sent ice complete for peer connection id 4e62c323-661f-4257-88c9-66f4413e4a32 with no ice candidates (could be in SDP) revision: 1
2021-10-06T20:25:42.312Z: P3 sent ice complete for peer connection id 4e62c323-661f-4257-88c9-66f4413e4a32 with no ice candidates (could be in SDP) revision: 1
2021-10-06T20:25:43.238Z: [ice_connection_state_change] for P3 with state FAILED
2021-10-06T20:25:53.430Z: [ice_connection_state_change] for P3 with state CONNECTED
2021-10-06T20:25:53.430Z: [ice_connection_state_change] for P3 with state COMPLETED
2021-10-06T20:25:54.669Z: P3 received error: 53403 Server is unable to apply a remote media description: Dtls negotiation failed
2021-10-06T20:25:54.669Z: [participant_disconnected] for P3 
2021-10-06T20:25:54.675Z: [delete_labeled_room]
2021-10-06T20:25:54.675Z: [group_billing_event] for P3 with bytes sent 8370, bytes received 6750, recording time in secs 0
2021-10-06T20:26:55.178Z: [group_media_client_closed]
2021-10-06T20:57:54.873Z: [room_removed]
```

**Comment by chrismatthieu** [comment] 2021-10-29 22:41
I upgraded to Safari 15.1 and Twilio-video 2.18.1 and Twilio 3.70.0 and
this issue continues to persist.

Mac Safari user can see Mac Chrome user.
Chrome user cannot see Safari user.

**Comment by makarandp0** [comment] 2021-11-01 17:51
Hello @chrismatthieu, can you please share a room sid, and client logs from both sides to debug this further.

**Comment by PikaJoyce** [comment] 2022-07-27 19:14
Will now be closing this as there hasn't been any recent activity here for quite some time and VIDEO-7424 has been closed. Please open another issue with us if you're still experiencing any problems. Thanks!

**Closed by PikaJoyce** 2022-07-27 19:14 UTC
Labels: bug filed
