### ISSUE TITLE
Fails to compile with webpack: The keyword 'import' is reserved

### ISSUE THREAD

**Issue by gburt** [twilio/twilio-video.js#1854] opened 2022-08-12 16:35 UTC
Since [this change](https://github.com/twilio/twilio-video.js/pull/1766/files#diff-623a0b434f5f9811ef20cc2cd0789b726701dac18afafb85f69a37c040fa597dR8) merged our webpack build of our repo using twilio-video is failing to build with the following error, so we're unable to upgrade to 2.23.0

```
Error: Error: [static/js/2085.1c3eda7d.chunk.js]:The keyword 'import' is reserved (2:23360)
```

**Comment by mikeauclair** [comment] 2022-08-12 18:57
More context: We use `ecma-version-validator-webpack-plugin` to pin our outputs to ES5 and it looks like the version of `dynamicImport.js` in the es5 build contains an un-transpiled `import()`

**Comment by zaptrem** [comment] 2022-08-21 15:24
I have a potentially related issue during Fastlane build:
```
[stderr] [!] Error building the application - see the log above
1014
error node_modules/twilio-video/es5/dynamicImport.js: node_modules/twilio-video/es5/dynamicImport.js:Invalid call at line 8: import(
/* webpackIgnore: true */
module).
Error: node_modules/twilio-video/es5/dynamicImport.js:Invalid call at line 8: import(
/* webpackIgnore: true */
module)
    at transformJS (/Users/expo/workingdir/build/node_modules/metro-transform-worker/src/index.js:262:15)
    at transformJSWithBabel (/Users/expo/workingdir/build/node_modules/metro-transform-worker/src/index.js:410:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.transform (/Users/expo/workingdir/build/node_modules/metro-transform-worker/src/index.js:571:12)
info 
1015
Error: Fastlane build failed with unknown error. Please refer to the "Run fastlane" and "Xcode Logs" phases.
Fastlane errors in most cases are not printed at the end of the output, so you may not find any useful information in the last lines of output when looking for an error message.
```

**Comment by PikaJoyce** [comment] 2022-08-22 18:01
Hi all,

Thank you for reporting this issue. I was able to reproduce this issue. I have created a ticket to investigate and resolve this (VIDEO-11220). I will be keeping this thread open and update when we get more news! 

Best,
Joyce

**Comment by PikaJoyce** [comment] 2022-08-25 20:20
Hi folks,

There is a current workaround for this issue by updating `browserify` to v17. Please run the below snippet in order to update browserify.
```
npm install -S browserify@17
```
Please utilize this workaround as we continue to investigate this issue and let me know if there are still any issues!

Best,
Joyce

**Comment by manjeshbhargav** [comment] 2022-08-26 22:19
Hi @gburt ,

While we troubleshoot the issue, can you set the ECMA version to `2020` in your validator plugin as a temporary workaround?

**Comment by manjeshbhargav** [comment] 2022-08-30 15:28
Hi @gburt , @mikeauclair ,

We have filed an internal ticket and are looking into it.

**Comment by gburt** [comment] 2022-09-02 18:03
> Hi @gburt , @mikeauclair ,
> 
> Can you run `npm install twilio/twilio-video.js#2.24.1-rc1` and verify whether it fixes your build issue? We verified on our end that this works.

@manjeshbhargav that builds fine, thanks!

**Comment by PikaJoyce** [comment] 2022-09-07 18:23
Hi Folks,

This issue has now been fixed on the [latest version](https://github.com/twilio/twilio-video.js/releases/tag/2.24.1). I will now be closing this issue. But of course, please let us know if you're still running into any issues. 

Best,
Joyce

**Closed by PikaJoyce** 2022-09-07 18:23 UTC
Labels: bug, bug filed
