### ISSUE TITLE
FireFox 94.0 (64-bit) issue with video dimension.

### ISSUE THREAD

**Issue by jdsapariya18** [twilio/twilio-video.js#1636] opened 2021-11-10 12:27 UTC
Im using createLocalVideoTrack() in vueJs to create localvideotrack with specific constrains, i set the camera dimension and create local track using code below...
`this.localVideoTrack = await this.twilioVideo.createLocalVideoTrack({
width: this.streamVideoWidth,
height: this.streamVideoHeight,
frameRate: this.streamVideoFps
});
this.videoContainer.appendChild(this.localVideoTrack.attach());`

where width, height and frameRate is 480, 270 and 24. and printed the local track object on console.

Chrome Log 95.0.4638.69 (official 64 bit)
![image](https://user-images.githubusercontent.com/63000769/141111333-3bb82148-f6ff-4c63-b954-dd4156588e00.png)

Firefox Log 94.0 (64 bit)
![image](https://user-images.githubusercontent.com/63000769/141111468-eccfb821-7653-4e46-b5fd-437142dc6ff9.png)

I used every thing same including code, computer, camera, and i even tested that internet connection is not that slow to scaledown the resolution. only problem is with firefox i think. chrome gave me 480x270 as defined but with firefox it gave me different 352x288 dimension.

Please help me is there any problem with my code or there is any way to solve this issue because in firefox my local video outout is cutting by all the side.

**Comment by PikaJoyce** [comment] 2021-11-16 02:10
Hi @jdsapariya18,

Thank you for filing this issue with us. I'm going to investigate this and continue to update this thread. I've been able to reproduce this. However, unfortunately, it seems that you are correct in that this is a FireFox issue. Video constraints are dependent on individual devices and browsers. Some (like Chrome) might mutate the camera capture, whereas others (like FireFox) will not.

But you may be able to work around this by using a range: 
```
video_constraints = {
  width: { min: 320, ideal: 480: max: 640 },
  height: { min: 240, ideal: 270, max: 360 } 
};
```
Or you may be able to declare attributes or use CSS in order to adjust the CSS of your video element along with `objectFit : cover;`

Please let me know if you've got any further questions or concerns. However, since we don't have any action items from this issue, I'll be closing this. 

Best,
Joyce

**Closed by PikaJoyce** 2021-11-16 02:10 UTC

**Comment by jdsapariya18** [comment] 2021-11-16 12:37
Hello @PikaJoyce while doing research for this issue i found that cameras have a list of support and unsupport resolution,
when i tested my camera (mi 720p webcam) in https://webcamtests.com/resolution , i found that chrome is mutating the camera output as you said maybe downscaling or something when firefox is not. so now problem is my camera doesn't support 480x270 resolution so firefox is giving random or maybe nearest supported resolution output when chrome is already mutating so it will just keep the resolution as requested but mutate the output. so my firefox output is actually true output and chrome is cutting edges to fit that in asked resolution frame.
![image](https://user-images.githubusercontent.com/63000769/141986269-bc52da5f-4f7c-4c93-bca0-05c4257477fe.png)
