### ISSUE TITLE
unpublishTracks issue in Safari

### ISSUE THREAD

**Issue by antonpash-dev** [twilio/twilio-video.js#297] opened 2018-05-08 16:04 UTC
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.

**Code to reproduce the issue:**

```js
activeRoom.localParticipant.unpublishTracks(Array.from(activeRoom.localParticipant.videoTracks.values()));
```

**Expected behavior:**

Not blocking/disabling remote video on unpublishing local one

**Actual behavior:**

Remote video gets blocked/disabled, when I call unpublishTracks method of LocalParticipant

**Software versions:**

 - [ ] Browser(s):
Safari 11.0.3
 - [ ] Operating System:
MacOS High Sierra
 - [ ] twilio-video.js:
1.8.0
 - [ ] Third-party libraries (e.g., Angular, React, etc.):
Angular 6

**Comment by markandrus** [comment] 2018-08-28 18:31
@antonpash-dev I cannot reproduce this with Safari 11.1.2. I do know that, in Safari, if you haven't granted microphone or camera access, you may not hear remote audio. This is something unfortunately out of our control. I will close this issue for now, but feel free to reopen it if you are still having issues.

Best,
Mark

**Closed by markandrus** 2018-08-28 18:31 UTC
