### ISSUE TITLE
Twilio Recording frozen video frame

### ISSUE THREAD

**Issue by venkateshdinfy** [twilio/twilio-video.js#1544] opened 2021-08-09 11:09 UTC
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

Hi, we are using Twilio's recording and composition funcationalites to record group room session call, and facing one issue related to Enable/Disable the media tracks. Tested this with only one user in the group room call.

**Expected behavior:**

Once the recording started, user mutes both audio and video track , after a while user enbales their audio alone by unmuting the mic,  so in the completed composition media file, we should hear only the user's audio and video should be black.

**Actual behavior:**

Once the user enbales thier audio alone, we are seeing a frozen video frame in completed compostion media file, that frozen video frame reamains there in the recording until the user enables their video.

Confirmed with Room callback events that at the time when audio was enabled, video track was in disabled state only( received track-enabled statuscallback event from twilio for audio track only).

**Software versions:**

 - [x] Browser(s): Chrome 92.0.4515.131
 - [x] Operating System: Windows 10 Pro
 - [x] twilio-video.js: 2.15.3
 - [x] Third-party libraries (e.g., Angular, React, etc.):

**Comment by PikaJoyce** [comment] 2021-08-11 00:00
Hi @venkateshdinfy,

Thank you for submitting this issue. I'll investigate this further and reach out to the team about this as well and will respond back with an update.

Best,
Joyce

**Comment by PikaJoyce** [comment] 2021-08-11 17:49
Hi again @venkateshdinfy,

The team has gotten back to me with a possible workaround. You would have to stop the media track completely and republish instead of muting/unmuting tracks, as well as not use trimming when creating a composition. This would keep the gap as a single black frame continuously muted. Whereas with trimming enabled, that gap would disappear because there is no media. 

However, I'm going to reach out once again to another team to potentially get a bit more insight on this issue. Again, I'll keep this updated!

Thanks,
Joyce

**Comment by venkateshdinfy** [comment] 2021-08-12 05:04
Thanks @PikaJoyce  for your response, the thing with completley stopping the media tracks and publishing again is , there is a delay every time between when the user umutes his audio/video and when other users are able to hear or view thier audio/video, thats why we went with enable/disable approach(Twilio site recommended this way)

we don't use any cropping in compostion and we also tried stopping and unpublishing/publishing the video track alone when user mutes/unmutes, but the issue still persists, we are still seeing the frozen frame in the completed composition.

**Comment by venkateshdinfy** [comment] 2021-08-24 16:34
Hello @PikaJoyce, please let me know if there is any update on this.

**Comment by PikaJoyce** [comment] 2021-08-24 17:03
Hi there @venkateshdinfy,

Apologies for the long wait. Unfortunately, the teams responsible for this have not provided another possible workaround or fix yet. I'll bump them again and I'll respond to this thread once I get an answer. 

Thank you for your patience,
Joyce

**Comment by PikaJoyce** [comment] 2021-09-08 18:13
Hey @venkateshdinfy,

This is more of a small update, but we've filed an internal ticket to track and investigate this issue as it is reproducible. 

Best,
Joyce

**Comment by venkateshdinfy** [comment] 2021-09-09 04:48
Thanks @PikaJoyce for the update.

**Comment by PikaJoyce** [comment] 2021-10-19 20:57
Hi @venkateshdinfy,

Apologies for the late response! Another small update, but the internal ticket that was filed to track this effort is VIDEO-6854. But with that being said, I've reached out to the team as they are currently focused on other high priority initiatives, it may take some time before they can investigate this issue further. 

The team has a possible suggestion to get a user to unmute both audio and video at the same time. As their understanding of the situation currently is that the frozen frame happens when the user first unmutes the audio, and after some time, then video is unmuted. 

Please try it out and let me know if it works. We appreciate your patience!

Best,
Joyce

**Comment by PikaJoyce** [comment] 2022-01-18 19:41
Hi @venkateshdinfy,

The team has gotten back to me with regards to your issue and they've stated that this is likely not something they will tackle as this is a larger than expected effort. However, they have improved the MediaServer recently and they suggest to **unpublish the track rather than muting** to reduce the latency of the recording. I'll be closing this issue now but if you have any other questions, please don't hesitate to reach out! Apologies for any inconveniences this may have caused you.

Best,
Joyce

**Closed by PikaJoyce** 2022-01-18 19:41 UTC
Labels: bug filed
