### ISSUE TITLE
Issues ICE server failure and related to it.

### ISSUE THREAD

**Issue by kumail-raza** [twilio/twilio-video.js#503] opened 2019-01-09 20:22 UTC
There are many random issues I am oberving since a month. 

While video chat is going on participant video disappear and require a refresh to fix it.

On joining from one room to another without leaving the previous (on firefox as reported previously too) user media not share to other users in that group, again refresh is require to fix it but today on first refresh its not get fixed and sometime either of users video get disappear.

This is really affecting my application now.

Also what is the update regarding the issues related to ICE?

**Comment by frederikbosch** [comment] 2019-01-29 10:57
I have the same issue. Firefox tells me something like `ice failed add a stun server`.

**Comment by frederikbosch** [comment] 2019-01-29 10:59
If this is a connection problem, I would be interested how to retry this programmatically. Although I would also guess that retrying is something that happens in this library itself.

**Comment by frederikbosch** [comment] 2019-01-29 11:07
I just found out I was using Twilio 1.10, upgraded to 1.15. Let's see what happens. @smkrn110 What version are you using?

**Comment by frederikbosch** [comment] 2019-01-29 14:36
And then I now also get the following from time to time.

```
WARN in [LocalParticipant #1: PA348bcd4fe8095c2c749da640f71b9981]: Failed to publish the LocalVideoTrack: Server is unable to apply a remote media description
```

**Comment by frederikbosch** [comment] 2019-01-29 14:47
For the Twilio operators my room SID is `RM50cbe1f63a28c976ef3e018c87459d45`.

**Comment by frederikbosch** [comment] 2019-01-29 14:50
The funny part is, once I join the room with another Firefox browser (private window), then both Chrome and the new Firefox are seeing the video.

**Comment by manjeshbhargav** [comment] 2019-01-29 18:41
Hi @frederikbosch ,

Thanks for writing in with your question. We are looking into the ICE failure issues with Firefox for group Rooms, and will get back to you when we have more information.

Regarding the Track publication failure, we have a fix for it under development and will reach out to you once it is available.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by frederikbosch** [comment] 2019-01-31 10:58
Thanks, let me know if I can do anything to help.

**Comment by smkrn110** [comment] 2019-01-31 13:31
> If this is a connection problem, I would be interested how to retry this programmatically. Although I would also guess that retrying is something that happens in this library itself.

I really interested in the retry mechanism (re-connectivity) since due to network issues and on slow bandwidth, the issue does occur.

I am currently working with twilio-video.js@2.0.0-beta5.

**Comment by smkrn110** [comment] 2019-02-05 14:13
@manjeshbhargav, thanks for being so responsive. 

I like to tell you without enabling of it, 'reconnecting' and 'reconnected' event still emits. I tried with `_useTwilioConnection: true,` , also. I am receiving an error on reconnecting event **Media connection failed.**, although after that reconnected event also emit. 

Issue I am facing is, media tracks remains stuck. I did try re-attaching of the tracks but no success.

**Comment by manjeshbhargav** [comment] 2019-02-07 20:23
Hi @frederikbosch 

We just released twilio-video.js@1.15.2, which fixes this error that you were seeing:
```
WARN in [LocalParticipant #1: PA348bcd4fe8095c2c749da640f71b9981]: Failed to publish the LocalVideoTrack: Server is unable to apply a remote media description
```
This should also be fixed in 2.0.0-beta6 when it is released.

@smkrn110 ,

If you don't set `_useTwilioConnection: true`, then "reconnecting" and "reconnected" events will still fire, but only for media interruptions. Setting it to true will also emit these events for signaling connection interruptions.

Can you provide a Room SID where your media tracks were stuck after reconnecting?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by smkrn110** [comment] 2019-02-08 11:36
@manjeshbhargav 

> Can you provide a Room SID where your media tracks were stuck after reconnecting?

Not available with the Room SID for now, but when gets stuck, on reconnecting event, I received the **Media connection error** in console, on investigating with the SDK I have change the following code,

from
     `room.emit('reconnecting', new MediaConnectionError());`
to 
      `room.emit('reconnecting', error); `

Will update you as encounter the error again, also with the Room SID.

**Comment by manjeshbhargav** [comment] 2019-02-08 16:56
@smkrn110 

We will officially announce this feature in 2.0.0-beta6, where you will get different error codes for signaling and media related reconnections.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by jamesgraham** [comment] 2019-02-26 17:06
Hi @manjeshbhargav when can we expect 2.0.0-beta6 to be cut?

**Comment by manjeshbhargav** [comment] 2019-02-26 18:41
Hi @jamesgraham ,

We are ironing out the last few bugs. We're aiming to roll out sometime early next week.
I'll reach out to you when it's available.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by jamesgraham** [comment] 2019-03-06 10:34
Thanks @manjeshbhargav are we still on track?

**Comment by manjeshbhargav** [comment] 2019-03-20 22:05
Hi @jamesgraham , @smkrn110 ,

[twilio-video.js@2.0.0-beta6](https://github.com/twilio/twilio-video.js/blob/2.0.0-beta6/CHANGELOG.md) is now available. Please try it out and let me know.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by frederikbosch** [comment] 2019-03-22 09:23
@manjeshbhargav I still the ICE PRs not merged, see #547 and #537. Would 2.0.0-beta6 still help for ICE improvements?

**Comment by manjeshbhargav** [comment] 2019-05-09 00:17
@frederikbosch ,

[2.0.0-beta9](https://github.com/twilio/twilio-video.js/blob/2.0.0-beta9/CHANGELOG.md) is now available. The ICE improvements PR will be available in the next beta version. Please try it out and let me know if you're still experiencing issues on Firefox. Please refer to [COMMON_ISSUES.md](https://github.com/twilio/twilio-video.js/blob/2.0.0-beta9/COMMON_ISSUES.md) to make sure any issues you are experiencing are not listed here, and then file a separate issue for it.

Sorry for the delayed response.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by smkrn110** [comment] 2019-05-21 10:55
Recently we are experiencing, ICE Failure very frequently, after every 2-3 seconds we are receiving consecutive ICE failure connection attached is the image.

![image_2019_05_21T10_47_39_754Z](https://user-images.githubusercontent.com/2698458/58090177-12371000-7be0-11e9-83c3-7aecddae9a06.png)

### Environment

**Chrome :** Version 74.0.3729.157 (Official Build) (64-bit)
**RoomSID:** RMfa95ba39c874a02948f4b2df7e00798d
**ParticipantSID :** PAfbbfd7040377e7e3fe9901523bcfa50b
**Twilio Version:** 2.0.0-beta5

**Comment by manjeshbhargav** [comment] 2019-05-21 20:51
Hi @smkrn110 ,

We recently released [2.0.0-beta9](https://github.com/twilio/twilio-video.js/blob/2.0.0-beta9/CHANGELOG.md), which officially supports the [Network Reconnection API](https://www.twilio.com/docs/video/reconnection-states-and-events). Please try it out and let me know if you still experience the same issues.

Regarding your specific Room that you shared here, it looks like there is a problem with the network since the websocket connection that reports media statistics is also being interrupted constantly.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by smkrn110** [comment] 2019-06-15 11:54
@manjeshbhargav 

Thanks, let me try with this I am upgrading to beta11 and will get back to you on this. :-)

**Comment by smkrn110** [comment] 2019-06-17 11:18
@manjeshbhargav 

Thanks for providing the reconnection mechanism, really looking for that from months and great to see that it is working fine (so far), after upgraded to **v2.0.0-beta11.**

If this fix, also for ICE Failure issue, then this issue could mark as close.

Thanks,
Kumail Raza

**Comment by ing-fabian** [comment] 2020-01-16 09:39
Hello,

We are still having a lot of issues with ICE Failure connections. First this only happen with Safari/Firefox but now it happens randomly with Chrome and after retrying a couple of times it gets connected. We were using the version 2.0.0-beta14, update to the latest stable version 2.0.0 but the problem is still there. Any news on this problem?

Thanks!

**Comment by manjeshbhargav** [comment] 2020-01-16 17:15
Hi @ing-fabian ,

Can you provide a Room SID where you're experiencing ICE issues? That will help us start investigating.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by ing-fabian** [comment] 2020-01-17 08:48
Hi @manjeshbhargav, Sure, I'll reproduce the error and collect all the information I can.

Thanks for the quick reply.

**Comment by ing-fabian** [comment] 2020-01-20 12:32
Hi @manjeshbhargav, 

I did a test with this SID 2324b98d-58e1-444e-ae96-8122c256a780:

I follow the below steps:

1. Try Connecting from Firefox, Got ICE errors 4 times, It didn't connect but Firefox keep trying to connect.

2. Try connecting from Safari, Got ICE error once, but somehow It didn't try to connect again.

3. Try connecting with Chrome, get connected without problem. 

Please tell me if you need any other information.

Version used on this test: 2.0.0-beta14
Network: All our connections are behind a proxy

**Comment by ankit2711** [comment] 2020-02-03 11:01
We are also stuck by the same issue on Safari and Firefox. 
ROOMSID: RM415c240b11f236db5e27c305ca789e3d
Both browser when tried from behind the corporate proxy do not show up the remote track and we get ICE failures
WARN in [PeerConnectionV2 #1: 3505ce13-dff4-41e0-afe0-e66805e50d42]: ICE failed; attempting to restart ICE

**Closed** 2020-04-27 17:40 UTC
Labels: Network Handoff, bug
