### ISSUE TITLE
Remote participant's video is intermittently blank after publication.on('subscribed' is called

### ISSUE THREAD

**Issue by grp06** [twilio/twilio-video.js#1029] opened 2020-05-23 06:13 UTC
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

*Debug Logs*
Here are logs for 3 different connection scenarios

1. some abnormality with ICE connection
2. isStarted is false. We've subscribed but don't see video
3. every works fine

https://gist.github.com/grp06/aacbc3e3a12b1f0388edce33c6d62c14

**Code to reproduce the issue:**

```js
// p2p room
// for the purposes of this demo - this all runs within an onClick handler
fetch(`${endpointUrl}/api/token`, {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
  },
  body: JSON.stringify({ roomId, myUserId: userId }),
})
  .then((res) => res.json())
  .then(async ({ token }) => {
    const videoTrack = await createLocalVideoTrack()

    const room = await connect(token, {
      name: roomId,
      tracks: [videoTrack],
    })

    const { localParticipant } = room
    function trackPublished(publication) {
      console.log(`Published LocalTrack: = `, publication.track)
    }

    // Access the already published LocalTracks.
    localParticipant.tracks.forEach(trackPublished)

    function remoteTrackPublished(publication, participant) {
      console.log(
        `RemoteParticipant ${participant.identity} published a RemoteTrack: `,
        publication
      )
      if (publication.isSubscribed) {
        console.log('publication.isSubscribed = true. Going to append')
        console.log('publication.track = ', publication.track)
        const remoteDiv = document.getElementById('remote-media-div')
        if (remoteDiv) {
          const attachedTrack = publication.track.attach()
          remoteDiv.appendChild(attachedTrack)
        }
      }
      publication.on('subscribed', (track) => {
        console.log(`LocalParticipant subscribed to a RemoteTrack: `, track)
        console.log('publication.on Subscribed fired. Going to append')
        const attachedTrack = track.attach()
        document.getElementById('remote-media-div').appendChild(attachedTrack)
      })

      publication.on('unsubscribed', (track) => {
        console.log(`LocalParticipant unsubscribed from a RemoteTrack: `, track)
      })
    }

    function participantConnected(participant) {
      console.log('setting identity')
      setPartner(participant.identity)

      participant.tracks.forEach((publication) => {
        remoteTrackPublished(publication, participant)
      })

      participant.on('trackPublished', (publication) => {
        remoteTrackPublished(publication, participant)
      })

      participant.on('trackUnpublished', (publication) => {
        console.log(
          `RemoteParticipant ${participant.identity} unpublished a RemoteTrack: ${publication}`
        )
      })
    }

    room.participants.forEach(participantConnected)
    room.on('participantConnected', participantConnected)

    room.on('participantDisconnected', (remoteParticipant) => {
      const remoteDiv = document.getElementById('remote-media-div')
      if (remoteDiv) {
        remoteDiv.innerHTML = ''
      }
    })

    window.addEventListener('beforeunload', () => {
      room.disconnect()
    })

    room.on('disconnected', function (rum, error) {
      console.log('room.on disconnected ', rum)
      rum.localParticipant.tracks.forEach(function (track) {
        track.unpublish()
      })

      const remoteDiv = document.getElementById('remote-media-div')
      if (remoteDiv) {
        remoteDiv.innerHTML = ''
      }
    })
  })
```

**Expected behavior:**
when `remoteParticipant.on('trackSubscribed'` fires, their video should be attached every time
TODO

**Actual behavior:**
when `remoteParticipant.on('trackSubscribed'` fires, the video doesn't appear. isStarted is false

**Software versions:**

 - [x] Browser(s): Version 81.0.4044.138 (Official Build) (64-bit)
 - [x] Operating System: Mac osx catalina 10.15
 - [x] twilio-video.js: 2.4.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): React

The following screen shot shows the `console.log` that occurs when I look at the same "trackSubscribed" function is called. On the left side, the video is shown on the page. On the right side, it's not.

<img width="1648" alt="Screen Shot 2020-05-23 at 1 13 10 AM" src="https://user-images.githubusercontent.com/1573959/82723224-42a20600-9c9b-11ea-9c34-064494892260.png">

This has been perplexing me and another developer for 3 days now. We're unable to determine what's causing the "isStarted" to be false from time to time.

**Comment by maxsolely** [comment] 2020-05-23 17:43
Also have been experiencing this problem. Any suggestions on how to remedy the problem would be greatly appreciated. Thanks

**Comment by makarandp0** [comment] 2020-05-23 22:15
Thank you for reporting this issue @grp06, 

This does sound weird. I also noticed that in your console log the track is showing as `readyState = "ended"` which means that remote source is not providing any data for this track.
The `track.started`  gets set to true when the track starts flowing data.   

Can you share some room sids where this issue showed up? The root cause maybe at the remote participant side. Which os browser are they on? Does this issue repro consistently, if so if you can share the repro steps, or app where I can try the repro that would be great. 

Thanks,
Makarand.

**Comment by grp06** [comment] 2020-05-24 18:41
@makarandp0 thanks for the quick reply. The roomSid we just reproduced is `RMf8a2f850b786ec3b0dc06aa08841f4a7` 

In the latest test, we've produced the logs here: https://gist.github.com/grp06/7395b17844fe8c82663fd3854441b312

In this scenario person #2 refreshes the page and person #1 gets the logs as shown. Seems like there's an issue with connecting to ice servers.

**Comment by makarandp0** [comment] 2020-05-25 15:49
Hey @grp06 , Thank you for the update. I took a quick look at the room-sid (RMf8a2f850b786ec3b0dc06aa08841f4a7), and found that there were 43 users joined to this peer-to-peer room - although not at the same time. Was this because repro takes lots of connect disconnect attempts? There certainly looks like intermittent ice-connectivity issues. This being a p2p room, we do not have much visibility into the media tracks that flow in the room. Do you by chance have a simpler repro steps that does not involve multiple connect/disconnect ? Have you tried group rooms to see if you see similar issue?

thanks,
Makarand

**Comment by manjeshbhargav** [comment] 2020-05-26 19:01
Hi @grp06 ,

I noticed that in all the Rooms whose logs you have shared, you are only acquiring a lone STUN server and there are no TURN servers. This might explain why you are intermittently not able to establish media connections. Is this happening intermittently, or are you always unable to obtain TURN servers?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by grp06** [comment] 2020-05-26 19:09
@manjeshbhargav This is happening intermittently. A lot of the time when we're testing, the connections happen flawlessly, as expected. 

I'm actually not sure if it's connecting/falling back to TURN servers. Is there a way for me to debug this?

You mention that we're acquiring only one STUN server. Is there something we should be doing to set up more than one?

We are running an app where there's one "admin" user that assigns users to rooms. Both of us are running 3 users simultaneously on each of our laptops. Could that be a problem?

**Comment by manjeshbhargav** [comment] 2020-05-26 19:31
Hi @grp06 ,

The next time this happens, you can search for "got ice servers" in your browser console logs. That will show you what servers were returned by our service. You can also check the network tab for the response to query for ICE servers to the ECS (endpoint configuration service).

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by grp06** [comment] 2020-05-26 22:10
Hi Manjesh, here are some screenshots of what I'm getting in the console when there are ICE server errors: 

![Uploading Screen Shot 2020-05-26 at 2.18.00 PM.p
<img width="1330" alt="Screen Shot 2020-05-26 at 2 17 48 PM" src="https://user-images.githubusercontent.com/1573959/82955134-298ba480-9f7c-11ea-9c29-2f97fdbe1b09.png">
<img width="1308" alt="Screen Shot 2020-05-26 at 2 17 41 PM" src="https://user-images.githubusercontent.com/1573959/82955138-2b556800-9f7c-11ea-904d-bd99d3232a9c.png">
<img width="1319" alt="Screen Shot 2020-05-26 at 2 17 11 PM" src="https://user-images.githubusercontent.com/1573959/82955140-2bedfe80-9f7c-11ea-8413-34b170a48db8.png">


ng…]()

**Comment by manjeshbhargav** [comment] 2020-05-26 23:33
Hi @grp06 ,

Can you share the contents of the **Response** tab instead of the **Headers** tab?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by makarandp0** [comment] 2021-03-09 00:03
Hey @grp06, I am  closing this old ticket, Please reopen new issue if you are still experiencing this issue.

**Closed by makarandp0** 2021-03-09 00:03 UTC
