### ISSUE TITLE
Cannot read properties of null (reading 'frameWidth') at getstats

### ISSUE THREAD

**Issue by Dosant** [twilio/twilio-video.js#1968] opened 2023-01-20 15:43 UTC
Unfortunately, I don't have a reproduction for this issue, but this error relatively often occurs in our error monitoring. 

The stack trace is: 

```
TypeError: Cannot read properties of null (reading 'frameWidth')
  at <anonymous>(webpack:/./node_modules/twilio-video/es5/webrtc/getstats.js:490:59)
  at Array.forEach(<anonymous>)
  at standardizeChromeOrSafariStats(webpack:/./node_modules/twilio-video/es5/webrtc/getstats.js:449:17)
  at apply(webpack:/./node_modules/twilio-video/es5/webrtc/getstats.js:318:21)
```

And the error is coming from here: 

https://github.com/twilio/twilio-video.js/blob/6b625db655e8f6e23c9232616adb24bb2c5886c0/lib/webrtc/getstats.js#L542

The type error happens because `track` is null. 

I don't know what's precisely leads to this error. It happens sproadically during the call. All the errors I see are coming from desktop users on Chrome 109.0.0.
I also don't know what is the impact on the end users.

I would appreciate help in troubleshooting this error. If there is anything else I should attach, please let me know.
I didn't try to upgrade to a newer version, as I didn't see anything related to this error mentioned in the release notes.

**Software versions:**

 -  Browser(s): Chrome 109.0.0
 - Operating System: Mac OS / Windows
 -  twilio-video.js: 2.24.3
 -  Third-party libraries (e.g., Angular, React, etc.): Angular

**Comment by fippo** [comment] 2023-01-23 09:26
This looks like @henbos [removal of the deprecated track and stream stats in Chrome 109](https://groups.google.com/g/discuss-webrtc/c/Bxrxr8gw08Y/m/RGn-iME-AgAJ)
If you can reproduce this when starting Chrome with --force-fieldtrials=WebRtcUnshipDeprecatedStats/Enabled/ (or it reproduces in Beta/Canary) then that is it.

**Comment by henbos** [comment] 2023-01-23 09:40
Thanks @fippo. If you want the "input" frame width (as opposed to the sent frame width, which can be lower if encoding in a downscaled resolution) the place to look is the [RTCVideoSourceStats](https://w3c.github.io/webrtc-stats/#dom-rtcvideosourcestats) which has type "media-source". It is referenced by the RTP stream's [mediaSourceId](https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-mediasourceid).

**Comment by henbos** [comment] 2023-01-23 09:41
E.g. `report.get(rtpStream.mediaSourceId).width`

**Comment by AllyTang** [comment] 2023-01-25 03:37
We got the same issue from our clients recently. I was wondering if Twilio is working on this bug as we can't force our clients to update to chrome 109 :)

**Comment by AllyTang** [comment] 2023-01-25 03:39
@Dosant does this issue happen to all of your clients with Chrome 109? or just some of them? I found that some of our clients with Chrome 109 don't have this issue.

**Comment by Sumit134coder** [comment] 2023-01-25 06:02
@Dosant Facing this issue while implementing screen share using `twilio-video` . I am using react . Any solutions ?

**Comment by manjeshbhargav** [comment] 2023-01-25 18:02
@Dosant , @fippo ,

I am going to try and reproduce this today, and work on fixing it. I have created a ticket to start working on it. Please watch this space for updates.

**Comment by manjeshbhargav** [comment] 2023-01-25 22:36
@Dosant , @fippo ,

I can confirm that the root cause is the removal of the deprecated track stats report from the `getStats()` response. I will cut a release candidate with the fix to rely on media source stats instead by end of day today, and hopefully we can release it by the end of this week. Please watch this space for updates.

Thanks for bringing this issue to our notice!

**Comment by alexandermaisey** [comment] 2023-01-26 16:05
Following this, experiencing this exact error.  When it happens, I entirely lose ability to click any DOM elements.

**Comment by FabianaMendes** [comment] 2023-01-26 18:25
We are getting the same error here in our sentry. Chrome 109.0.0 too. We also don't know what is the impact on the end users. As it is not possible to predict if there will be a release with this fix or when there will be a fix, if anyone here has a solution that we can apply right away I would greatly appreciate it.
![image](https://user-images.githubusercontent.com/63737491/214918628-f91d9980-cb1a-491f-9ed9-72641813af8f.png)
![image](https://user-images.githubusercontent.com/63737491/214918729-a5729e5e-30ca-45d3-a1cd-dc1b8d5de84e.png)

**Comment by lehno** [comment] 2023-01-27 11:48
We work with Clinical session using Twilio and currently it is not working for people that upgraded the browser, also waiting for the release of the fix

**Comment by manjeshbhargav** [comment] 2023-01-27 18:05
@FabianaMendes , @lehno ,

This bug should not affect the user experience w.r.t video/audio. It does however break `Room.getStats()`, if you are calling that API within the app.

**Comment by manjeshbhargav** [comment] 2023-01-27 22:25
@alexandermaisey @FabianaMendes ,

While we are working on the release, you can work around this by not using `Room.getStats()` in your app, and adding `insights: false` to ConnectOptions. This disables the SDKs periodic reporting of media stats for the Participant.

Please let me know if this works for you.

**Comment by alexandermaisey** [comment] 2023-01-30 16:17
> @alexandermaisey @FabianaMendes ,
> 
> While we are working on the release, you can work around this by not using `Room.getStats()` in your app, and adding `insights: false` to ConnectOptions. This disables the SDKs periodic reporting of media stats for the Participant.
> 
> Please let me know if this works for you.

Thanks for this, it has resolved the issue I was encountering.  Any ETA on the release with the real fix?  Thanks.

**Comment by manjeshbhargav** [comment] 2023-01-30 19:11
@alexandermaisey ,

QA is in progress for the RC, and assuming everything goes well, we should be able to release before the end of this work week (Friday).

**Comment by anna-vasilko** [comment] 2023-01-30 21:13
Hello all, 
Today Google reverted an experiment which caused this issue in Chrome stable (109) ([removal of the deprecated stats](https://groups.google.com/g/discuss-webrtc/c/Bxrxr8gw08Y/m/2NnGSeHnAAAJ)).

However the change is still active in beta and canary versions of Chrome and [will return to stable in the future](https://groups.google.com/a/chromium.org/g/blink-dev/c/NZVXsJQ7tV8), so we advice you to update to the upcoming version of the SDK with the changes from @manjeshbhargav as soon as it becomes available, to avoid being impacted in the future. 

I have to acknowledge it took unusually long time for us to discover this breaking change and to act on it. We are going to do a retrospective internally to understand the reasons better and to catch such issues sooner in the future.

**Comment by Dosant** [comment] 2023-01-31 16:18
Thank you for the updates and for working on the fix

> While we are working on the release, you can work around this by not using `Room.getStats()` in your app, and adding `insights: false` to ConnectOptions. This disables the SDKs periodic reporting of media stats for the Participant.
> 
> Please let me know if this works for you.

@manjeshbhargav, we don't use `Room.getStats()` and we updated to `insights: false`. We still see the same error in our error monitoring from the users with the latest version of our app. 

Is there a chance that `insights: false` is not sufficient to not hit the bug? 
We are also currently on `twilio-video.js: 2.24.3`, so I wonder if this workaround doesn't work for older versions of twilio-video.js like ours. Before I try to update to the newer version, I wonder if you could confirm if we could be still hitting the bug with `insight:false` because of the older version of the library.

**Comment by alexandermaisey** [comment] 2023-01-31 20:53
> Thank you for the updates and for working on the fix
> 
> > While we are working on the release, you can work around this by not using `Room.getStats()` in your app, and adding `insights: false` to ConnectOptions. This disables the SDKs periodic reporting of media stats for the Participant.
> > Please let me know if this works for you.
> 
> @manjeshbhargav, we don't use `Room.getStats()` and we updated to `insights: false`. We still see the same error in our error monitoring from the users with the latest version of our app.
> 
> Is there a chance that `insights: false` is not sufficient to not hit the bug? We are also currently on `twilio-video.js: 2.24.3`, so I wonder if this workaround doesn't work for older versions of twilio-video.js like ours. Before I try to update to the newer version, I wonder if you could confirm if we could be still hitting the bug with `insight:false` because of the older version of the library.

@anna-vasilko @manjeshbhargav @Dosant 
It's important to note that Chrome reverted this issue; I was still encountering difficulties until I read through the thread Anna linked and saw that in order to apply the reversion, you need to *restart Chrome*.  I haven't had issues since doing so.  Hope this helps.

**Comment by manjeshbhargav** [comment] 2023-02-02 00:44
twilio-video@2.26.1 is now available. I'm closing this issue, but let's continue the conversation here.

**Closed by manjeshbhargav** 2023-02-02 00:44 UTC

**Comment by zakjholt** [comment] 2023-05-04 17:09
Since upgrading `twilio-video` versions to solve this issue, I'm having issues using `@twilio/video-processors@2.0.0`

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/18562092/236276441-9a5c7154-cd67-48c3-b4f3-73374c483023.png">

**Comment by MohamedBlossom** [comment] 2023-05-05 10:05
@zakjholt What's the version you're using for `twilio-video`?

**Comment by MohamedBlossom** [comment] 2023-05-05 10:42
@anna-vasilko I was using twilio-video 2.18.1 and @twilio/video-processors 1.0.2, video processing background was working smoothly.

However after upgrading twilio-video to 2.27.0 and keeping @twilio-video-processors 1.0.2 have some issues with video background image processing.

<img width="572" alt="image" src="https://user-images.githubusercontent.com/117749161/236436917-6f941601-5da5-4634-935c-705d58ffb0fc.png">

Upgrading @twilio-video-processors to 2.0.0 throwing similiar issue as @zakjholt is facing.
