### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by ezelohar** [twilio/twilio-video.js#542] opened 2019-02-13 10:54 UTC
- [y ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [y ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [y ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [y ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**
- Install basic Quickstart video app from github and follow up steps to set it up and run.
- Open chrome and open chrome inspect
- Toggle device toolbar (responsive screen on firefox)
- Refresh the page

Video showing the error
https://www.useloom.com/share/1f68be9a9bce4bafb75a91c003cb5433

**Expected behaviour:**
Not showing the error and connecting to the twilio
TODO

**Actual behaviour:**
Show the error, and don't connect to twilio

**Software versions:**

 - [Chrome ] Browser(s):
 - [ MacOs] Operating System:
 - [ 1.15.2] twilio-video.js:

**Comment by ayavilevich** [comment] 2019-02-13 13:49
It happens here as well but when the device that is selected in the "Device toolbar" is iPhone or iPad. Doesn't happen when the device is Responsive or Pixel. It seems, therefore, this is due to browser detection logic. When the browser is Chrome but the userAgent is for an iOS device then detection fails to choose the right operation mode.

This didn't happen in previous twilio-video library versions.

Preferably the detection will be made without relying on userAgent. For example the `guessBrowser` logic you use works in a way that is similar to:

```
if (typeof webkitRTCPeerConnection !== 'undefined') {
  console.log('chrome');
} else if (typeof mozRTCPeerConnection !== 'undefined') {
    console.log('firefox');
 } else if (typeof RTCPeerConnection !== 'undefined') {
if (getUserAgent().match(/AppleWebKit\/(\d+)\./)) {
  console.log('safari');
}
}
```

**Comment by manjeshbhargav** [comment] 2019-02-13 17:49
Hi @ezelohar @ayavilevich ,

Thanks for writing in with your question. We are aware of this issue. This is because of our dependence on the prefixed PeerConnection classes which we depend on for browser detection. Our next release will depend purely on the user agent, which should fix this error. We will reach out to you once this is available.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by ayavilevich** [comment] 2019-02-13 18:17
Hi @manjeshbhargav 

Are you sure that is what you are planning to do? "Feature detection" is the better practice compared to browser detection based on userAgent.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent

It seems at the moment you are doing userAgent detection somewhere, since the "Device toolbar" affects the userAgent but doesn't affect prefixed PeerConnection objects. The issue probably arises from using both methods in an incompatible way. Assuming you can switch to just "Feature detection" this should not be an issue.

**Comment by manjeshbhargav** [comment] 2019-02-13 22:48
Hi @ayavilevich ,

We try to avoid that where we can, but there are WebRTC-related bug fixes/workarounds on particular browser versions which can't be detected using feature detection. So, unfortunately we do need to rely on the user agent. As long as WebRTC is a moving target and does not settle down, I'm afraid we would need some kind of user agent based detection.

Hope that clears things up for you.

Thanks,

Manjesh Malavalli

**Comment by yash-curefit** [comment] 2019-04-10 09:53
@manjeshbhargav any updates on this ?

**Comment by manjeshbhargav** [comment] 2019-04-10 17:07
Hi @yash-curefit , @ayavilevich , @ezelohar ,

The latest version of twilio-video.js: 1.17.0 has fixed this issue. Please try it out and let me know. I will close this issue for now.

Thanks,

Manjesh Malavalli
JSDK Team

**Closed by manjeshbhargav** 2019-04-10 17:07 UTC

**Comment by ayavilevich** [comment] 2019-04-10 18:38
Done a quick test with 1.17.0 and couldn't reproduce any more. Looks good. Thanks.
