### ISSUE TITLE
(TypeScript) track.attach() is not a function, but it is

### ISSUE THREAD

**Issue by Hisashin7331** [twilio/twilio-video.js#1800] opened 2022-06-06 21:07 UTC
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**
```ts
// any usage of track.attach(), no matter if it's local or remote participant

useEffect(() => {
   console.log(
      room?.localParticipant.tracks.forEach((track) => {
         console.log('attach()', typeof track.track.attach, !!track.track.attach);
      }),
   );
}, [room]);
```

**Expected behavior:**
track.attach() function attaches tracks to the DOM

**Actual behavior:**
I get a TypeScript error saying  
```
Property 'attach' does not exist on type 'LocalTrack'.
   Property 'attach' does not exist on type 'LocalDataTrack'.ts(2339)
```

**Logs:**
```attach() function true```

**Software versions:**

 - [x] Browser(s): Google Chrome 102.0.5005.61 (Official Build) (64-bit)
 - [x] Operating System: EndeavourOS; Build ID: 2021.12.17
 - [x] twilio-video.js: 2.21.2
 - [x] Third-party libraries: React 17.0.2, Typescript 4.5.4

**Comment by Hisashin7331** [comment] 2022-06-06 21:10
I searched on the internet, many people had this problem, but no one told them how to fix it, they just said something like "you are using it wrong" even though they were code snippets from the documentation

**Comment by charliesantos** [comment] 2022-06-07 20:29
@Hisashin7331 thanks for reaching out. We are not getting this same error in our reference app which also uses typescript. I'm not sure how you setup your project but can you please see our app and use it as a reference regarding how the attach function is being used? https://github.com/twilio/twilio-video-app-react

**Comment by manjeshbhargav** [comment] 2022-07-07 15:29
@Hisashin7331 ,

LocalDataTrack does not have the `attach()` method, whereas LocalAudioTrack and LocalVideoTrack do have it. So, when you are cycling through the LocalTrackPublications, each publication's `.track` can be an instance of any one of the above 3 classes, so `attach()` being available is not guaranteed. Hope this answers your question.

I will close this issue, since there is no other action item, but please feel free to ask for clarifications here, or open a new issue if you are seeing some other unexpected behavior.

**Closed by manjeshbhargav** 2022-07-07 15:29 UTC
