### ISSUE TITLE
Access Token expired or expiration date invalid (V2)

### ISSUE THREAD

**Issue by katranci** [twilio/twilio-video.js#471] opened 2018-12-02 22:23 UTC
Hello,

It seems like in some cases Video throws error 20104 in reconnect attempt after signalling fails. Below are the summary of debug logs.

```
2018-12-02 21:43:32.358Z | DEBUG in [TwilioConnection #3: wss://sdkgw.us1.twilio.com/signaling]: Consecutive heartbeats missed: 1

2018-12-02 21:43:38.308Z | DEBUG in [TwilioConnection #3: wss://sdkgw.us1.twilio.com/signaling]: Consecutive heartbeats missed: 2

2018-12-02 21:43:44.277Z | DEBUG in [TwilioConnection #3: wss://sdkgw.us1.twilio.com/signaling]: Consecutive heartbeats missed: 3

2018-12-02 21:43:44.284Z | INFO in [Room #2: RM72be00054a337b8f265534243b7d45e9]: Transitioned to state: reconnecting

2018-12-02 21:43:45.267Z | DEBUG in [TwilioConnection #4: wss://sdkgw.us1.twilio.com/signaling]: Created a new WebSocket: [object WebSocket]

2018-12-02 21:43:45.616Z | DEBUG in [TwilioConnection #4: wss://sdkgw.us1.twilio.com/signaling]: Incoming: {"body":{"version":1,"type":"error","participants":[],"code":20104,"message":"Access Token expired or expiration date invalid","subscribe":{"revision":1,"unsubscribe":[]}},"type":"msg"}

2018-12-02 21:43:45.616Z | DEBUG in [LocalParticipant #4: PA782a34de3a3a69b5585ef7730e6f189c]: Transitioned to state: disconnected
```

**Comment by katranci** [comment] 2018-12-03 16:46
The instances of this issue has been growing fast throughout today. I don't think Video SDK provides a way of that but do we need to refresh the access token in the background?

**Comment by manjeshbhargav** [comment] 2018-12-05 18:04
Hi @katranci ,

Thanks for writing in with your question. We will look at our logs and get back to you.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by innerverse** [comment] 2018-12-05 21:52
@katranci 

Sorry you're running into this.  I just reviewed your logs and I am seeing two issues here:
* JSDK-2226 / https://github.com/twilio/twilio-video.js/issues/468 - Bug where an `error` sent by the server is treated as a network disconnect in the JSDK for a TCMP connection.  When this happens, JSDK is incorrectly attempting to `sync` and reconnect.  Usually this results in a 20101 error.
* It appears that your Access Token used during this failed reconnect process was indeed expired.  Once a fix lands for JSDK-2226 you won't see this specific reconnect case happen.

As we will now attempt to reconnect a broken signaling connection, you'll want to ensure the token expiration length is long enough to handle the maximum time a Participant is allowed to be in the Room for your application (up to 4 hrs max). This is why you're seeing a 20104 here instead.

If it's ok, I'm closing this issue and you can track progress on the root cause here https://github.com/twilio/twilio-video.js/issues/468

**Closed by innerverse** 2018-12-05 21:52 UTC
Labels: signaling

**Comment by katranci** [comment] 2018-12-07 11:23
Sure, thanks for the update @innerverse.
