### ISSUE TITLE
isSupported on 2.4.0 broken with SSR

### ISSUE THREAD

**Issue by lmatheus** [twilio/twilio-video.js#997] opened 2020-05-05 17:24 UTC
Recently release version of twilio-video 2.4.0 has updated `isSupported` and introduced `navigator` to make a few checks, this introduced a problem when it comes to Server side rendering (for example using React in NextJS) as it does not exist server side.

To reproduce this error I have made a small example app:

https://github.com/lmatheus/twilio-video-ssr-is-supported

you can run `yarn` then `yarn dev` and open a browser using `http://localhost:3000`

**Expected behavior:**

`navigator` not defined should not cause `isSupported`to break server side rendered applications when imported 

**Actual behavior:**

When imported in a server side rendered React app
`ReferenceError: navigator is not defined`

**Suggestion:**
checking `navigator` been defined before calling it `typeof navigator !== 'undefined'`

**Comment by manjeshbhargav** [comment] 2020-05-05 19:07
Hi @lmatheus ,

Thanks for reporting this issue. I will confirm this issue using the app you have provided and do the needful. However, `isSupported` is meant to be run on the browser to see if it is officially supported by the SDK, so it doesn't really make sense to use it on the server side. I recommend that you update your code to use `isSupported` on the browser.

In the meantime, I will file a ticket to have `isSupported` return false when it runs on the server side.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by jamessharp** [comment] 2020-05-06 08:23
Just for clarity - there isn't a workaround for this at the moment because `isSupported` gets called when the module is imported (see [here](https://github.com/twilio/twilio-video.js/blob/43dff31d8d98e8b44766b00840e747ec1eb3c011/lib/index.js#L41)), so can't just "not be used on the server"

**Comment by Tyler-Churchill** [comment] 2020-05-11 22:34
Seeing this too, I cannot upgrade because of this unless I use something like patch-package

**Comment by manjeshbhargav** [comment] 2020-05-13 01:12
Hi @Tyler-Churchill , @jamessharp , @lmatheus ,

The [fix](https://github.com/twilio/twilio-video.js/pull/1013/commits/970b65a53aa73240cd066bfc4de8ac6995dfa363) is scheduled to be released in the upcoming release (2.5.0). We are going to cut a release candidate for QA some time this week. I'll reach out when the release is available.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment] 2020-05-28 02:11
Hi @Tyler-Churchill , @jamessharp , @lmatheus ,

[twilio-video.js@2.5.0](https://github.com/twilio/twilio-video.js/releases/2.5.0) is now available. Please try it out and let me know if this solves the issue for you. I'll close the issue, but we can continue the discussion here.

Thanks,

Manjesh Malavalli
JSDK Team

**Closed by manjeshbhargav** 2020-05-28 02:11 UTC
Labels: bug

**Comment by brcarey** [comment] 2021-06-18 03:35
Is it possible there has been a regression in relation to this issue? Seeing this in 2.15.0

**Comment by MonstraG** [comment] 2021-06-18 12:56
> 
> 
> Is it possible there has been a regression in relation to this issue? Seeing this in 2.15.0

Its not only possible, it is the case, new isSupport doesn't contain typeof check now.

**Comment by charliesantos** [comment] 2021-06-18 16:02
@brcarey @MonstraG thanks for bringing this to our attention. We will take a look.

**Comment by charliesantos** [comment] 2021-06-21 21:44
This has been fixed on 2.15.1.
