### ISSUE TITLE
Audio-only mode still shows video icon in Chrome.

### ISSUE THREAD

**Issue by macgregordennis** [twilio/twilio-video.js#51] opened 2017-02-13 00:43 UTC
My application uses both a video + audio and an audio-only mode for video conferencing and audio conferencing respectively. When I use the audio-only version (i.e. `client.connect({video: false})`), the video icon still shows up in the Chrome browser like so:

<img width="89" alt="screen shot 2017-02-12 at 4 41 30 pm" src="https://cloud.githubusercontent.com/assets/1322709/22867728/2f1e07ee-f142-11e6-97f8-2a10b3396d04.png">
<img width="124" alt="screen shot 2017-02-12 at 4 41 40 pm" src="https://cloud.githubusercontent.com/assets/1322709/22867729/31b4121e-f142-11e6-93c0-003e97ecec5d.png">

This creates a poor user experience because it gives users the impression that the video is activated when it is not.

How can this be fixed?

**Comment by markandrus** [comment] 2017-02-14 22:55
Hi @macgregordennis,

This is not something we can fix in twilio-video.js. Unfortunately, this is the behavior of Chrome itself. For example, try out [this JSFiddle](https://jsfiddle.net/3101mp8f/8/) I wrote using native APIs only. We request `audio` only, and yet the webcam icon appears (and remains even after we stop the MediaStreamTrack).

It's unfortunate that Chrome chose a webcam icon in this case instead of a microphone. If you hover over the icon you will see it does only indicate microphone permissions:

![screen shot 2017-02-14 at 2 43 01 pm](https://cloud.githubusercontent.com/assets/359154/22952988/0c7f9ef4-f2c4-11e6-992e-a98414186101.png)

As for the icon remaining, there is an outstanding Chrome bug, [617431: "This page is accessing your microphone" still present after removing all microphone access in settings](https://bugs.chromium.org/p/chromium/issues/detail?id=617431), that I've updated seeking to clarify whether this behavior is related.

Best,
Mark

**Comment by macgregordennis** [comment] 2017-02-16 20:36
Hi @markandrus,

That's unfortunate. It looks like a fix for this is waiting on Chrome itself. Thanks for the update and clarification!

Best,
Stewart

**Comment by markandrus** [comment] 2017-03-03 01:59
Hi @macgregordennis,

Just wanted to followup. jansson@chromium.org clarifies the icon is working as intended:

> The camera icon in the omnibar indicates that permissions has been given to the page, that's it.
> 
> The red recording indicator in the tab is present as long as a MediaStream is alive.

Unfortunately, we can't do much more here, so I'll close this ticket out.

Best,
Mark

**Closed by markandrus** 2017-03-03 01:59 UTC
Labels: Chrome, question

**Comment by macgregordennis** [comment] 2017-03-03 07:58
Hi @markandrus,

To make sure I fully understand, jansson is saying that a camera icon is used even if only microphone permissions have been given to the page? If this is the case, I will follow up with him for further discussion.

Best,
Stewart

**Comment by markandrus** [comment] 2017-03-03 18:51
@macgregordennis Yes, that's what I understood from the thread.

Thanks,
Mark
