### ISSUE TITLE
Anyone experiencing crashes with Chrome v122?

### ISSUE THREAD

**Issue by alxppp** [twilio/twilio-video.js#2043] opened 2024-02-27 15:09 UTC
Not a bug report but poll: is anyone experiencing tab crashes after the Chrome update to version 122? Multiple users from different companies are reaching out to us that their tabs are crashing with the "Aw, snap" message when a video call is active.

![image](https://github.com/twilio/twilio-video.js/assets/4237216/946ba3bb-87c7-4764-900a-b7748066b1f5)

We know from both Windows and MacOS users:
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

**Software versions:**

 - [x] Browser(s): Chrome v122
 - [x] Operating System: macOS, Windows
 - [x] twilio-video.js: 2.27.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): Vue.js

**Comment by spalmertwilio** [comment] 2024-02-28 00:00
Hi @alxppp!

Thank you for submitting.  Looks like Chrome submitted a fix:

https://chromium-review.googlesource.com/c/chromium/src/+/5328768.

Would you mind testing again update this issue with your findings?

Look forward to your reply.

**Comment by chaosloth** [comment] 2024-02-28 23:20
@alxppp I am getting customer reports of this exact issue with Chrome 122. I will ask the customer to retest also

**Comment by a-lindsay** [comment] 2024-02-29 01:30
I also have customers reporting this issue, is there any idea when Chrome will release an update that resolves this?

**Comment by spalmertwilio** [comment] 2024-02-29 16:22
Thanks for the response folks! Will one or more of you please send in an example Room SID and the version of the JS SDK you are using?  As I am not able to reproduce this with either our Quickstart or our Demo App using Chrome 122.   If you are using a third party SDK such as Flutter or React Native, have the owners of the Repos been notified?

**Comment by RafaRuiz** [comment] 2024-02-29 16:23
> Thanks for the response folks! Will one or more of you please send in an example Room SID and the version of the JS SDK you are using? As I am not able to reproduce this with either our Quickstart or our Demo App using Chrome 122. If you are using a third party SDK such as Flutter or React Native, have the owners of the Repos been notified?

There's one issue created: https://gitlab.com/twilio-flutter/programmable-video/-/issues/261#note_1795819376

but Flutter's SDK max version allowed is 2.14.0

**Comment by bautistagetahead** [comment] 2024-02-29 16:51
@RafaRuiz thank you, that's the exact error we are facing

**Comment by a-lindsay** [comment] 2024-03-06 14:23
Memory leak based crashing has been resolved in Chrome 122.0.6261.111, released 3/5/24

**Comment by sansarip** [comment] 2024-03-06 20:02
> I feel like @bautistagetahead 's issue is different then memory related Chrome crashing. My customers have seen no issues connecting to a video room on Chrome 122.
> 
> We see memory related crashes, it's explained in this Chromium issue report. https://issues.chromium.org/issues/326904528
> 
> It seems to be an issue with likely video processors, (background blur, virtual background). Crashing can be replicated by running the below JS fiddle for a long time (hours)
> 
> https://jsfiddle.net/danbriggs5/64p8vhuo/48/

Can confirm that I was only experiencing this memory leak issue when using video processing. Upgrading Chrome seems to have resolved the leak.

**Comment by spalmertwilio** [comment] 2024-03-06 22:48
@a-lindsay and @sansarip  you beat me to posting!   Thank you!

Thank you all who posted feedback.

For those following along this release: 
https://chromereleases.googleblog.com/2024/03/stable-channel-update-for-desktop.html

Detail of changes:
https://chromium.googlesource.com/chromium/src/+log/122.0.6261.94..122.0.6261.112?pretty=fuller&n=10000

Corrected this issue and will will close this issue.

**Closed** 2024-03-08 00:13 UTC
