### ISSUE TITLE
The dist folder of the beta 14 version contains the dist of beta9

### ISSUE THREAD

**Issue by frederikbosch** [twilio/twilio-video.js#784] opened 2019-10-23 12:59 UTC
The dist folder of the beta 14 version contains the dist of beta9. That basically means downgrading by upgrading.

**Comment by KaelWD** [comment] 2019-10-23 13:04
Duplicate of #768?

**Comment by frederikbosch** [comment] 2019-10-23 13:06
Nope, although is it close: the actual dist file is from beta9.

**Comment by makarandp0** [comment] 2019-10-23 17:09
@frederikbosch - Thank you for writing about this - Can you please elaborate. I do see correct version @ https://github.com/twilio/twilio-video.js/blob/2.0.0-beta14/dist/twilio-video.js

**Comment by makarandp0** [comment] 2019-10-24 17:45
@frederikbosch - Thank you for the clarification. 

I see  that: 
```
npm install twilio-video@2.0.0-beta14
``` 
resolves to correct version, but

```
npm install twilio-video@^2.0.0-beta14
```
resolves to wrong (twilio-video.js 2.0.0-beta9) version. And that is explained by #768.  dist folder for `beta14` looks correct to me. Can you please verify that you get right version if you pin your dependency to `twilio-video@2.0.0-beta14`

Thanks,
Makarand
JSDK Team

**Comment by frederikbosch** [comment] 2019-10-25 06:44
Clear, now I get it!

**Closed** 2019-10-25 06:44 UTC
Labels: duplicate, npm
