### ISSUE TITLE
Virtual background processor leads to higher CPU usage

### ISSUE THREAD

**Issue by Lisztos** [twilio/twilio-video.js#2007] opened 2023-06-13 09:48 UTC
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```ts
import { GaussianBlurBackgroundProcessor, VirtualBackgroundProcessor } from '@twilio/video-processors';
import { VideoTrack, AddProcessorOptions } from 'twilio-video';

const maskBlurRadius = 5;
const blurFilterRadius = 12;

const defaultProcessorOptions: AddProcessorOptions = {
  inputFrameBufferType: 'video',
  outputFrameBufferContextType: 'webgl2',
};

export default class VideoProcessor {
  processors = new VideoBackgroundProcessor();

  async getBlurBackground(blurLevel: number) {
    return this.processors.getGaussianBlurProcessor({
      maskBlurRadius,
      assetsPath: getBackgroundsPath(),
      blurFilterRadius: blurLevel,
    })
  }

  async blurVideoBackground(track: VideoTrack, blurLevel: number = blurFilterRadius) {
    const processor = await this.getBlurBackground(blurLevel);
    track.addProcessor(processor, defaultProcessorOptions);
  }
}

```
This is a snippet of our code, nonetheless, I follow standard implementation. 

I created a performance profile with both the following setups to test the difference in CPU usage. In the test, I switched from no virtual background to blurred virtual background.

Current Setup: 
* twilio-video: 2.26.2
* @twilio/video-processor: 1.0.2

With the current setup, you can see the CPU usage increase, having constant spikes. (screenshot 1)

![Screenshot 2023-06-09 at 18 13 15](https://github.com/twilio/twilio-video.js/assets/63045656/4ab1473c-faa1-4da9-86a9-0b826eb4d783)

Updated Setup: 
* twilio-video: 2.27.0
* @twilio/video-processor: 2.0.0

After updating versions and switching to the Webgl2 pipeline, the CPU usage maxed out and stayed high. (screenshot 2)

![upgraded-processor](https://github.com/twilio/twilio-video.js/assets/63045656/2850afb9-5591-49f2-afd0-f1b74bf5afac)

**Software versions:**

 

- [x] Browser(s): Chrome 105.0.5195.127
- [x] Operating System: Windows 10 Pro
- [x] Twilio-video.js: 2.27.0
- [x] Twilio-video Processor: 2.0.0
- [x] Third-party libraries (e.g., Angular, React, etc.): Vue.js

**Comment by CyranMS** [comment] 2023-06-14 17:37
@manjeshbhargav this is blocking us from upgrading

**Comment by anna-vasilko** [comment] 2023-06-15 00:05
Hi @CyranMS, thank you for the detailed report.
Our QE team is working to reproduce the performance degradation between mentioned versions. We will be setting priority of the issue based on their findings.

**Comment by anna-vasilko** [comment] 2023-06-20 20:42
Hey all, the team here was able to reproduce this issue. We prioritize fixing it in this sprint.

**Comment by CyranMS** [comment] 2023-06-21 17:51
That is great to hear and very fast. Thanks @anna-vasilko!

In the release note it said that webgl2 needs uo to 30% less cpu. Is that claim still accurate? We are upgrading mainly because of that benefit.

**Comment by manjeshbhargav** [comment] 2023-07-10 21:37
@CyranMS ,

I found out that the CPU max-out behavior (resulting in huge delays in the video stream) happens primarily on Intel-based Graphics Cards for 720p and greater resolutions. So, while we work to investigate further, I suggest a workaround:
```
Capture video at 480p if your app is running on Chrome with an Intel-based Graphics Card. Otherwise capture at 720p.
```
You can figure out the graphics card name by using the following code snippet:
```js
/**
 * Get the graphics card information.
 * @returns {string} Graphics card information
 */
function getGraphicsCardInfo() {
  const gl = document.createElement('canvas').getContext('webgl2');
  if (!gl) {
    return {
      error: "no webgl",
    };
  }
  const debugInfo = gl.getExtension('WEBGL_debug_renderer_info');
  return gl.getParameter(debugInfo.UNMASKED_RENDERER_WEBGL);
}
```

**Comment by CyranMS** [comment] 2023-07-20 09:49
Thanks for looking into it @manjeshbhargav! Will there also be a proper fix any time soon?

**Comment by yura-oryshchych** [comment] 2023-07-26 12:06
Hey @anna-vasilko @manjeshbhargav  .
Just wondering if anyone has an idea on when we can expect that fix. Really hoping this gets sorted out soon!
We faced this issue a lot, cpu max-out behavior, delay in video streams
Thanks

**Comment by CyranMS** [comment] 2023-08-16 07:13
@anna-vasilko @manjeshbhargav any updates?

**Comment by juanjovazquez** [comment] 2023-08-18 07:22
This is a huge blocker for us too. Same behavior.

**Comment by swapnonil-b** [comment] 2023-08-23 13:34
Any updates on this? Performance is going to be important as we may have devices with low CPU capability.

**Comment by anna-vasilko** [comment] 2023-08-30 20:45
Hi all, 
Apologies for the delay and the troubles caused by the CPU max-out issue. It was temporarily de-prioritized since the issue appeared to be less widespread than initially thought. Nevetherless please be assured that we are commited to address this, we aim to pick up this work in the next sprint. 
In the interim, I recommend using [the workaround mentioned here](https://github.com/twilio/twilio-video.js/issues/2007#issuecomment-1629764778) to avoid the cpu maxout as the issue is specific to Intel-based graphic cards when video track resolution is 720p or greater.

**Comment by CyranMS** [comment] 2023-09-12 11:56
Thanks for the update @anna-vasilko. Is there a rough estimate of when that will be done? This will help us to determine if we need to implement the workaround or if we wait for the new update.

**Comment by anna-vasilko** [comment] 2023-09-19 00:01
Hey @CyranMS The work is in the current sprint. However it will likely spill over to the next one since the team have to prioritize the newly discovered [iOS17 issues](https://github.com/twilio/twilio-video.js/issues/2023). Conservatively I would say this fix will ship 2-3 weeks from now.

**Comment by dmajor3** [comment] 2023-10-18 02:08
Any update here @anna-vasilko ?

**Comment by BryanA2T** [comment] 2023-11-01 23:13
Any update here @anna-vasilko? This is a crucial blocker for our use case.

**Comment by BryanA2T** [comment] 2023-11-02 00:31
Any update here @manjeshbhargav?

**Comment by swapnonil-b** [comment] 2023-11-07 06:13
Hopefully this is still being worked on? The set of devices is not as limited as we might have thought.

**Comment by ido-journey** [comment] 2023-11-19 17:29
Here just to point out how critical this issue is, we just released the backgrounds feature for clients and already had a big percentage of them experiencing this, we had to disable it for now.

**Comment by alxppp** [comment] 2023-11-22 09:18
An update would be great @anna-vasilko 🙏

**Comment by BryanA2T** [comment] 2023-11-22 09:19
Doubling down on how important this is. We are unable to roll out to certain clients because of this issue.

**Comment by jeffss99** [comment] 2023-11-23 13:40
Any update on this?
It is super critical for us

**Comment by dmajor3** [comment] 2023-11-29 16:55
Any update on this?  Also can critical for us.

**Comment by manjeshbhargav** [comment] 2023-12-08 00:26
Hi devs,

There is a new RC available with a fix for this issue: `npm install twilio/twilio-video-processors.js#2.1.0-rc2`. Please try it out and let us know if it helps. I will expedite the publishing of the production version `2.1.0` based on your feedback and our QA process.

**Comment by manjeshbhargav** [comment] 2023-12-12 17:50
`v2.1.0` is now available. Closing the issue.

**Closed by manjeshbhargav** 2023-12-12 17:50 UTC
