### ISSUE TITLE
Firefox room remote participant no audio or video streams

### ISSUE THREAD

**Issue by mattapperson** [twilio/twilio-video.js#52] opened 2017-02-13 22:14 UTC
No errors are displayed and attachments are there for the participants media object but streams show nothing and no video is displayed... all the while the same code and room when loaded with chrome works just fine... any ideas? Or is this a bug?

**Comment by markandrus** [comment] 2017-02-14 22:21
Hi @mattapperson,

That's very strange. I just tested the latest beta (beta4) with the current stable Firefox (51), and things are working fine both Firefox to Firefox and Firefox to Chrome. Here's a screenshot I just took from a test app we use during development:

![image](https://cloud.githubusercontent.com/assets/359154/22952102/81234d90-f2c0-11e6-8b6d-ad27ce20f38a.png)

I've also taken a look at one of our dashboards that continuously tests twilio-video.js releases against new stable, beta, and canary releases of browsers. No issues there: 

![screen shot 2017-02-14 at 2 11 21 pm](https://cloud.githubusercontent.com/assets/359154/22952149/b34d91ae-f2c0-11e6-9e29-1c1f9863cb05.png)

Can you share some logs from your application or describe a little bit more about how you are using twilio-video.js? For example, are you using it with a framework? Doing anything quirky with the MediaStreams? etc.

Best,
Mark

**Comment by mattapperson** [comment] 2017-02-15 02:35
@markandrus I am using it inside a React app, nothing special is being done with MediaStreams really... the other participant in the room is a hosted inside an electron app. and camera and mic are both added using addCamera and addMicrophone so nothing special there. Again Chrome has no issue here, just Firefox. 

On chrome when the electron app connects to the room and room.on('participantConnected' is called, the participant has audio and video tracks. When I inspect on Firefox there are no tracks and that participant never fires the trackAdded event for me...

I am using Firefox 51.0.1 on MacOS 10.12.3. Also tested on windows 7... I forget the Firefox version used there but assume the latest stable.

**Comment by mattapperson** [comment] 2017-02-15 02:36
Tomorrow ill grab the debug logs if you like?

**Comment by ZuSe** [comment] 2017-02-15 14:03
I can confirm this behavior.
Tested with Firefox 53 (Developer Edition) on Ubuntu against Android with Video beta6

**Comment by mattapperson** [comment] 2017-02-15 14:08
@zuse are you also using react on the web side?

**Comment by geoffreyabdallah** [comment] 2017-02-17 16:31
@mattapperson I can also confirm I'm getting this issue. Working fine in Chrome and Firefox separately, however any Firefox -> Chrome connection will prevent a connection (only adds a blank element to both browsers.)

Warnings in firefox console I get (firefox -> firefox) before connecting to a chrome user:

```
navigator.mozGetUserMedia has been replaced by navigator.mediaDevices.getUserMedia  twilio.min.js:79:394
RTCPeerConnection.getLocalStreams/getRemoteStreams are deprecated. Use RTCPeerConnection.getSenders/getReceivers instead.
onaddstream is deprecated! Use peerConnection.ontrack instead.  twilio.min.js:71
```

And warning I get once a Chrome user connects
`ICE failed, see about:webrtc for more details  (unknown)`

Using:
twilio-video v1.0.0-beta4
Firefox v51.0.1 (64-bit)
Chrome Version 56.0.2924.87 (64-bit)
React on the web side.

**Comment by mattapperson** [comment] 2017-02-17 18:06
@markandrus clearly I'm not the only one with an issue here

**Comment by ZuSe** [comment] 2017-02-17 18:20
@mattapperson No, we are using Angular2

**Comment by markandrus** [comment] 2017-02-17 18:42
@geoffreyabdallah thanks for the details. The warnings are annoying—we'll update the Firefox APIs soon. The ICE error is interesting, and would certainly explain the "blank element" you mention. Could you please share logs? The library should fetch STUN and TURN servers for you before attempting a call (unless you override the `iceServers` property). Also, a Room SID would be useful so that we can check in on the server-side.

@mattapperson do you mind sharing full logs from both participants as well? If you'd like to share them privately, feel free to email me at mroberts at twilio dot com. A Room SID would also be useful?

I'll try to reproduce myself.

**Comment by geoffreyabdallah** [comment] 2017-02-17 19:08
@markandrus sent to your email, thanks for the response! And to clarify, Chrome is receiving and mounting the <video /> component with source properly, but no video is being displayed. Firefox is only mounting a blank element. I'll keep investigating this on my end, let me know if there's anything I can do to further assist.

**Comment by markandrus** [comment] 2017-02-17 19:48
OK, I can now reproduce this issue. I only see it when I try a video-only call. Still investigating.

**Comment by mattapperson** [comment] 2017-02-17 19:50
@markandrus on my end, the Firefox side is sharing just audio (muted) and vide false. the chrome/electron side is sharing video and audio

**Comment by markandrus** [comment] 2017-02-21 15:53
Fixing this issue is our #1 priority for this week. I believe it stems from an interop issue between Chrome and Firefox. In the meantime, a workaround is to share both video _and_ audio (although muted) and to ignore the AudioTrack in your application. It's not ideal, but it should work until we have a proper fix.

**Comment by markandrus** [comment] 2017-02-22 01:03
@mattapperson thanks for clarifying your use case. There are at least two issues at play here:

1. The issue affecting you and @abhishekgahlot appears to be the same (see #49). Chrome and Firefox are currently using different SDP formats. We have a backend server that translates between the two formats. Currently, the translation is failing for your use case, leading to the media error. We are currently testing the fix for this in our dev environment. Once ready, we will deploy it to production and the issue should be resolved without any code changes necessary on your part.
2. @geoffreyabdallah your issue is slightly more complicated, and I am considering opening a separate issue for it. It stems from Chrome bug [6280](https://bugs.chromium.org/p/webrtc/issues/detail?id=6280). This is another translation issue we can workaround server-side; however, we need to think through the implications as Chrome and Firefox continue to improve their WebRTC support.

Like #49, I'll keep this issue open until we deploy the fix.

Best,
Mark

**Comment by geoffreyabdallah** [comment] 2017-02-22 01:43
Thanks for the update and thanks for the assistance! Glad I could complicate things 😄

**Comment by markandrus** [comment] 2017-03-07 15:57
The issue in #49 has been resolved at the server-side. @mattapperson do you mind retesting with your particular use case (or including logs) to see if you were indeed encountering the same error?

A fix for @geoffreyabdallah is coming next.

Best,
Mark

**Comment by ZuSe** [comment] 2017-03-14 18:55
@markandrus 

we get the same error when using custom ice servers (e.g. stun.1und1.de or stun.rockenstein.de)and be behind a NAT (that does not require relay connection)  in Chrome. For Firefox everything works. I think chrome has some real issues on this.

**Comment by MilllerTime** [comment] 2017-04-06 18:58
Interestingly, I'm experiencing the reverse of this issue with beta5 on Chrome 57. Firefox works just fine, but Chrome isn't showing any remote tracks when inspecting `room.participants`. Remote participant's `tracks` property is just an empty Map.

This may be connected to #77

**Comment by geoffreyabdallah** [comment] 2017-05-02 21:04
@markandrus Just to add a bit to this - I'm doing some more testing right now (using v1.0.0), but seems that the preferred way of avoiding the firefox/chrome interop issue (adding a local audio stream/then disabling) may be an untenable solution in our case, since we are also dealing simultaneously with twilio-audio in a room (essentially bridging conferences in audio/video). In test, going that route, I've noticed that it then prevents twilio-audio from connecting to the conference. I'll keep testing and make sure I'm not just messing up something simple on my end as well though.

**Comment by markandrus** [comment] 2017-05-02 21:17
Hi @geoffreyabdallah,

Thanks for the info. I think maybe we should continue the discussion on a separate issue, perhaps we should track two issues:

1. An issue for tracking the Firefox/Chrome interop issue, and
2. An issue describing where the suggested workaround fails.

I can open the first item, but as you continue your discovery, could you perhaps capture it in an issue for item 2? Also, by twilio-audio, do you mean the twilio.js (aka Twilio Client) library? A failure here might indicate more general issues if both libraries are used together, and would be surprising.

Thanks,
Mark

**Comment by Shivang44** [comment] 2017-07-25 19:35
Hi,

I'd like to report that I am still having similar (if not the exact same) issue as of July 25th. Chrome to chrome works fine, chrome to firefox works fine, but in firefox <-> chrome I cannot see the video. If I set both video: true and audio: true when joining firefox to chrome does work, but this doesn't quite fit my use case scenario as in my room there is a presenter (which provides video tracks to twilio) and a viewer (which has video and audio set to false).

I created a stackoverflow post, but I can also post any logs/code/anything you require from me, just let me know. Thanks.

https://stackoverflow.com/questions/45250532/twilio-video-javascript-library-doesnt-work-firefox-chrome

**Comment by markandrus** [comment] 2017-07-25 19:53
@Shivang44 does this sounds like your issue? [Common Issues: VideoTrack shared by Firefox appears black](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md#videotrack-shared-by-firefox-appears-black)? If you share only video in a P2P Room between a Firefox and non-Firefox Participant, you will hit the [bundle issue](https://bugs.chromium.org/p/webrtc/issues/detail?id=6280) described there.

**Comment by Shivang44** [comment] 2017-07-27 01:56
@markandrus Thanks for linking that. Looks like that was the problem after all. After I enabled audio on the person sharing video, firefox -> chrome video works now! I have two questions/concerns:

1. Is there any way to create an local audio track and not have Firefox ask for audio permissions? Maybe somehow create a "dummy" audio track since I disable the audio track anyway? It's shady for me to ask for audio permission from the user when I'm not using the user's audio.

2. About 50% of the time Firefox <-> Firefox does not work when viewed on the **same** computer (p2p room opened in two different tabs). I get the ICE error again ("add a stun server, check about:webrtc for more info"). It works 100% of the time when conferencing with another computer, so this is not a big concern for me, but I thought I would mention it. I can provide logs if you want.

Please let me know if there is anything I can do about my first question. Thanks!

**Comment by markandrus** [comment] 2017-07-27 02:56
@Shivang44 

> After I enabled audio on the person sharing video, firefox -> chrome video works now!

Nice! 👍 

> 1. Is there any way to create an local audio track and not have Firefox ask for audio permissions? Maybe somehow create a "dummy" audio track since I disable the audio track anyway? It's shady for me to ask for audio permission from the user when I'm not using the user's audio.

I'm embarrassed to say that I don't know why we didn't think of this before! 🤦‍♂️ Yes, using the [Web Audio APIs](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API), there _is_ a way to create a "dummy" MediaStreamTrack:

```js
var audioContext = typeof AudioContext !== 'undefined'
  ? new AudioContext()
  : new webkitAudioContext()
var mediaStreamDestinationNode = audioContext.createMediaStreamDestination()
var mediaStream = mediaStreamDestinationNode.stream
var mediaStreamTrack = mediaStream.getAudioTracks()[0]
```

You should be able to pass this into the `tracks` Array when `connect`ing. If you're using the `audio`/`video` properties as shorthand today, you may need to grab your LocalVideoTrack manually instead. For example,

```js
var localAudioTrack = new Twilio.Video.LocalAudioTrack(mediaStreamTrack)
createLocalVideoTrack().then(function(localVideoTrack) {
  return Twilio.Video.connect(token, {
    tracks: [localAudioTrack, localVideoTrack]
  })
})
```

Some caveats here:

1. The "dummy" `localAudioTrack` will show up on the remote end, so you'll want to ignore it.
2. Maybe wrap the Web Audio API calls in a `try`/`catch`—there is typically a limit on the number of AudioContexts you can construct.

Also, I haven't actually tried this out yet—I just have a hunch it should work. If it does, we'll work on landing this fix internally in the next release so that you don't have to.

> 2. About 50% of the time Firefox <-> Firefox does not work when viewed on the same computer (p2p room opened in two different tabs). I get the ICE error again ("add a stun server, check about:webrtc for more info"). It works 100% of the time when conferencing with another computer, so this is not a big concern for me, but I thought I would mention it. I can provide logs if you want.

This is very interesting. Would you mind opening a separate issue with logs?

Thanks,
Mark

**Comment by Shivang44** [comment] 2017-07-27 04:06
@markandrus Perfect! Your code work without any modifications. Firefox -> Chrome without audio works now, without requesting audio permissions. I really appreciate your quick responses on everything. I'll get to posting the #2 issue with logs soon.

**Comment by markandrus** [comment] 2018-01-11 23:02
This was fixed in twilio-video.js@1.6.1. Neither `getUserMedia` nor the dummy AudioTrack workaround should be required in application-land. The library takes care of it.

**Closed by markandrus** 2018-01-11 23:02 UTC
Labels: Chrome, Firefox, bug, bug filed
