### ISSUE TITLE
Using 2.7. Switching cameras on iOS is working but not working on Android

### ISSUE THREAD

**Issue by steeleauto** [twilio/twilio-video.js#1126] opened 2020-08-05 10:12 UTC
Hi,
I'm trying to toggle back and forth between front and back camera. Works great on iOS but nothing happening on android. Any idea what I'm doing wrong?

Triggering it with a button in jquery:
`<button type="button" id="flip" data-id="environment" class="btn bg-white btn-float rounded-round"><i class="mi-switch-camera"></i></button>`

$(document).on("click", "#flip", function (e) {
    e.preventDefault();
    var id = $(this).data('id');

    if( id == "environment"  )
    {
        $('#flip').data('id','user');
        cameraTrack.restart({ facingMode: 'environment' });

    } else {

        $('#flip').data('id','environment');
        cameraTrack.restart({ facingMode: 'user' });

    }
});

also tried:

$(document).on("click", "#flip", function (e) {
            e.preventDefault();
            var id = $(this).data('id');

            if( id == "environment"  )
            {
                $('#flip').data('id','user');
                const localVideoTrack = Array.from(room.localParticipant.videoTracks.values())[0].track;
                return localVideoTrack.restart({ facingMode: 'environment' });

            } else {

                $('#flip').data('id','environment');
                const localVideoTrack = Array.from(room.localParticipant.videoTracks.values())[0].track;
                return localVideoTrack.restart({ facingMode: 'user' });

            }
        });

Both work on iOS but not Android

**Comment by PikaJoyce** [comment] 2020-08-10 20:28
Hi @steeleauto,

Thank you for reporting this issue. On first look, I don't see any glaring issues. 

Will you be able to log what `id` is on Android vs iPhone and share it with me? Also, which Android device as well as OS are you running? 

I am curious to see if the reason it is not switching in Android because the conditionals may or may not being hit. 

Best,
Joyce

**Comment by steeleauto** [comment] 2020-08-10 22:36
Hi,
If I could PM you I have a 'live' test version running.
that possible?

**Comment by steeleauto** [comment] 2020-08-10 22:55
I'm using iPhone 10x on 13.6
Android is Samsung J7 on Android 8.0
not sure what you mean by ID's?

**Comment by PikaJoyce** [comment] 2020-08-10 22:58
Hey @steeleauto,

I don't think that is possible here. Just a `console.log(id)` right after `var id = $(this).data('id');` should be sufficient for now.

However, if you think it'd be helpful, I can reach out to you to share that with me over email if you can share that here. 

Thanks,
Joyce

**Comment by steeleauto** [comment] 2020-08-10 23:38
Hi, the id on either device is 'environment' and then 'user' should you click to flip the camera again.

**Comment by PikaJoyce** [comment] 2020-08-11 01:28
Hi there,

I will be investigating this. Can I also get what browser you are running this on your android device as well? 

Thanks for letting me know! 
Joyce

**Comment by steeleauto** [comment] 2020-08-11 07:17
I’m using latest google chrome on android and latest Firefox on android
Safari on iOS


======================
Todd Thompson
Marketing & Development
Steele Auto Group
8 Basinview Drive
Dartmouth, NS, B3B 1G4
P: 902.454.3060
C: 902.802.0904
E: tthompson@steeleauto.com

On Aug 10, 2020, at 10:28 PM, Joyce Ma <notifications@github.com> wrote:

﻿

Hi there,

I will be investigating this. Can I also get what browser you are running this on your android device as well?

Thanks for letting me know!
Joyce

**Comment by manjeshbhargav** [comment] 2020-08-11 19:43
Hi @steeleauto ,

In your code, it seems like you are not updating the `data-id` attribute after switching between facing modes. So, after the first time, it will never switch facing modes. Can you try updating the `data-id` attribute after each switch and let me know if that works?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by steeleauto** [comment] 2020-08-12 16:19
Hi, thanks for your note.
I'm certain the id is changing unless I'm really missing something. 

The button is:
<button type="button" id="flip" name="flip" data-id="user" ><i class="mi-switch-camera"></i></button>

I'm changing the ID value using "$('#flip').data('id','user') or $('#flip').data('id','environment)"
I inserted alerts to check the value and it is as expected, alternating between user and environment.

I click the 'flip button',
it gets the data-id
checks the conditional logic (first time its 'user' as I have that hard coded)
switches cameras


 $(document).on("click", "#flip", function (e) {
            e.preventDefault();
            var id = $(this).data('id');

            if( id == "environment"  )
            {

                $('#flip').data('id','user');
                const localVideoTrack = Array.from(room.localParticipant.videoTracks.values())[0].track;
                localVideoTrack.restart({ facingMode: 'environment' });
                alert('id is now: ' + id); 

            } else {

                $('#flip').data('id','environment');
                const localVideoTrack = Array.from(room.localParticipant.videoTracks.values())[0].track;
                localVideoTrack.restart({ facingMode: 'user' });
                alert('id is now: ' + id);

            }
        });


On iOS it is switching cameras like it should.
I'd be happy to send a link to your email if possible to see for yourself.

**Comment by PikaJoyce** [comment] 2020-08-12 18:16
Hi @steeleauto,

After doing some investigation. I am unable to reproduce this behavior on an Android 10/Chrome84 device, but able to reproduce on a Surface tablet. 

Would it be possible for you to run this snippet within the `if( id == "environment"  )` block:
`  navigator.mediaDevices.getUserMedia({ video: { deviceId: 'ID_OF_REAR_CAMERA' } }).then(stream => {
    const track = stream.getTracks()[0];
    console.log(track.getCapabilities().facingMode);
  });`
and let me know what the log is on your mobile device?

For me, I get `[]` back on the Surface, which may be the issue here.

Thanks,
Joyce

**Comment by steeleauto** [comment] 2020-08-12 18:29
I'm getting:
track.getCapabilities is not a function

`$(document).on("click", "#flip", function (e) {
            e.preventDefault();
            var id = $(this).data('id');

            if( id == "environment"  )
            {

            navigator.mediaDevices.getUserMedia({ video: { deviceId: 'ID_OF_REAR_CAMERA' } }).then(stream => {
            const track = stream.getTracks()[0];
            console.log(track.getCapabilities().facingMode);
            });


            } else {

                $('#flip').data('id','environment');
                const localVideoTrack = Array.from(room.localParticipant.videoTracks.values())[0].track;
                localVideoTrack.restart({ facingMode: 'environment' });

            }
        });`

**Comment by PikaJoyce** [comment] 2020-08-12 18:37
Hi there,

Apologies, please try this:

```
  navigator.mediaDevices.getUserMedia({ video: { deviceId: 'environment' } }).then(stream => {
     const track = stream.getVideoTracks()[0];
     console.log(track.getCapabilities().facingMode);
 });
```

Thanks,
Joyce

**Comment by steeleauto** [comment] 2020-08-12 18:43
same error:
Uncaught (in promise) TypeError: track.getCapabilities is not a function

`if( id == "environment"  )
            {

            navigator.mediaDevices.getUserMedia({ video: { deviceId: 'environment' } }).then(stream => {
     const track = stream.getVideoTracks()[0];
     console.log(track.getCapabilities().facingMode);
 });




            } else {

                $('#flip').data('id','environment');
                const localVideoTrack = Array.from(room.localParticipant.videoTracks.values())[0].track;
                localVideoTrack.restart({ facingMode: 'environment' });

            }`

**Comment by steeleauto** [comment] 2020-08-12 18:45
sorry I used a desktop and got that error.
So at the moment, I'm getting on samsung 'user'

**Comment by steeleauto** [comment] 2020-08-12 18:46
I just put the console log into an alert instead so I could see it on the phone.

**Comment by PikaJoyce** [comment] 2020-08-12 18:56
It's alright!

Could you now move that snippet in the `else` block as well, and test on the mobile device? 

Thanks,
Joyce

**Comment by steeleauto** [comment] 2020-08-12 19:23
it says 'user' either way.

**Comment by steeleauto** [comment] 2020-08-12 19:30
I've been able to switch cameras using Phil Nash tutorial and this test page:
https://philnash.github.io/mediadevices-camera-selection/
Seems it switches by device id instead of user/environment
Is that an option somehow?
Not sure how to pass a device ID in etc. but it does switch cameras using the device ID

**Comment by PikaJoyce** [comment] 2020-08-12 19:37
Hi @steeleauto 

Thanks, that's a neat test app! It's odd that it doesn't seem to work with `facingMode`. However, here's an example of how you can apply it with `deviceId` in this [quickstart example](https://github.com/twilio/video-quickstart-js/blob/b2da4f000e519ab1acb280dff09d0325fcc8a9cd/examples/mediadevices/src/index.js#L141). 

You can find the helper function `applyInputDeviceSelection` [here](https://github.com/twilio/video-quickstart-js/blob/b2da4f000e519ab1acb280dff09d0325fcc8a9cd/examples/mediadevices/src/helpers.js#L37) for reference.

Please let me know if this works.

Thanks,
Joyce

**Closed** 2020-11-23 18:21 UTC
