### ISSUE TITLE
e.play is not a function(…)

### ISSUE THREAD

**Issue by GarPit** [twilio/twilio-video.js#10] opened 2016-05-17 12:05 UTC
Hello. I've got this when tried to initialize local Camera Preview:

```
twilio-conversations.min.js:89 Uncaught (in promise) TypeError: e.play is not a function(…)


this.get('client').listen().then(() => {
  console.log('Connected to Twilio!');
  if (this.get('conversation') === null) {
    this.displayCameraPreview();
    ...
displayCameraPreview() {
  var previewMedia = new Twilio.Conversations.LocalMedia();
  previewMedia.addCamera().then(function(cameraTrack) {
    // attach to a <video> element
    cameraTrack.attach('.chat .left-part .video .preview-video');
  }, function(error) {
    console.error('Unable to get access to the local camera.' + error.message);
  } );
},
```

**Comment by GarPit** [comment] 2016-05-17 12:45
Changing to this helped me:
`Twilio.Conversations.LocalMedia.getLocalMedia().then...`

**Comment by markandrus** [comment] 2016-05-20 19:39
@GarPit thanks for the report. What platform are you testing on? Any chance this is Chrome for Android?

**Comment by GarPit** [comment] 2016-05-23 14:26
Google Chrome, desktop

**Comment by markandrus** [comment] 2017-02-01 17:46
Hi @GarPit,

I am still unable to reproduce this issue. One thing to note, when you call `Track#attach`, the element selected by the query selector, e.g. in your case `.chat .left-part .video .preview-video`, must be an HTMLAudioElement (&lt;audio&gt;) or HTMLVideoElement (&lt;video&gt;); otherwise, the `play` method used internally will not exist. I suppose we should put some checks around that.

I will close this ticket for now. Please re-open if you continue experiencing issues.

Thank you,
Mark

**Closed by markandrus** 2017-02-01 17:46 UTC
Labels: needs more information
