### ISSUE TITLE
WebSocket connection to 'wss://sdkgw.us1.twilio.com/v1/VideoEvents' failed

### ISSUE THREAD

**Issue by sarahtully** [twilio/twilio-video.js#1552] opened 2021-08-17 18:31 UTC
**Expected behavior:**

Connect, Publish local media, and Disconnect from rooms without warnings or errors.

**Actual behavior:**

Recently, we consistently see the warning and error below. The error occurs frequently within 10-20 seconds of connecting to a room and it is thrown multiple times as if it's polling. The warning happens when we disconnect. We can get it to happen almost every time if you disconnect within the first 10 seconds which is odd because we are fully connected because we can see our remote participants and vice versa. 

When observing the network tab, I can see multiple VideoEvents requests with the only obvious difference being the Sec-WebSocket-Key changing each time. 

**WARNING**
index.js:115 WebSocket connection to 'wss://sdkgw.us1.twilio.com/v1/VideoEvents' failed: WebSocket is closed before the connection is established.
InsightsPublisher.disconnect	@	index.js:115
value	@	twilioconnectiontransport.js:130
TwilioConnectionTransport.disconnect	@	twilioconnectiontransport.js:318
RoomV2._disconnect	@	room.js:219
RoomSignaling.disconnect	@	room.js:214
Room.disconnect	@	room.js:145
(anonymous)	@	conversation.service.ts:649
step	@	tslib.js:143
(anonymous)	@	tslib.js:124
(anonymous)	@	tslib.js:117
ZoneAwarePromise	@	zone.js:1335
__awaiter	@	tslib.js:113
push.htJB.ConversationService.disconnect	@	conversation.service.ts:642
(anonymous)	@	conversation.service.ts:432
step	@	tslib.js:143
(anonymous)	@	tslib.js:124
(anonymous)	@	tslib.js:117
ZoneAwarePromise	@	zone.js:1335
__awaiter	@	tslib.js:113
push.htJB.ConversationService.updateConversation	@	conversation.service.ts:395
(anonymous)	@	conversation.service.ts:152
step	@	tslib.js:143
(anonymous)	@	tslib.js:124
(anonymous)	@	tslib.js:117
ZoneAwarePromise	@	zone.js:1335
__awaiter	@	tslib.js:113
(anonymous)	@	conversation.service.ts:132
__tryOrUnsub	@	Subscriber.ts:265
next	@	Subscriber.ts:207
_next	@	Subscriber.ts:139

**ERROR:**
index.js:170 WebSocket connection to 'wss://sdkgw.us1.twilio.com/v1/VideoEvents' failed: 
connect	@	index.js:170
reconnect	@	index.js:259
maybeReconnect	@	index.js:72
emit	@	events.js:153
(anonymous)	@	index.js:178
ZoneDelegate.invokeTask	@	zone.js:429
onInvokeTask	@	core.js:27492
ZoneDelegate.invokeTask	@	zone.js:428
Zone.runTask	@	zone.js:200
ZoneTask.invokeTask	@	zone.js:511
invokeTask	@	zone.js:1651
globalZoneAwareCallback	@	zone.js:1677
InsightsPublisher.disconnect	@	index.js:115
value	@	twilioconnectiontransport.js:130
TwilioConnectionTransport.disconnect	@	twilioconnectiontransport.js:318
RoomV2._disconnect	@	room.js:219
RoomSignaling.disconnect	@	room.js:214
Room.disconnect	@	room.js:145
(anonymous)	@	conversation.service.ts:649
step	@	tslib.js:143
(anonymous)	@	tslib.js:124
(anonymous)	@	tslib.js:117
ZoneAwarePromise	@	zone.js:1335
__awaiter	@	tslib.js:113
push.htJB.ConversationService.disconnect	@	conversation.service.ts:642
(anonymous)	@	conversation.service.ts:432
step	@	tslib.js:143
(anonymous)	@	tslib.js:124
(anonymous)	@	tslib.js:117
ZoneAwarePromise	@	zone.js:1335
Show 86 more frames

**Twilio Info Log**
2021-08-17T18:20:02.781Z info [connect #2] Connecting to a Room
log.js:162 2021-08-17T18:20:02.782Z info [connect #2] Getting LocalTracks
log.js:162 2021-08-17T18:20:02.783Z info [createLocalTracks #4] Adding user-provided LocalTracks
log.js:162 2021-08-17T18:20:02.786Z info [LocalParticipant #2] Created a new Participant
log.js:162 2021-08-17T18:20:02.788Z info [connect #2] event {elapsedTime: 8, group: "signaling", level: "info", name: "early", timestamp: 1629224402788}
log.js:162 2021-08-17T18:20:02.790Z info [connect #2] event {elapsedTime: 10, group: "room", level: "info", name: "connect", timestamp: 1629224402790, …}
log.js:162 2021-08-17T18:20:02.978Z info [connect #2] event {elapsedTime: 198, group: "signaling", level: "info", name: "connecting", timestamp: 1629224402978}
log.js:162 2021-08-17T18:20:03.018Z info [connect #2] event {elapsedTime: 238, group: "signaling", level: "info", name: "open", timestamp: 1629224403018}
log.js:162 2021-08-17T18:20:03.208Z info [LocalParticipant #2: PAf3ac484a720eb103e834b189dcaafaba] reconnected
log.js:162 2021-08-17T18:20:03.209Z info [MediaSignaling #5:active_speaker] setting up msp transport for id: 5c5401a2-c053-4816-a082-93fb63335694
log.js:162 2021-08-17T18:20:03.210Z info [MediaSignaling #6:network_quality] setting up msp transport for id: b9cb23ea-8273-43b1-b3c6-edf41bfa8d81
log.js:162 2021-08-17T18:20:03.210Z info [MediaSignaling #8:track_priority] setting up msp transport for id: f732e776-5f2c-4e85-894e-e984331277ac
log.js:162 2021-08-17T18:20:03.210Z info [MediaSignaling #9:track_switch_off] setting up msp transport for id: b79fefe9-411b-412b-a298-cd97c9b9f290
log.js:162 2021-08-17T18:20:03.211Z info [MediaSignaling #7:render_hints] setting up msp transport for id: e60474ca-1d56-4dff-94b1-ab3458b08dea
log.js:162 2021-08-17T18:20:03.213Z info [Room #2: RMe42fc82b86b17bbc170768f7606e1f93] Created a new Room: 1-193-dev
log.js:162 2021-08-17T18:20:03.214Z info [connect #2] Connected to Room: [Room #2: RMe42fc82b86b17bbc170768f7606e1f93]
log.js:162 2021-08-17T18:20:03.214Z info [connect #2] Room name: 1-193-dev
log.js:162 2021-08-17T18:20:03.223Z info [LocalParticipant #2: PAf3ac484a720eb103e834b189dcaafaba] Added a new VideoTrack: 24b99176-a2c0-4b85-8f61-e8da4891143c
log.js:162 2021-08-17T18:20:03.225Z info [LocalParticipant #2: PAf3ac484a720eb103e834b189dcaafaba] Added a new LocalVideoTrack: 24b99176-a2c0-4b85-8f61-e8da4891143c
log.js:162 2021-08-17T18:20:03.409Z info [LocalParticipant #2: PAf3ac484a720eb103e834b189dcaafaba] Added a new VideoTrackPublication: MT954fe7132ecede153eb3b2414e61caa1
log.js:162 2021-08-17T18:20:13.221Z info [connect #2] event {elapsedTime: 10441, group: "quality", level: "info", name: "stats-report", timestamp: 1629224413221, …}
log.js:162 2021-08-17T18:20:13.222Z info [connect #2] event {elapsedTime: 10442, group: "quality", level: "info", name: "active-ice-candidate-pair", timestamp: 1629224413222, …}
**index.js:170 WebSocket connection to 'wss://sdkgw.us1.twilio.com/v1/VideoEvents' failed:** 
log.js:162 2021-08-17T18:20:17.610Z info [LocalParticipant #2: PAf3ac484a720eb103e834b189dcaafaba] Removed a VideoTrack: 24b99176-a2c0-4b85-8f61-e8da4891143c
log.js:162 2021-08-17T18:20:17.612Z info [LocalParticipant #2: PAf3ac484a720eb103e834b189dcaafaba] Removed a LocalVideoTrack: 24b99176-a2c0-4b85-8f61-e8da4891143c
log.js:162 2021-08-17T18:20:17.613Z info [LocalParticipant #2: PAf3ac484a720eb103e834b189dcaafaba] Removed a VideoTrackPublication: MT954fe7132ecede153eb3b2414e61caa1
log.js:162 2021-08-17T18:20:17.640Z info [Room #2: RMe42fc82b86b17bbc170768f7606e1f93] Disconnecting
log.js:162 2021-08-17T18:20:17.642Z info [LocalParticipant #2: PAf3ac484a720eb103e834b189dcaafaba] LocalParticipant disconnected. Stopping 0 automatically-acquired LocalTracks
log.js:162 2021-08-17T18:20:17.643Z info [Room #2: RMe42fc82b86b17bbc170768f7606e1f93] Transitioned to state: disconnected
log.js:162 2021-08-17T18:20:17.650Z info [connect #2] Disconnected from Room: [Room #2: RMe42fc82b86b17bbc170768f7606e1f93]
log.js:162 2021-08-17T18:20:17.653Z info [connect #2] event {elapsedTime: 14873, group: "signaling", level: "info", name: "closed", timestamp: 1629224417653, …}
**index.js:115 WebSocket connection to 'wss://sdkgw.us1.twilio.com/v1/VideoEvents' failed: WebSocket is closed before the connection is established.**
log.js:162 2021-08-17T18:20:17.711Z info [MediaSignaling #5:active_speaker] Tearing down
log.js:162 2021-08-17T18:20:17.715Z info [MediaSignaling #9:track_switch_off] Tearing down
log.js:162 2021-08-17T18:20:17.718Z info [MediaSignaling #6:network_quality] Tearing down
log.js:162 2021-08-17T18:20:17.721Z info [MediaSignaling #7:render_hints] Tearing down
log.js:162 2021-08-17T18:20:17.724Z info [MediaSignaling #8:track_priority] Tearing down

**Software versions:**

 - [X] Browser(s): Chrome Version 92.0.4515.159 (Official Build) (x86_64)
 - [X] Operating System: macOS Big Sur
 - [X] twilio-video.js: 2.16.0
 - [X] Third-party libraries (e.g., Angular, React, etc.): Angular

**Comment by sarahtully** [comment] 2021-08-18 21:00
I can confirm that I am able to replicate using the sample React app: https://github.com/twilio/twilio-video-app-react

**Comment by manjeshbhargav** [comment] 2021-08-23 18:10
Hi @sarahtully ,

Sorry for the delayed response. I will get one of the back-end engineers to look into this.

**Comment by ykhodosh** [comment] 2021-08-23 19:57
@sarahtully last week we've deployed a new version of the insights backend, which introduced the regression that caused high latency and the errors on the client side similar to those you reported. That version was rolled back already and the errors should no longer be happening. However, let me also assure you that video rooms functionality will not be affected even when a client is unable to connect to the above mentioned URL.

We'll be closing this issue since there is nothing actionable on our side anymore. Feel free to reopen it if you have further questions or concerns.

**Closed** 2021-08-23 19:59 UTC

**Comment by tiptronic85** [comment] 2021-10-05 22:25
Hello,
why did you call /v1/VideoEvents inside the https://sdk.twilio.com/js/video/releases/2.17.1/twilio-video.min.js

is this correct ?
