### ISSUE TITLE
Freshly added video track (screen capture) does not behaves properly on getStats on remote participant

### ISSUE THREAD

**Issue by mpszczolinski** [twilio/twilio-video.js#127] opened 2017-06-25 07:50 UTC
I've added correct screen capture screen to localParticipant tracks.
It shows properly on remote participant, but when using "room.getStats().then(...)" the properties of this track are all null (like dimensions, packetsSend etc.)
I've verified and it works correctly when track are added before joining room. So the problem is only when track is added dynamically, like this:

1. userA joins room with audio+video
2. userB joins room with audio+video
3. room.getStats() works 100% ok
4. userA adds track with screen capture stream (on Chrome 58.0.3029.110 (64-bit))
4. the room.getStats() has data for new added stream, but it's properties are null/undefined

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.

```
getUserScreen(['window', 'screen', 'tab'], 'id-to-chrome-extension')
  .then(function(stream) {
    const screenLocalTrack = new Twilio.Video.LocalVideoTrack(stream.getVideoTracks()[0]);
    var addedTrack = vm.twilio.room.localParticipant.addTrack(screenLocalTrack); // vm.twilio.room is a reference to twilio's 'room'
});
```

**Expected behavior:**
When I add video track dynamically (after joining room) - the getStats().then(...) has correct statistic data of all (also freshly added) tracks.

**Actual behavior:**
the freshly added video track has statistic data properties set to null/undefined

**Software versions:**

 - [x] Browser(s): Chrome 58.0.3029.110 (64-bit)
 - [x] Operating System: Win10 Home, 64 bit
 - [x] twilio-video.js: 1.0.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): Angular 1.5.0

**Comment by manjeshbhargav** [comment] 2017-06-26 18:47
@mpszczolinski ,

Thanks for bringing this to our attention. We will try and reproduce this on our end, and get back to you with an update shortly.

Thanks,

Manjesh Malavalli
Video JavaScript SDK Team

**Comment by markandrus** [comment] 2017-08-23 00:03
Hi @mpszczolinski,

We think this is fixed as of twilio-video.js@1.2.2. Can you please re-test and let us know if it fixed your issue?

Thanks,
Mark

**Comment by mpszczolinski** [comment] 2017-08-24 07:56
issue fixed, but it caused another issue.

When I stop screensharing, so a video stream (from laptop camera) is being re-added to tracks, its stats are frozen (no longer updates).

So what I am doing:
1. tracks contains video(camera) track
2. screensharing started
3. remove video(camera) track [using localParticipant.removeTrack() ]
4. add screensharing track [using localParticipant.addTrack(screenLocalTrack) ]
-- stats works fine --
5. stop screensharing, removed screensharing track [using localParticipant.removeTrack(event.currentTarget) ]
6. re-add video(camera) track [using localParticipant.addTracks(removedVideoTracks)]
-- at this point video(camera) stats are frozen

**Comment by mpszczolinski** [comment] 2017-08-24 08:13
ok, so I fixed it by creating new localVideoTrack [ Video.createLocalVideoTrack() ] and adding it to tracks (rather the readding previously removed track).

GENERAL CONCLUSION:
My general conclusion is that when track is removed from tracks, but kept in memory, and then reattached to tracks - it behaves differently than new created tracks. There may be some bug/issue in code.

best regards Guys! :)

**Comment by markandrus** [comment] 2018-07-12 00:41
Just an update here: in general this should be much-improved in twilio-video.js 2.x due to some changes around how we manage the underlying MediaStreamTracks.

**Closed** 2020-01-21 00:44 UTC
Labels: stats
