### ISSUE TITLE
testPreflight not availbale on CDN js?

### ISSUE THREAD

**Issue by kelvin2200** [twilio/twilio-video.js#1331] opened 2020-12-31 17:16 UTC
As stated in 2.8.0-beta.1 (September 28, 2020), the twilio-video lib includes a testPreflight API, which I can confirm it exists when importing the API from twilio-video, but it doesn't exist when using the CDN version.

Will the testPreflight API be included in the CDN script? or do we have to bundle twilio-video along with our code?

**Comment by charliesantos** [comment] 2020-12-31 18:06
Hi @kelvin2200 , thanks for reaching out!

How are you accessing the testPreflight API after loading the Video SDK from CDN?

I can confirm if you load the SDK from CDN like the following, you should be able to access the testPreflight API from the global Twilio.Video object.

In my HTML page:
```html
<script src="https://media.twiliocdn.com/sdk/js/video/releases/2.8.0-beta.3/twilio-video.js"></script>
```

In my JS file:
```js
const Video = Twilio.Video;
const preflightTest = Video.testPreflight(publisherToken, subscriberToken, options);
```

**Comment by kelvin2200** [comment] 2020-12-31 18:35
this is how i load the SDK
```typescript
const loadScript = (src: string, done: () => void) => {
    const js = document.createElement("script");

    js.src = src;
    js.onload = function () {
        done();
    };
    document.head.appendChild(js);
};

const sdkScriptUrl = "//media.twiliocdn.com/sdk/js/video/releases/2.10.0/twilio-video.min.js";

//... some other code

loadScript(sdkScriptUrl, () => {
    sdkLoaded = true;
    API = ((window as any).Twilio || {}).Video as typeof Video;
});

```
And... I use the types from @types/twilio-video
As far as your example goes, do i have to expressly use 2.8.0-beta.3? ...or the non-minified url? or both?
...because the way I'm using it right now, there is NO testPreflight API under Twilio.Video
these are the methods exposed by the Video API that is loaded

```log
Video:
    LocalAudioTrack: ƒ LocalAudioTrack(mediaStreamTrack,options)
    LocalDataTrack: ƒ LocalDataTrack(options)
    LocalVideoTrack: ƒ LocalVideoTrack(mediaStreamTrack,options)
    Logger: Logger {name: undefined, levels: {…}, methodFactory: ƒ, getLevel: ƒ, setLevel: ƒ, …}
    connect: ƒ connect(token,options)
    createLocalAudioTrack: ƒ createLocalAudioTrack(options)
    createLocalTracks: ƒ createLocalTracks(options)
    createLocalVideoTrack: ƒ createLocalVideoTrack(options)
    isSupported: true
    version: "2.10.0"

**Comment by charliesantos** [comment] 2020-12-31 19:10
Hi @kelvin2200 , access to testPreflight API is only available in 2.8.0-beta.3 at the moment. We are working on getting it out of beta and include it in the latest version soon. Please watch out for updates.

As for your question, you can use either minified or non-minified. But for now, you might need to load 2.8.0-beta.3 to use the API.

**Comment by kelvin2200** [comment] 2020-12-31 19:28
@charliesantos thank you for the clarification.
Will be watching out for updates

**Comment by manjeshbhargav** [comment] 2021-01-20 19:09
Hi @kelvin2200 ,

I'll close this issue since we have answered your question. We will announce the inclusion of the testPreflight API when its ready.

**Closed by manjeshbhargav** 2021-01-20 19:09 UTC
Labels: question
