### ISSUE TITLE
Safari Users on Big Sur have Audio Distortion

### ISSUE THREAD

**Issue by jjp390** [twilio/twilio-video.js#1337] opened 2020-12-10 20:52 UTC
**Describe the bug**
Audio on Safari 14.0.1 on Big Sur has massive amounts of distortion for the audio the Safari user is receiving. It is so bad that you can't understand what other people on the call are saying.

**To Reproduce**
1. Open a video call with one user in a stable browser (I.e. Chrome)
2. Have another user join in Safari on Big Sur.
3. User on Chrome starts talking, their audio will be heavily distorted for the user on Safari. Sometimes this seems to normalize after a variable amount of time.

**Expected behavior**
Audio should sound normal

**Environment (please complete the following information):**
 - OS: macOS 11.0.1
 - Browser: Safari 14.0.1
 - App Version: 0.2.1
 - SDK Version: 2.9.0
 - Node.js version: 14

**Additional context**
We've tested this on multiple different Macbooks (2013 MBP, multiple 2020 MBP's). We've tested it both on the demo app and our own version that we are running of Twilio Video.

**Comment by aaalaniz** [comment] 2021-01-07 16:54
Duplicate of #1304

**Closed by aaalaniz** 2021-01-07 16:54 UTC

**Comment by jjp390** [comment] 2021-01-07 17:10
@aaalaniz I'm not sure that this should be closed as a duplicate. The issue that you linked this to is for Chrome. This issue is specifically Safari related in our application and testing. Chrome seems to reliably function ok for us, but Safari is reliably broken.

**Comment by anna-vasilko** [comment] 2021-01-08 00:05
It seems to be a duplicate of [#1296](https://github.com/twilio/twilio-video.js/issues/1296) which is a webkit bug fixed in the latest MacOS and iOS 14.3.
