### ISSUE TITLE
Consistent, repeatable bitrate issues

### ISSUE THREAD

**Issue by multiplegeorges** [twilio/twilio-video.js#947] opened 2020-04-11 20:24 UTC
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

Just launch the Quickstart app and go to the Bandwidth Constraints demo.

**Expected behavior:**

Consistent bandwidth usage, or more intelligent bandwidth adjustments.

**Actual behavior:**

Aggressive, very periodic drops in bitrate causing consistent stuttering in videos.

**Software versions:**

 - [x] Browser(s): Chrome 80, FF 74, Safari 13.
 - [x] Operating System: macOS 10.15
 - [x] twilio-video.js: 2.3.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): None - just the Quickstart app.

I've attached some screenshots showing the behaviour I'm seeing on desktop browsers. 
The video quality is good until framerate drops dramatically, bitrate drops as well, and there is significant stuttering. This is reproducible across browsers, computers, different networks, and in my own app and the Quickstart App.

![android-chrome](https://user-images.githubusercontent.com/59541/79054167-b66ae080-7c10-11ea-9139-5fe78f69c08b.png)
![safari](https://user-images.githubusercontent.com/59541/79054171-b9fe6780-7c10-11ea-9c93-cdb2c398628f.png)
![ff](https://user-images.githubusercontent.com/59541/79054172-b9fe6780-7c10-11ea-8f10-a580a98baae6.png)
<img width="544" alt="chrome" src="https://user-images.githubusercontent.com/59541/79054173-ba96fe00-7c10-11ea-824f-13841c56ec8d.png">

That's why I've concluded that there might be something going on with how twilio-video or the SFU is throttling bandwidth.

The ONLY exception I've found is Chrome on Android on a Pixel 3. I've also attached that screenshot for an example of expected behaviour.

Thanks a lot!

**Comment by PikaJoyce** [comment] 2020-04-13 22:42
Hey there @multiplegeorges!

Thanks for reporting this issue. I've been trying to reproduce this issue today with no luck. 
Can you provide some more details, such as room sids if the issue is still occurring for you?

Thank you,
Joyce

**Comment by multiplegeorges** [comment] 2020-04-15 03:28
Hi @PikaJoyce, thanks for your response. I realize that this one is pretty hard to debug.

I will try to reproduce it again on my local machine. 

Are there any specific debugging steps you'd like me to take to help shed more light on possible causes?

**Comment by PikaJoyce** [comment] 2020-04-15 21:33
Hi @multiplegeorges 

Unfortunately, this may take a deeper look at more than just some logs in order to debug. If you can reproduce this issue, could you include more room sids so that we have more information? 

Thanks, 
Joyce

**Comment by multiplegeorges** [comment] 2020-04-17 01:31
@PikaJoyce I saw similar behaviour in RM000e60847e7bef0fd4dc675f82b74fa8 

Thanks for your help!

**Comment by multiplegeorges** [comment] 2020-04-18 00:17
Another from just now: RMcc71fdc0f8262511cee6a64ef0df96ca
<img width="331" alt="Screen Shot 2020-04-17 at 8 17 00 PM" src="https://user-images.githubusercontent.com/59541/79623103-6f855b00-80e8-11ea-8d90-ff7bc9a0c8c7.png">

**Comment by PikaJoyce** [comment] 2020-04-18 00:22
@multiplegeorges I was also wondering if you could verify the capture settings? These intervals look like key frame sending which could be too big for the bandwidth. This may explain the spikes.

Thank you,
Joyce

**Comment by multiplegeorges** [comment] 2020-04-18 16:29
I'm using unmodified code from the BandwithContrainsts example and I'm getting there to be no bitrate limit. The connect call in question is here:

https://github.com/twilio/video-quickstart-js/blob/master/examples/bandwidthconstraints/src/helpers.js#L14

I added some logging to confirm that there were no constraints being passed in. Here's the output from the JS console in Firefox. `attachedTrack` is the var I set the video track to:

```
12:24:13.717 >> attachedTrack
12:24:13.749 {…}
    _MediaStream: function ()
    _attachments: Set [ video#videopreview ]
    _dummyEl: <video autoplay="">
    _events: Object { dimensionsChanged: reemitTrackEvents(), message: reemitTrackEvents(), started: reemitTrackEvents()
    }
    _instanceId: 3
    _isEnabled: true
    _isStarted: 
    _isSwitchedOff: false
    _log: Object { … }
    _maxListeners: undefined
    _priority: null
    _setPriority: function setPriority(newPriority)​
    dimensions: Object { width: 640, height: 480 }
    isEnabled: 
    isStarted: 
    isSwitchedOff: 
    kind: "video"
    mediaStreamTrack: MediaStreamTrack { kind: "video", id: "{2190e3a8-3dfa-694f-86c3-7ea8b4c76bde}", label: "remote video", … }
    name: "{d3ab6652-313e-0440-9df8-2e127f000da0}"
    priority: 
    sid: "MT0cd25c01dc5258d7e9a42656d91388c7"
    <get _isStarted()>: function get()​
    <set _isStarted()>: function set(_isStarted)​
    <get isEnabled()>: function get()​
    <get isStarted()>: function get()​
    <get isSwitchedOff()>: function get()​
    <get priority()>: function get()​
    <prototype>: Object { … }

12:24:21.328 >> attachedTrack.mediaStreamTrack
12:24:21.358 MediaStreamTrack { kind: "video", id: "{2190e3a8-3dfa-694f-86c3-7ea8b4c76bde}", label: "remote video", enabled: true, muted: false, onmute: null, onunmute: null, readyState: "live", onended: null }

12:24:26.000 >> attachedTrack.mediaStreamTrack.getConstraints()
12:24:26.030 {}
    <prototype>: Object { … }
```

Hope this helps!

**Comment by PikaJoyce** [comment] 2020-04-22 04:33
Hey @multiplegeorges,

Looking at some data, it seems like there were some packets that were lost on the way to the media server. However, it doesn't seem like they saw anything unusual from their end. I'm wondering if there was perhaps some network disruptions? 

I'm still unable to reproduce this and I'm thinking that it may be a network issue. It seems like it could also be bursts of wifi interference from another device / network, or simply another device on the same network monopolizing available bandwidth. 

Thanks!
Joyce

**Comment by multiplegeorges** [comment] 2020-04-22 14:24
@PikaJoyce Ok, thanks a lot for all the investigation. I'll swap out some network equipment (routers, APs) and see what I can come up with.

Cheers!

**Comment by PikaJoyce** [comment] 2020-04-22 19:34
@multiplegeorges No worries. Since there doesn't seem to be any current actionable items for this. I'll be closing this issue for now. Please open again if you're still experiencing problems. Thank you!

**Closed by PikaJoyce** 2020-04-22 19:34 UTC

**Comment by ceaglest** [comment] 2020-04-22 19:51
Hey @multiplegeorges,

> Another from just now: RMcc71fdc0f8262511cee6a64ef0df96ca
> Every minute, on the minute...

I wanted to chime in because I looked at the metrics for this Room with @PikaJoyce. Each minute there was a small amount of packets lost on the sender/receiver side, but more importantly a large increase in round trip time (up to 500 ms) for the perspective of the receiver. If the devices were on the same network then there may be some queueing due to congestion on the local link that is periodic.

Best,
Chris

**Comment by multiplegeorges** [comment] 2020-04-27 19:57
@ceaglest I replaced my consumer grade router with some Ubiquity hardware and the issue is gone.

Thanks again for all the time you guys put in to investigating this!
