### ISSUE TITLE
Vue 3 / Vite simple app fails to load twilio-video package

### ISSUE THREAD

**Issue by rlightner** [twilio/twilio-video.js#1680] opened 2022-01-21 04:55 UTC
- [X] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [X] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [X] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii) or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**
npm init vue@3 twilio-video-test
npm install twilio twilio-video --save

App.Vue
```js
<script setup> 
import { onMounted } from 'vue';
import { isSupported } from 'twilio-video';

onMounted(() => {
 console.log('isSupported: ', isSupported);
});
</script>
```

**Expected behavior:**
console output:
```
isSupported: true
```
**Actual behavior:**
```
Uncaught TypeError: Class extends value undefined is not a constructor or null
```
![image](https://user-images.githubusercontent.com/354640/150467797-121a3507-ffb2-447f-9567-177e0edc6d87.png)

if I install events package `npm install events --save`
then the error changes to 
```
Uncaught ReferenceError: global is not defined
```
![image](https://user-images.githubusercontent.com/354640/150468425-7376ce9e-6397-4bcb-b064-0b7e079c9674.png)

**Comment by sannonthachai** [comment] 2022-01-26 07:53
try this

https://medium.com/@ftaioli/using-node-js-builtin-modules-with-vite-6194737c2cd2

**Comment by rlightner** [comment] 2022-01-26 16:31
This worked!  Thanks!

**Comment by rlightner** [comment] 2022-01-26 16:39
Well spoke too soon. 

Works great for local dev, but once I build, I get `Uncaught TypeError: Class extends value [object Object] is not a constructor or null`

**Comment by charliesantos** [comment] 2022-01-27 17:16
Hi @rlightner , thank you for submitting. Can you please delete the `isSupported` `import` statement then log the user agent right after your last `import`, and `onMounted`?
```ts
import { onMounted } from 'vue';
console.log(navigator.userAgent);

onMounted(() => {
 console.log(navigator.userAgent);
});
```

**Comment by charliesantos** [comment] 2022-01-27 17:30
@rlightner `isSupported` depends on userAgent detection. Logging the userAgent after the import statements, and onMounted will provide us information why you are having the error.

**Comment by rlightner** [comment] 2022-01-27 17:33
Gotcha, so you're wanting the output posted here. That wasn't apparent. Will do.

**Comment by rlightner** [comment] 2022-01-27 17:36
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36`

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36`

**Comment by charliesantos** [comment] 2022-01-27 17:54
Thanks for the info @rlightner . It seems the issue is related to your build process. I'm not familiar with `Vue`, but per your log, it seems the twilio-video sdk is being loaded as a node module on client side. Ideally, the build process will take care of browserifying (or similar) the node modules but it seems it is not happening in your setup.

**Comment by rlightner** [comment] 2022-01-27 23:21
@charliesantos Seems this is a known issue already: https://github.com/twilio/twilio-video.js/issues/1347

**Comment by zynth17** [comment] 2022-02-22 02:49
any update on this?

**Comment by charliesantos** [comment] 2022-02-22 17:14
@zynth17 to speed up the process on resolving this issue, can you please provide a basic vite/vue project that will allow us to pull down and reproduce the issue locally?

**Comment by zynth17** [comment] 2022-02-23 02:13
> @zynth17 to speed up the process on resolving this issue, can you please provide a basic vite/vue project that will allow us to pull down and reproduce the issue locally?

here is a simple repro 
https://github.com/zynth17/twilio-video-bug-vite

**Comment by charliesantos** [comment] 2022-02-23 13:50
Thanks @zynth17 . This has been prioritized and it will be picked up soon. We'll keep you posted.

**Comment by zynth17** [comment] 2022-02-23 17:11
> Thanks @zynth17 . This has been prioritized and it will be picked up soon. We'll keep you posted.

thankyou!

**Comment by marjorg** [comment] 2022-03-07 10:49
@charliesantos Sorry to bother you, but I'm wondering if you have an ETA on this? Is it days, weeks or months away? Currently working on a project that will use Twilio video chat heavily and this is currently a blocker for that feature. We can wait a bit, but might have to consider other build tools if a fix is not close :)

**Comment by marjorg** [comment] 2022-03-18 08:58
@charliesantos Thanks! Haven't been able to try it yet because of other priorities, but I'll try to make time next week!

**Comment by PikaJoyce** [comment] 2022-03-22 22:45
Hi Folks!

Happy to announce that the latest release [2.21.1](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md#2211-march-22-2022) fixes this issue. Please give it a spin and let us know if you're still seeing any issues! I will now be closing this issue.

Thank you for all of your patience,
Joyce

**Closed by PikaJoyce** 2022-03-22 22:45 UTC

**Comment by marjorg** [comment] 2022-03-27 14:51
@PikaJoyce Thanks, build works now! Still getting an error with `utils`, but can work around it by adding the snippet below to `vite.config.ts`. Would be great if we didn't need any polyfills though.

```js
...
resolve: {
	alias: {
		util: 'rollup-plugin-node-polyfills/polyfills/util'
	}
}
...
```

<img width="635" alt="image" src="https://user-images.githubusercontent.com/5442549/160286489-30d7a448-0cd9-42e4-9869-e3095c59e3a7.png">

**Comment by yenntkaopiz** [comment] 2022-04-04 09:06
@PikaJoyce 
i tried to use twilio vesion 2.21.1 ,but when i run `vite dev` its seen be ok, but when i run `vite build` for deploy production it throw error like above comment 
https://github.com/twilio/twilio-video.js/issues/1680#issuecomment-1023477306
**Error in console:**
`vendor.0d2ea866.js:8 TypeError: Class extends value [object Object] is not a constructor or null`
**Code vue component:**
```
<template>
  <h1>Twilio Serverless Video Calling</h1>
  <form>
    Name: <input type="text" id="username" />
    <button id="join_leave">Join call</button>
  </form>
  <p id="count"></p>
  <div id="container" class="container">
    <div id="local" class="participant">
      <div></div>
      <div>Me</div>
    </div>
  </div>
</template>
<script>
import Twilio from "twilio-video"
export default {
  name: "VideoCallComponent",
  mounted() {
    if (Twilio.isSupported) {
      const addLocalVideo = async () => {
        const track = await Twilio.createLocalVideoTrack()
        const video = document.getElementById("local").firstElementChild
        video.appendChild(track.attach())
      }
      addLocalVideo()
    } else {
      alert("not Support")
    }
  },
}
</script>
```
