### ISSUE TITLE
unpublishTrack  issue   (remoteVideoTrackStats) on mobile Safari

### ISSUE THREAD

**Issue by x3mlestat** [twilio/twilio-video.js#327] opened 2018-06-17 14:28 UTC
Hi, 

I have a very strange issue...
I have a room with 2 connections - 

1 - iPhone (safari)
2 - desktop (chrome) 

I `createLocalTracks` and connecting to the room with a front camera.
I switch the camera on iPhone, so I re-create local stream with different video parameters
`Twilio.Video.createLocalTracks`
and get new `localVideoTrack`
my next:
`videoRoom.localParticipant.unpublishTrack(oldTrack);`
`videoRoom.localParticipant.publishTrack(newTrack);`

Result: 

1. load to the room with front camera - ok 
2. switch to environment camera, 
```
videoRoom.localParticipant.unPublishTrack(oldTrack) 
videoRoom.localParticipant.publishTrack(newTrack)
```
- ok.
3. switch to front camera, 
```
videoRoom.localParticipant.unPublishTrack(oldTrack) 
videoRoom.localParticipant.publishTrack(newTrack)
```
- ok.
4. switch to environment camera, 
```
videoRoom.localParticipant.unPublishTrack(oldTrack) 
videoRoom.localParticipant.publishTrack(newTrack)
```
- FAIL.

and my remote participant on the desktop  - broken (I see blank screen), because
I get broken participant from Twilio room (some parametrs - null , see please screenshot) 
<img width="444" alt="broken" src="https://user-images.githubusercontent.com/2789235/41508753-2deba592-7252-11e8-960c-255789093697.png">

I checked room and seems to its ok  - 2 tracks (see please screenshot )

<img width="518" alt="localroom" src="https://user-images.githubusercontent.com/2789235/41508780-9063556c-7252-11e8-9389-a03bb04f8a39.png">

but I check status and see that I have a lot of not removed tracks  - 4 video and 4 audio tracks
`videoRoom.getStats()`
 (see please screenshot )

<img width="1247" alt="roomstatus" src="https://user-images.githubusercontent.com/2789235/41508788-a486077e-7252-11e8-8822-bd1ce6321d18.png">

I believe my issue related to a lot of not unpublished tracks in the room
Please tell me how I can remove it...?
note: issue present only on mobile Safari, on android chrome everything is ok.

**Comment by manjeshbhargav** [comment] 2018-06-18 18:20
Hi @x3mlestat ,

Thank you for reaching out to us with your issue. I have a couple of questions:

* In your description of the issue, you said:
  >
  switch to environment camera,
  videoRoom.localParticipant.unPublishTrack(oldTrack) 
  videoRoom.localParticipant.publishTrack(newTrack)
  FAIL.
  and my remote participant on the desktop - broken (I see blank screen)
  >
  Do you mean the <video> element that was rendering the video Track was blank?

* It would help us greatly if you can re-run the same scenario with logging enabled on both devices:
  ```
  const room = await Twilio.Video.connect('room-name', { logLevel: 'debug' });
  ```

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by michaek** [comment] 2018-08-07 15:55
@manjeshbhargav I'm also able to reproduce this with iOS Safari to Desktop Chrome: switching cameras on iOS Safari will eventually lead to the remote side not seeing the newly published track. It doesn't seem to always be a set number of camera changes - sometimes as few as 2, sometimes as many as 5.

I've added the debug log output to both devices. Is there anything specific you're looking for? I'm seeing that when the video track is no longer displayed on the Desktop Chrome, the "Attempting to attach to element" log line is no longer followed by the "Added a new VideoTrack" line, but nothing else is jumping out at me (to be fair, I might just be missing the needle in the debug haystack).

I hope this helps with troubleshooting on your end - I'll keep investigating to see what I can uncover as well.

**Comment by manjeshbhargav** [comment] 2018-08-07 19:40
Hi @michaek @x3mlestat ,

Thanks for your responses. As of 1.13.0, we worked around this [Safari WebRTC bug](https://bugs.webkit.org/show_bug.cgi?id=174327) by not calling `RTCPeerConnection.removeTrack` when the SDK user unpublishes a LocalTrack. What you're seeing is a consequence of this workaround.

In 2.x, we will be cloning MediaStreamTracks associated with LocalTracks before publishing to the Room. So this way, we will actually call `RTCPeerConnection.removeTrack` when the SDK user unpublishes the LocalTrack.

We have a release candidate that is being tested right now. However, I would love it if you can try it out and let me know if it solves your problem. Here's how you can try it out:

### NPM
```
npm install twilio-video@twilio/twilio-video.js#2.0.0-rc1
```

### <script>
```
<script src="https://stage.twiliocdn.com/sdk/js/video/releases/2.0.0-rc1/twilio-video.js"></script>
```

NOTE: In 2.x, we will be removing support for deprecated APIs and events. Please refer to the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/2.0.0-rc1/CHANGELOG.md) to figure out how to migrate to the 2.x APIs and events.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by michaek** [comment] 2018-08-09 13:31
@manjeshbhargav From my testing, upgrading to the 2.0 RC does resolve this issue. Fortunately, I was already minding the deprecation notices, so there wasn't much I needed to change for the 2.x API. I'm still hunting down the causes for some unexpected regressions, but if they need any attention from maintainers I'll open separate issues. Thanks for your help!

**Comment by manjeshbhargav** [comment] 2018-08-09 18:02
@michaek ,

Cool! Glad to be of help.

@x3mlestat ,

I'll close this issue for now. Please feel free to re-open if needed.

**Closed by manjeshbhargav** 2018-08-09 18:02 UTC
Labels: Safari, needs more information
