### ISSUE TITLE
With Chrome 76, no longer subscribing to remote data track

### ISSUE THREAD

**Issue by patricktemple** [twilio/twilio-video.js#714] opened 2019-08-13 01:49 UTC
When the latest Chrome update to 76 was pushed out, I stopped getting subscriptions to the remote data track. Normally we have four tracks coming in from the remote participant: two video, one audio, and one data. After the Chrome update, the remote participant still has four publications, but the data track has `isSubscribed: false` and `track: null`.

Here's the code snippet that sets it up, though it's very Rx-style so may not be immediately clear if you're not familiar (I can rewrite in standard form if you like):
```
const participant$ = fromEvent<RemoteParticipant>(
  room,
  'participantConnected',
).pipe(
  startWith(...room.participants.values()),
  filterByIdentity(p => p.identity),
  share(),
);

const tracks$ = participant$.pipe(
  switchMap(p => {
    const initialTracks = Array.from(p.tracks.values())
      .map(trackPublication => trackPublication.track)
      .filter(track => track != null);
    return fromEvent<Video.RemoteTrack[]>(p, 'trackSubscribed').pipe(
      // The first event argument is track, second is publication
      map(eventArgs => eventArgs[0]),
      startWith(...initialTracks),
    );
  }),
);
```

Basically, we take the initial values for `room.participants`, add all the following values that come in due to `participantConnected`, which should handle all cases of remote participant timing. Then we do the same for the tracks of that participant. I believe this is equivalent to the standard setup code for initialize the tracks.

I find that, for the data track, its publication has `track=null` and gets filtered out. Just in case there's some edge case of not listening to all the events, I tried setting a timeout to print out the `room.participant` 10 seconds after startup, and its data track was still not subscribed.

I went into Chromium and did a binary search of their snapshots to find when this got broken. On this snapshot here, it works:
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/660003/

On this next one, it fails:
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/660038/

Here are all the commits that happened between those two:
https://github.com/chromium/chromium/commits/master?before=5f8825b173dc9cb7ba79ca7f5685aa32312e1d50+35

There's one that mentions webrtc and is immediately suspect to me:
https://github.com/chromium/chromium/commit/3763026369de637d76a5421e06b1d9231f982699

I also reverted our `twilio-video-js` to `1.14.2` and believe I still saw the issue on that (though I didn't test as thoroughly just now). So it's probably not just an issue with the beta release.

It does still sometimes work with the new Chrome, maybe 20% of the time. But before it was working every time.

**Software versions:**

 - [ ] Browser(s): 76.0.3809.100
 - [ ] Operating System: Mac OS 10.14.5
 - [ ] twilio-video.js: 2.0.0-beta12
 - [ ] Third-party libraries (e.g., Angular, React, etc.):

**Comment by makarandp0** [comment] 2019-08-13 15:45
Thank you @patricktemple for writing in about this issue. I will investigate further and get back to you soon.

**Comment by makarandp0** [comment] 2019-08-13 18:36
Hey @patricktemple, I tried a this few times on Chrome 76, but have not been able to repro the issue. If you have a fairly consistent repro, can you capture the room sid when the issue repros, and share it with us. 

Also any other details like 
- type of room you are using (p2p or group?)
- the client/browser version that the peer is using?
could  also help narrow down the repro steps.

Thanks,
Makarand
JSDK Team

**Comment by patricktemple** [comment] 2019-08-13 19:07
Sure. Here was recent room: `RM3ef8fcb8a1cf4862a28eb4156ff23aab`

We're using p2p, and the other side is the iOS SDK 2.2.0

I'll try to repro it in a simplified setting outside our project and let you know how that goes.

**Comment by patricktemple** [comment] 2019-08-13 19:28
When I hack this up to pair against a web app instead of our iOS app, I can no longer repro the issue. So maybe something is different about how that iOS app is setting up the tracks.

**Comment by patricktemple** [comment] 2019-08-13 20:14
I tried pairing against `video-quickstart-ios` and its `DataTrackExample`. What I found:
* Building that example as-is, there's no problem. The data track shows up fine.
* But if I drop the iOS version down from `2.10` to `2.2.0`, then it shows up again. On web, we no longer subscribe to the data track. Then against that iOS version, I tried using the older Chromium, and once again it worked. So it seems this is the same issue.

Is iOS version `2.2` doing something that non-spec-compliant that got deprecated and removed in the newest Chrome?

**Comment by ceaglest** [comment] 2019-08-13 20:17
Hi @patricktemple,

Just a comment while @makarandp0 continues to investigate on our side.

Twilio Video iOS [2.2.2](https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-2x#222-july-25-2018), has [known issues](https://github.com/twilio/twilio-video-ios/issues/35) with DataTrack interoperability in Peer-to-Peer Rooms and Firefox 63+. Can you please try updating to a more recent version (like [2.10.0](https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-2x#2100-april-24-2019)) which doesn't have known DataTrack interop issues? 

I believe the changes made to how a DataChannel is negotiated in Chrome 76 (which were already implemented in Firefox) make it incompatible with the older iOS SDKs.

Regards,
Chris

**Comment by patricktemple** [comment] 2019-08-13 20:30
Thanks, that does sound like it. Even when I upgrade just to 2.3 (which says it fixes that issue), things work again. We'll try doing the upgrade now.

**Comment by ceaglest** [comment] 2019-08-13 23:05
Hi @patricktemple,

Yes, upgrading to 2.3.0 or newer will resolve the issue (we encourage 2.10.0 because it has improvements and bug fixes over 2.3.0 and no breaking API changes).

After reproducing with @makarandp0, we noticed that the following scenario causes issues in a Peer-to-Peer Room:

1. iOS Participant (Alice) connects first publishing a DataTrack. Chrome 76 Participant (Bob) connects second publishing a DataTrack. 

Result: Bob does not subscribe to Alice's DataTrack, but Audio/Video works as expected.

2. Chrome 76 Participant (Bob) connects first publishing a DataTrack. iOS Participant (Alice) connects second publishing a DataTrack. 

Result: Alice and Bob subscribe to all Tracks as expected.

I will be updating our known issue and Changelog to mention the iOS < 2.2.2 and Chrome >= 76 incompatibility.

Best,
Chris

**Comment by makarandp0** [comment] 2019-08-13 23:36
Hey @patricktemple, Thank you again for noticing and reporting this issue. @ceaglest and I were able to get repro of it locally as well and also verified that it does not repro anymore with iOS 2.10.0 

We will update our common_issues mentioning this incompatibility. (JSDK-2474) I am closing this ticket now.  

Thanks!
Makarand

**Comment by patricktemple** [comment] 2019-08-21 20:46
I did the upgrade and everything works fine again. Thanks for all your help.

**Comment by makarandp0** [comment] 2019-08-21 20:59
Thanks for the update @patricktemple

**Closed by makarandp0** 2019-08-21 20:59 UTC
