### ISSUE TITLE
Group Room Communicate with one To One Using Twilio Video JavaScript 

### ISSUE THREAD

**Issue by DipenIprospl** [twilio/twilio-video.js#781] opened 2019-10-19 03:46 UTC
user-1 is connected to room. same room user-2 is connected as participant and user-3 is connected as participant. but not see user-1 video screen in user-2 screen and user-3 screen. 
user-2 and user-3 only show self view. user-1 can video screen view user-2 and user-3. user-1 can click user-2 start button that time user-1 communicate with user-2 but user-3 not see user-1 video screen.

**Comment by makarandp0** [comment] 2019-10-21 22:33
Hello @DipenIprospl, Thank you for writing about this issue. Could you please fill in issue-template, and also share any code samples to isolate and demonstrate the issue. That would make it easier for us to see your usage of the SDK, and provide any guidance. 

Thanks,
Makarand
JSDK Team.

**Comment by DipenIprospl** [comment] 2019-10-22 03:14
Hi @makarandp0, I am using programmable video with JavaScript and refer code in this url (https://www.twilio.com/docs/video/javascript-v1-getting-started).  And Scenario in example.

This Is Scenario.
1. User-1 Connected room.
2. User-2 Connected Same room But User-2 screen Not See User-1 Video Screen frame or User-1 Video Screen black frame Allowed.
3. User-3 Connected same room But User-3 Screen Not See User-1 Video Screen frame And User-2 Video Screen frame or User-1 Video Screen frame And User-2 Video Screen black frame Allowed.
4. User-1 Can See User-2 Local Video Screen frame And User-3 Local Video Screen frame.
5. User-1 Can Start With Communication Between User-2. User-2 Can See User-1 Audio And Video Screen frame. At That Time User-3 Can Not See User-1 Audio And Video Screen frame or Display black Video Screen frame.
6. User-1 Can Stop With Communication Between User-2 That User-2 Not See User-1 Audio And Video Screen frame or Display black Video Screen frame.

**Comment by makarandp0** [comment] 2019-10-22 19:24
@DipenIprospl, I am sorry, but the issue is not clear to me. Are you wondering if the scenario you mention is possible with Twilio SDK, or are you encountering any issue when implementing the scenario? Any code samples that demonstrate the issue will make it easier to understand. 

Please fill in following template.
============= 


 - [ ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**



```js
// TODO
```

**Expected behavior:**

TODO

**Actual behavior:**



TODO

**Software versions:**

 - [ ] Browser(s):
 - [ ] Operating System:
 - [ ] twilio-video.js:
 - [ ] Third-party libraries (e.g., Angular, React, etc.):

**Comment by DipenIprospl** [comment] 2019-11-11 06:06
@makarandp0 
Sorry i am busy can not replay your question.
 working js file twilio-video.js: 1.14.1.
all code working in single page .aspx file.

if possible participant audio track disable share code.
//Participant is all participant connect with Room. For Ex. User-1 Screen Page Participant User-2, User-3 And User-4.
participant.audioTracks.forEach(function (track) {
        if (track.kind === 'audio') {
                track.mediaStreamTrack.enabled = false;
                track.mediaStreamTrack.muted = true;
        }
// sid is disable Audio track Particular Participant sid. For Ex. User-1 Screen Participant User-3 audio disable using audio track sid It is Possible. If Possible give me code or reference url link.
       if (track.sid == sid) 
       {
               //participant audio track disable.
               track.disable();
         }
});

If it is possible give me code or url reference link.

**Comment by DipenIprospl** [comment] 2019-11-28 09:25
Only Participant Audio and Video Enable And Disable. It is Working.

**Closed** 2020-06-23 20:08 UTC
