### ISSUE TITLE
Race condition when adding tracks in beta5

### ISSUE THREAD

**Issue by randallb** [twilio/twilio-video.js#81] opened 2017-04-13 17:21 UTC
In our application, we join the stream before adding cameras. If you join the stream using the default `getUserMedia` implementation, it works fine on join-in-progress streams. If you manually add the camera, there is a race condition preventing a user from simultaneously adding two tracks at the same time.

I've forked the quickstart so we can speak a common language for this problem.

https://github.com/TwilioDevEd/video-quickstart-node/compare/master...vidpresso:master

In my fork, I added a few buttons below the camera preview to illustrate the issue. If you follow this sequence of events precisely, you'll experience the same problem.

1. Open a browser to localhost:3000 and join a room, perhaps `test`
2. Open another browser to localhost:3000 and join the same room.
3. Preview your camera in the second browser.
4. Click the `add both to room simultaneously` button.
5. Go to the first browser, observe a 2x2 black video, with no audio.

If you go and repeat the same steps, trying out the other various buttons, you'll notice:

- Adding individual tracks as a one-off never fails.
- Adding simultaneous tracks staggering 200ms usually fails.
- Adding simultaneous tracks staggering 250ms sometimes fails, sometimes succeeds, usually with the audio working and the video failing. (in my tests, anyway)
- Adding simultaneous tracks staggering 500ms seems to always succeed.

I'll be working around this by hacking in a delay when adding tracks. This seems like an issue that should be resolved before 1.0 because a lot of users might want users to be able to join streams and add cameras later, without having to stagger the audio / video track adding.

**Comment by randallb** [comment] 2017-04-13 18:27
This is a dupe of #80 which was filed likely while I was figuring this out. :)

**Comment by markandrus** [comment] 2017-04-21 01:23
Hi @randallb,

We identified two issues that contributed to your issue.

1. One of the issues was server-side, where we accidentally filtered answer SDPs that should have been passed through. The fix for this was deployed today around noon. We also landed an integration test to track any regressions in this behavior.

2. The other contributing issue has to do with how Chrome responds to SSRC changes. Since the release of 1.0.0-beta5, it is now more likely that multiple offer SDPs can be "in flight" at a time. In theory this is a good thing: it means new SDPs can be transmitted as soon as Track changes occur, rather than waiting for round after round of negotiation to complete. However, if any Track SSRCs change during this process, Chrome will consider the Track with the previous SSRC to have "ended" and will raise a new Track—with the same ID—distinct from the previous one. We've landed an integration test documenting this behavior (which differs from Firefox), as well as a fix (slated for the next release).

Your issue may have actually overlapped with #72, since there were certain scenarios where the server could drop an answer; however, now that the server-side fix is out, it is _also_ possible that you may be hitting Issue 2 that I describe above. https://github.com/twilio/twilio-video.js/commit/6edf705e46524ae1a79d8c29d501c1eae8e90ea9 contains the proposed fix for Issue 2. It was a little too late to land in 1.0.0-beta6; however, we anticipate releasing it very soon if it makes it through our QE process.

Thanks,
Mark

**Comment by markandrus** [comment] 2017-04-21 23:54
@randallb following up, we've released 1.0.0-beta7 which includes the fix described above (6edf705). Would you please test it out and let us know if it fixes the issue?

Thanks, and have a good weekend.
Mark

**Comment by markandrus** [comment] 2017-04-25 22:40
@randallb,

Since #80 was closed, we will close this issue, too. If you have trouble with this in the 1.0.0 release, feel free to reopen the issue.

Thanks,
Mark

**Closed by markandrus** 2017-04-25 22:40 UTC
Labels: bug
