### ISSUE TITLE
Video flips intermittently on Apple M1 laptop during video call

### ISSUE THREAD

**Issue by datermine** [twilio/twilio-video.js#1338] opened 2021-01-08 21:09 UTC
We've been using the programmatic video sdk without issue for sometime. Recently with the launch of Apple's M1 chips, we noticed that video calls placed between our native clients and a web client (in multiple browsers) resulted in the video flipping (typically on-mouse-move). 

We were able to fix this with a hack where we set the `<video />` element's opacity to .999. (We stumbled upon this by accident.)

Also interesting: If another video application or screen-recording application was taking place, the flipping would not occur.

Here's a video of this in action + my opacity hack: 
https://drive.google.com/file/d/1jegr_eUgIxSRH1Q8IdwPWB5B8jvYNBIT/view?usp=sharing

Any thoughts on what might be causing this or how to actually fix it?

---

 - [X] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [X] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [X] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Software versions:**

 - Browser(s): Chrome, Firefox, Safari
 - Operating System: OSX
 - twilio-video.js: 2.10.0
 - Third-party libraries (e.g., Angular, React, etc.): React

**Comment by manjeshbhargav** [comment] 2021-01-20 18:46
Hi @datermine ,

Thanks for reporting this issue. I was not able to reproduce this issue on my MacBook Air (M1, 2020) with MacOS Big Sur 11.0.1. Did you say this issue was happening on your machine on all browsers or just Chrome? In my view, this is most likely specific to your machine.

I will ask my teammates who have M1 laptops to see if they can reproduce this issue. Can you do the same on your end?

Thanks,

Manjesh

**Comment by manjeshbhargav** [comment] 2021-01-30 00:11
Hi @datermine ,

Nobody on my team was able to reproduce this issue. Were you able to reproduce it on other similar machines? I will close this issue since there is nothing actionable at this point. Please feel free to re-open once you have results from your tests.

**Closed by manjeshbhargav** 2021-01-30 00:11 UTC
Labels: Chrome, Mac
