### ISSUE TITLE
WARN in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Handshake attempt 1 failed

### ISSUE THREAD

**Issue by Kinnari7** [twilio/twilio-video.js#1210] opened 2020-09-30 15:10 UTC
Hello 

When i click on video icon and try to connect to room than getting warning like this :  WARN in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Handshake attempt 1 failed.

Than after immediately getting error like this : 
TwilioError: Signaling connection error

I am using angular version 8.3.0.
Please help me to resolve this issue. it's urgent.

Thank you.
Kinnari

**Comment by makarandp0** [comment] 2020-10-01 19:33
Hello @Kinnari7, Can you add some details about your the repro steps. Any room sids, and client side logs would be very helpful. You can add information to the template below. Also since you mentioned angular please check out known issue and workaround for angular (https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md#angular)

Thanks,
Makarand


 - [ ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**



```js
// TODO
```

**Expected behavior:**

TODO

**Actual behavior:**



TODO

**Software versions:**

 - [ ] Browser(s):
 - [ ] Operating System:
 - [ ] twilio-video.js:
 - [ ] Third-party libraries (e.g., Angular, React, etc.):

**Comment by esojrafael** [comment] 2020-10-01 19:57
Im having the same problems with svelte and vanilla js

**Comment by Kinnari7** [comment] 2020-10-02 05:47
Hii @makarandp0 

I am generating token and room using twilio console.Here i attach all information.

**Client side log**
2020-10-02 05:37:56.935Z | INFO in [createLocalTracks #2]: Adding user-provided LocalTracks
log.js:138 2020-10-02 05:37:56.935Z | DEBUG in [createLocalTracks #2]: LocalTracks: (2) [LocalAudioTrack, LocalVideoTrack]
log.js:138 2020-10-02 05:37:56.937Z | DEBUG in [connect #1]: Creating a new LocalParticipant: LocalParticipantV2 {_events: {…}, _eventsCount: 1, _maxListeners: undefined, …}
log.js:138 2020-10-02 05:37:56.940Z | INFO in [LocalParticipant #1]: Created a new Participant
log.js:138 2020-10-02 05:37:56.942Z | INFO in [LocalParticipant #1]: Added a new LocalAudioTrack: 454a2bae-76fb-4924-8b31-99597a83cd3e
log.js:138 2020-10-02 05:37:56.942Z | DEBUG in [LocalParticipant #1]: LocalAudioTrack: LocalAudioTrack {kind: "audio", name: "454a2bae-76fb-4924-8b31-99597a83cd3e", id: "454a2bae-76fb-4924-8b31-99597a83cd3e", …}
log.js:138 2020-10-02 05:37:56.944Z | INFO in [LocalParticipant #1]: Added a new LocalVideoTrack: 658c3065-4d28-4b16-80b0-5fac473faa5c
log.js:138 2020-10-02 05:37:56.945Z | DEBUG in [LocalParticipant #1]: LocalVideoTrack: LocalVideoTrack {kind: "video", name: "658c3065-4d28-4b16-80b0-5fac473faa5c", dimensions: {…}, …}
log.js:138 2020-10-02 05:37:56.946Z | DEBUG in [connect #1]: Creating a new RoomSignaling
log.js:138 2020-10-02 05:37:56.962Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Created a new WebSocket: WebSocket {__zone_symbol__errorfalse: Array(6), __zone_symbol__openfalse: Array(6), url: "wss://global.vss.twilio.com/signaling", readyState: 0, bufferedAmount: 0, …}
log.js:138 2020-10-02 05:37:57.543Z | DEBUG in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: WebSocket opened: WebSocket {__zone_symbol__errorfalse: Array(7), __zone_symbol__openfalse: Array(8), __zone_symbol__closefalse: Array(1), __zone_symbol__messagefalse: Array(1), url: "wss://global.vss.twilio.com/signaling", …}

020-10-02 05:40:45.898Z | WARN in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Handshake attempt 1 failed
log.js:138 2020-10-02 05:40:50.922Z | WARN in [TwilioConnection #1: wss://global.vss.twilio.com/signaling]: Handshake attempt 2 failed

log.js:138 2020-10-02 05:38:12.560Z | INFO in [connect #1]: Error while connecting to a Room: TwilioError: Signaling connection error
    at SignalingConnectionError.TwilioError (http://localhost:4200/chats-chats-module.js:48273:23)
    at new SignalingConnectionError (http://localhost:4200/chats-chats-module.js:47183:133)
    at disconnect (http://localhost:4200/chats-chats-module.js:38743:112)
    at TwilioConnection.<anonymous> (http://localhost:4200/chats-chats-module.js:38724:9)
    at Object.onceWrapper (http://localhost:4200/vendor.js:167169:5)
    at TwilioConnection.emit (http://localhost:4200/vendor.js:167077:5)
    at TwilioConnection.<anonymous> (http://localhost:4200/chats-chats-module.js:42118:20)
    at TwilioConnection.emit (http://localhost:4200/vendor.js:167082:7)
    at TwilioConnection.transition (http://localhost:4200/chats-chats-module.js:39242:17)
    at TwilioConnection._close (http://localhost:4200/chats-chats-module.js:42183:16)

**Code for connect to room**
 createLocalTracks({
      audio: true,
      video: { width: 640 },
    }).then(localTracks => {
      return connect('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImN0eSI6InR3aWxpby1mcGE7dj0xIn0.eyJqdGkiOiJTSzBhYzVlMDllYzg2YzdmZjBjOTQ3YTE2MzJmZThlODdjLTE1MTc4NjQyMDAiLCJpc3MiOiJTSzBhYzVlMDllYzg2YzdmZjBjOTQ3YTE2MzJmZThlODdjIiwic3ViIjoiQUNmZTA2M2U3YzlkYmY2MDZjODQ1MTNjOWQwMmY5YmZmYSIsImV4cCI6MTUxNzg2NzgwMCwiZ3JhbnRzIjp7ImlkZW50aXR5IjoidGVzdCIsInZpZGVvIjp7InJvb20iOiJ0ZXN0In19fQ.l15uT1eaUqbIFr2JKbm2V7G3QmENV70M1t5qYAu-xYg', {
        name : 'my-new-room',
        tracks: localTracks,
        logLevel : 'debug',
        region : 'gll'
      });
    }).then(room => {
      console.log(`Connected to Room: ${room.name}`);
    });

**Software versions:**

 Browser(s): Google Chrome
 Operating System: windows 10
 twilio-video.js:  2.7.2
 Third-party libraries (e.g., Angular, React, etc.): Angular 8.2.3
 
**Expected Result**
successfully room connection

Please help me to solve my problem ASAP.

Thank you
Kinnari.

**Comment by swarnava** [comment] 2020-10-09 05:58
@Kinnari7 I hope this issue is resolved over Support Ticket #5165417 and this issue can be closed? cc @makarandp0

**Comment by anns-carveniche** [comment] 2020-10-14 05:00
Hi anybody have solution for this issue.iam also facing the same issue for my users several times.
Error Code : 53000
Error Message : Signalling Connection Error

**Comment by manjeshbhargav** [comment] 2020-10-23 02:41
Hi @anns-carveniche ,

Please open a new issue with all the relevant details.

Thanks,

Manjesh

**Closed** 2020-10-23 02:41 UTC
