### ISSUE TITLE
Unpublished tracks leave orphaned _workaroundWebKitBug1208516 listeners

### ISSUE THREAD

**Issue by dehler** [twilio/twilio-video.js#1305] opened 2020-12-04 04:09 UTC
https://github.com/twilio/twilio-video.js/blob/26355050c66a24acdb13a336b84a030488f15a65/lib/media/track/localtrackpublication.js#L94

The underlying track's _workaroundWebKitBug1208516Cleanup is not called when tracks are unpublished. 
Suggested change:

	  if (this.track._workaroundWebKitBug1208516Cleanup) {
	    this.track._workaroundWebKitBug1208516Cleanup();
	    this.track._workaroundWebKitBug1208516Cleanup = null;
	  }

Will also need to consider other areas, such localParticipant.unpublishTrack(s)

**Comment by dehler** [comment] 2020-12-04 04:18
To reproduce the issue seen repeatedly publish and unpublish the same local audio track the the localParticipant

```
var room = .. // initialize a twilio room here
var stream = await navigator.mediaDevices.getUserMedia({'audio':true});


function unpub() {
	room.localParticipant.audioTracks.forEach( function(pub) {
	   pub.unpublish();
	}); 
	console.log(room.localParticipant.audioTracks) ; // Empty Map
}

function pub(fn) {	
	stream.getAudioTracks().forEach( track => {
		let options = { name: 'audio_track'};
		room.localParticipant.publishTrack(track,options).then(p => {
		    try { log(`Published Audio Track: ` + p); } catch (e) {}
		}, error => {
	 	    console.log(error);
		});
	});
}

In your console, publish then unpublish several times using pub & unpub. 
Tab away to another window, twice. Come back and you will see the silence detected for orphaned tracks that were unpublished.
Try pub() again and it will fail to send audio even though the local track is working
```

**Comment by charliesantos** [comment] 2021-01-13 23:26
Duplicate of #1334 . Closing

**Closed by charliesantos** 2021-01-13 23:26 UTC
Labels: duplicate
