### ISSUE TITLE
Needing to add ~500ms delay between remove/add videotrack on beta5 screenshare

### ISSUE THREAD

**Issue by geoffreyabdallah** [twilio/twilio-video.js#72] opened 2017-03-31 03:26 UTC
Since upgrading from beta4 to beta5 we've had to add what feels like a nasty hack to get screensharing registering properly to remote participants. Previously we had:

```javascript
function* switchVideoFeeds(constraints) {
  const localMedia = yield select(path(['video', 'localMedia']))
  localMedia.videoTracks.forEach(setOnendedTo(null))
  yield localMedia.removeCamera()
  yield localMedia.addCamera(constraints)
  return localMedia
}
```

which worked like a charm. After update we switched to:

```javascript
function* switchVideoFeeds(constraints) {
  const newLocalVideoTrack = yield createLocalVideoTrack(constraints)
  const oldLocalVideoTrack = yield select(path(['video', 'localVideoTrack']))
  const localParticipant = yield select(path(['video', 'room', 'localParticipant']))
  yield localParticipant.removeTrack(oldLocalVideoTrack)
  yield localParticipant.addTrack(newLocalVideoTrack)
}
``` 

while this worked fine locally, remote participants would only see a black screen (I should add there are handlers added for beta5 handling trackRemoved/trackAdded on participants that work fine when people join/leave call - only having issue now w/ screenshare.)

Only fix I've found thus far is adding a 500ms delay between the removeTrack/addTrack functions - which does end up syncing properly. I'm wondering if this issue is related to [this comment in beta4](https://github.com/twilio/twilio-video.js/blob/946be7e80e1f7c7972113f99238a4964b281362b/lib/media/localmedia.js#L324)

Using react/redux/redux-sagas in front end.

**Comment by markandrus** [comment] 2017-03-31 05:38
@geoffreyabdallah thanks for the report. One change we made internally during the move from beta4 to beta5 was to re-use the same MediaStream object when publishing over the PeerConnection. We will work to reproduce and see if it is related.

**Comment by markandrus** [comment] 2017-04-21 01:18
Hi @geoffreyabdallah,

We identified two issues that contributed to your issue.

1. One of the issues was server-side, where we accidentally filtered answer SDPs that should have been passed through. The fix for this was deployed today around noon. We also landed [an integration test](https://github.com/twilio/twilio-video.js/blob/6edf705e46524ae1a79d8c29d501c1eae8e90ea9/test/integration/spec/localparticipant.js#L270) to track any regressions in this behavior.

2. The other contributing issue has to do with how Chrome responds to SSRC changes. Since the release of 1.0.0-beta5, it is now more likely that multiple offer SDPs can be "in flight" at a time. In theory this is a good thing: it means new SDPs can be transmitted as soon as Track changes occur, rather than waiting for round after round of negotiation to complete. However, if any Track SSRCs change during this process, Chrome will consider the Track with the previous SSRC to have "ended" and will raise a new Track—with the same ID—distinct from the previous one. We've landed [an integration test](https://code.hq.twilio.com/client/twilio-video.js/blob/6edf705e46524ae1a79d8c29d501c1eae8e90ea9/test/integration/spec/webrtc/rtcpeerconnection.js#L131) documenting this behavior (which differs from Firefox), as well as a fix (slated for the next release).

I don't believe Issue 2 really affected your use case, since you're presumably always creating a new LocalVideoTrack; however, I think it's worth calling out since it's in the proximity of what you are trying to do.

Would you mind please retesting without the delay to see if the recent server deploy fixed your issue? Would you mind also testing out 1.0.0-beta6?

Thanks,
Mark

**Comment by geoffreyabdallah** [comment] 2017-04-21 14:02
@markandrus Thanks for the update! We have an internal demo today of the new twilio-video stuff (so wont make any changes just yet), but after that I'll bump us to beta6 and retest screensharing without the delay. Will keep you updated.

**Comment by markandrus** [comment] 2017-04-21 23:51
@geoffreyabdallah OK, great! Hope it goes well. We've marched ahead to beta7 by the way (delta between beta6 and beta7 is just the bugfix for #80/#81).

**Comment by markandrus** [comment] 2017-05-02 15:51
This should be fixed now. Please reopen the issue if you are still seeing the problem. Thanks!

**Closed by markandrus** 2017-05-02 15:51 UTC
Labels: bug
