### ISSUE TITLE
LocalVideoTrack constructor has incorrect parameter names

### ISSUE THREAD

**Issue by jskrzypek** [twilio/twilio-video.js#71] opened 2017-03-30 11:13 UTC
If you look at the code here there might be a bug:
https://github.com/twilio/twilio-video.js/blob/master/lib/media/track/localvideotrack.js#L7-L22

The jsdoc comment indicates that `LocalVideoTrack()` should take two arguments, `mediaStreamTrack` and `options`:
```
 * @param {MediaStreamTrack} mediaStreamTrack - The underlying MediaStreamTrack
 * @param {LocalTrackOptions} options - {@link LocalTrack} options
```
while the function code takes three arguments, `mediaStream`, `mediaStreamTrack`, & `options`, and passes them to it's `super`, `LocalTrack()`, along with the `VideoTrack` ctor (4 args total).
```
function LocalVideoTrack(mediaStream, mediaStreamTrack, options) {
  if (!(this instanceof LocalVideoTrack)) {
    return new LocalVideoTrack(mediaStream, mediaStreamTrack, options);
  }
  LocalTrack.call(this, VideoTrack, mediaStream, mediaStreamTrack, options);
}
```

However, `LocalTrack()` takes only 3 arguments, not four: a `Track`, a `mediaStreamTrack`, and `options`:
```
...
 * @param {function(MediaStreamTrack, TrackSignaling): Track} Track
 * @param {MediaStream} mediaStreamTrack - The underlying MediaStreamTrack
 * @param {LocalTrackOptions} options
 * @property {boolean} isStopped - Whether or not the {@link LocalTrack} is stopped
 * @fires LocalTrack#stopped
 */
function LocalTrack(Track, mediaStreamTrack, options) {
...
```

~~It seems like this would cause problems with the videoTracks.~~

I was being dumb, this won't actually cause problems because of how functions work, but it is a bit confusing if you're looking at the code.

**Comment by manjeshbhargav** [comment] 2017-03-30 16:54
Hi @jskrzypek ,

We are aware of this issue. We have the fix lined up for `beta6`. However, this should not prevent the `LocalVideoTrack` from working as intended, because when you call `new LocalVideoTrack(mediaStreamTrack, options)`, inside the constructor, `mediaStreamTrack` is assigned to `mediaStream` and `options` is assigned to `mediaStreamTrack`. So when `LocalTrack` constructor is called, it actually passes the right parameters.

Thank you for taking the time to point this out.

Manjesh Malavalli

**Closed** 2017-04-06 22:52 UTC
