### ISSUE TITLE
"navigator" is not available during server side rendering

### ISSUE THREAD

**Issue by webjay** [twilio/twilio-video.js#1012] opened 2020-05-10 22:46 UTC
When building with Gatsby, I get the error: _"navigator" is not available during server side rendering._, which is caused by `isGetUserMediaSupported`.

It would be nice if a check could be made:
https://www.gatsbyjs.org/docs/debugging-html-builds/#how-to-check-if-window-is-defined

**Comment by makarandp0** [comment] 2020-05-11 14:22
Thank you @webjay for reporting this issue. This looks like duplicate of https://github.com/twilio/twilio-video.js/issues/997 - we are working on getting this fixed. 

Thanks,
Makarand

**Closed by makarandp0** 2020-05-11 14:22 UTC
Labels: duplicate
