### ISSUE TITLE
iOS 14.3 WKWebView

### ISSUE THREAD

**Issue by manit77** [twilio/twilio-video.js#1364] opened 2021-01-31 20:16 UTC
We've had WebRTC video calls running successfully for years on Chrome, Android, iOS and FireFox. I am testing to see if Twilio can replace some parts of our system. We are testing the twilio-video.js on iOS 14.3. The call process works as expected using Chrome, Safari.  When embedding our web page inside WKWebView and we ran into some issues using Twilio. I know WKWebView is not listed as a supported browser but has anyone tested video calls in WKWebView?

When using twilio-video.js:
- No JavaScript errors are reported.
-  Local camera and audio works using getUserMedia. 
- The local participant can connect to a room but no video or audio streams are sent to Twilio. 
- No remote audio or video streams are received from Twilio. 
- It appears that these events never gets triggered:
    participant.on('trackSubscribed', track => trackSubscribed(track));
    participant.on('trackUnsubscribed', trackUnsubscribed);

- When removing twilio-video.js and using our own JavaScript WebRTC call process inside WKWebView. Everything works as expected. 
- When loading a third party web page such as https://janus.conf.meetecho.com/videocalltest.html inside WKWebView.  Everything works as expected.

Any feedback is appreciated. Thanks.

Update:

I did find oner error during the negotiation process.

Calling setRemoteDescription with an RTCSessionDescription of type "answer" failed with the error "Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.".

**Comment by ma9o** [comment] 2021-02-01 12:50
+1

**Comment by manjeshbhargav** [comment] 2021-02-01 18:40
Hi @manit77 ,

Thanks for reporting this issue. We don't have WKWebView support in our roadmap for 2021 as of now. However, I'm curious as to why WKWebView is not working, since it is essentially a Safari window. Can you share the JavaScript console logs from your test app if possible? You can enable debug logging in the SDK by setting `logLevel: 'debug'` in ConnectOptions.

**Comment by manit77** [comment] 2021-02-01 21:41
[twilio-log1.txt](https://github.com/twilio/twilio-video.js/files/5906882/twilio-log1.txt)

It is odd that your library  works perfectly on Safari and on our system works just fine inside WKWebView. We setup small-room and recording in Twilio and our system uses Peer to Peer with turn servers enforced.

Here is the file attached. This is in our log format but I should have captured all the values.  I see the error around line 127. I tested this on iPhone 7 14.3, iPad Mini 14.4 with the same results. 

Thanks for looking at it.

**Comment by manit77** [comment] 2021-02-01 21:43
inside the log file, **U** is peer 1 and **I** is peer 2

**Comment by powerfront** [comment] 2021-02-04 07:33
We also have a big need for this and a lot of clients wanting to take client phone calls in the app using WKWebView.
We are facing the same issue and it looks like it might be a minor fix on Twilio side to get this functional.
Our clients are already using Video Chat with the twilio integration on normal website browsers and we prefer not have to go with another provider to get this working in our App SDK with works in a WKWebView.

**Comment by LuisaMontanez** [comment] 2021-02-04 14:19
+1

**Comment by manit77** [comment] 2021-02-04 16:54
@powerfront,

Are you using small-room or peer to peer in your Twilio calls?

**Comment by noahmehl** [comment] 2021-02-04 18:23
@manjeshbhargav Surprisingly, WKWebView is quite different than Safari in iOS.  In fact, Apple only added some WebRTC functionality in iOS 14.3, `getUserMedia()`: https://webkit.org/blog/11353/mediarecorder-api/

We've ([Open Telecom Foundation](http://opentelecom.foundation)) been working on: https://github.com/OpenTelecom/WKWebViewRTC and https://cocoapods.org/pods/WKWebViewRTC. We've recently updated for `getUserMedia()` for audio and video (for both 14.3 and previous to that).

Looks like the Twilio example doesn't quite work fully for WKWebViewRTC either.  We'll look into it.

**Comment by arturfps** [comment] 2021-02-04 22:26
+1

**Comment by powerfront** [comment] 2021-02-04 22:48
> @powerfront,
> 
> Are you using small-room or peer to peer in your Twilio calls?

Peer to peer

Thks

**Comment by LiuGuanwei77** [comment] 2021-02-05 09:35
+1

**Comment by cbxp** [comment] 2021-02-11 09:41
@manjeshbhargav 
We have submitted a pull request to solve the issue: https://github.com/twilio/twilio-webrtc.js/pull/133

The problem is that a function in [twilio-webrtc.js](https://github.com/twilio/twilio-webrtc.js) project which guesses the browser by user agent does not work correctly when a web application is running inside WKWebView.

**Comment by manit77** [comment] 2021-02-11 19:18
@cbxp 

Also need to add support for iPad. this the user agent for iPad mini. I can't copy paste it, this is typed:

Mozilla/5.0 (iPad; CPU OS 14_4 like Mac OS X) AppleWebkit/605.1.15 (KHTML, like Gecko) Mobile/15E148

**Comment by manit77** [comment] 2021-02-11 19:30
@cbxp

I did test your fix on the iPad. It is working. I just added iPad to the user agent check.

if (/Safari|iPhone|iPad/.test(userAgent)) {

Thanks!

**Comment by cbxp** [comment] 2021-02-12 08:52
Thanks @manit77 
Pull request https://github.com/twilio/twilio-webrtc.js/pull/133 includes iPad fix as well

@manjeshbhargav - could you please review and accept the pull request?

**Comment by aponski** [comment] 2021-02-16 13:39
+1

**Comment by jnorris441** [comment] 2021-02-18 15:11
+1

**Comment by sowsan** [comment] 2021-03-01 06:48
Any idea when this fix will be available in master and ready to use in production?

**Comment by tbasallo** [comment] 2021-03-01 13:22
I can confirm that this fixes the issue. I modified the CDN file to include "iPhone" in the browser test and served locally and it worked like a charm.

Can someone from the Twilio team provide some feedback?

(you have to love open source - these moments are great.)

**Comment by manjeshbhargav** [comment] 2021-03-12 21:12
Hi everyone,

We have WKWebView support tentatively as part of our Q2 roadmap, and we will actively work on it soon. @cbxp , thanks for the PR. We will certainly incorporate it when we start working on this.

Thanks,

Manjesh

**Comment by pmp-rbohler** [comment] 2021-03-22 13:00
> @manjeshbhargav
> We have submitted a pull request to solve the issue: [twilio/twilio-webrtc.js#133](https://github.com/twilio/twilio-webrtc.js/pull/133)
> 
> The problem is that a function in [twilio-webrtc.js](https://github.com/twilio/twilio-webrtc.js) project which guesses the browser by user agent does not work correctly when a web application is running inside WKWebView.

I used `patch-package` to replicate these changes on the `twilio-webrtc` package version `4.3.2` and it worked like a charm. Thank you a lot!

**Comment by sowsan** [comment] 2021-03-25 19:46
This is a major blocker for one of my projects. What is the best way to get a fix temporarily? We are even thinking of switching to other Video SDK providers if this is going to take more time..

**Comment by renato-bohler** [comment] 2021-03-25 19:57
> This is a major blocker for one of my projects. What is the best way to get a fix temporarily? We are even thinking of switching to other Video SDK providers if this is going to take more time..

I've successfully used `patch-package` to use @cbxp's fix on the `twilio-webrtc` package. You could try this while the fix is not officially available.

**Comment by sowsan** [comment] 2021-03-25 20:03
> > This is a major blocker for one of my projects. What is the best way to get a fix temporarily? We are even thinking of switching to other Video SDK providers if this is going to take more time..
> 
> I've successfully used `patch-package` to use @cbxp's fix on the `twilio-webrtc` package. You could try this while the fix is not officially available.

That is great and thanks for your prompt response. I have not used patch package before. Can you share the steps to use it pls?

**Comment by renato-bohler** [comment] 2021-03-25 20:32
> > > This is a major blocker for one of my projects. What is the best way to get a fix temporarily? We are even thinking of switching to other Video SDK providers if this is going to take more time..
> > 
> > 
> > I've successfully used `patch-package` to use @cbxp's fix on the `twilio-webrtc` package. You could try this while the fix is not officially available.
> 
> That is great and thanks for your prompt response. I have not used patch package before. Can you share the steps to use it pls?

Sure! You just need to follow the instructions on [their readme](https://www.npmjs.com/package/patch-package). But, to simplify:

1. Install `patch-package`: `npm install patch-package --save-dev` or `yarn install -D patch-package`
2. In your `node_modules`, search for the `lib/util/index.js` file inside the `@twilio/webrtc` folder
3. Open the file and make the same [changes that @cbxp has done on the file in his PR](https://github.com/twilio/twilio-webrtc.js/pull/133/files)
4. Run `patch-package`: `npx run patch-package @twilio/webrtc` or `yarn patch-package @twilio/webrtc`. This will create a folder called `patches` which will include a diff that patches that dependency.
5. Add the following script to your `package.json`. This will make `patch-package` apply the patches that are on your repo's `patches` folder into your `node_modules` every time you (or anyone else) install dependencies.
```diff
 "scripts": {
+  "postinstall": "patch-package"
 }
 ```
 
 Note: I haven't tested this step-by-step, but that should be it as far as I remember.

**Comment by mosaabramadan** [comment] 2021-05-04 11:12
i confirm the issue has been fixed with the PR provided by @cbxp 

I simply replaced the index.js file in @twilio/webrtc/lib/util and it all is well across all platforms

**Comment by hthetiot** [comment] 2021-05-21 20:02
Browser userAgent Snifing is bad in 2021 use features detection.

**Comment by it4e** [comment] 2021-05-22 16:39
Another solution is to set the user-agent of WKWebView to contain the word "Safari", then we don't have to worry about making any changes to the Twilio code.

**Comment by it4e** [comment] 2021-05-22 17:31
> This is a major blocker for one of my projects. What is the best way to get a fix temporarily? We are even thinking of switching to other Video SDK providers if this is going to take more time..

Another solution is to set the user-agent of WKWebView to contain the word "Safari", then we don't have to worry about making any changes to the Twilio code.

**Comment by fbruckhoff** [comment] 2021-12-05 13:21
Apple and the WebKit team both confirmed to me that WKWebView currently doesn't support accessing the microphone or camera in the background. So while you can hear other people talk, as soon as you background the app / lock the screen, others can no longer hear or see you. 

Were you able to solve this in `twilio-webrtc` or `WKWebViewRTC`? cc @noahmehl

**Comment by noahmehl** [comment] 2021-12-06 17:18
@fbruckhoff this has not been tested for WKWebViewRTC as far as I know.  All of the WKWebViewRTC is based on the work by @hthetiot for the Cordova project: https://github.com/cordova-rtc/cordova-plugin-iosrtc, and I'm sure he'd have a better idea what is possible here.

**Comment by fbruckhoff** [comment] 2021-12-06 17:57
Thanks @noahmehl! @hthetiot it's be great to hear whether / how you were able to get around the background mic issue :) Cheers

**Comment by hthetiot** [comment] 2021-12-07 12:02
For using audio and microphone while the application is minimized in background we recommend using cordova-plugin-background-mode in combination with cordova-plugin-iosrtc see sample application here: https://github.com/cordova-rtc/cordova-plugin-iosrtc-sample

**Comment by noahmehl** [comment] 2021-12-10 15:26
@hthetiot Thanks for that!!

**Comment by hthetiot** [comment] 2021-12-10 15:39
@oanguenot yes following issue is most likely related, since when safari (via user agent) is detected to my knowledge the twilio library fix the order or m-lines. In any case if you don't have the issue after applying the user agent fix not need to create new issue in my POV.

> Here is a trace of the issue encountered on my own:
"Calling setRemoteDescription with an RTCSessionDescription of type "answer" failed with the error "Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer."
TwilioError: Client is unable to apply a remote media description

**Comment by oanguenot** [comment] 2021-12-10 19:15
@hthetiot Thanks you for your answer

**Comment by PikaJoyce** [comment] 2022-03-09 01:37
Hi Folks,

The latest SDK release 2.21.0 now supports WebViews on iOS. 

Thanks for all of the patience! If any issues arise, please don't hesitate to open another issue with us. With that being said, I will now be closing this issue.

Best,
Joyce

**Closed by PikaJoyce** 2022-03-09 01:37 UTC
Labels: enhancement, iOS, WebView
