### ISSUE TITLE
iOS->JS video doesn't rotate correctly (orientation bug)

### ISSUE THREAD

**Issue by mcorner** [twilio/twilio-video.js#803] opened 2019-11-12 20:47 UTC
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

Objective-C sample
Twilio js quickstart

**Expected behavior:**

Video should rotate correctly

**Actual behavior:**

Bug:
If I rotate an ios device to the right (from portrait to landscape), the video seen on the js side is correctly rotated.  If I rotate the ios device back to portrait, it doesn't rotate correctly in js.  

Not a bug:
If I rotate the ios device to the left, it rotates correctly, and if I rotate it back to portrait it rotates correctly.

**Software versions:**

 - [x ] Browser(s):
Version 78.0.3904.70 (Official Build) (64-bit)

 - [ x] Operating System:
MAC

 - [x ] twilio-video.js:
As found in the quickstart
    "twilio-video": "2.0.0-beta10"

 - [x ] Third-party libraries (e.g., Angular, React, etc.):
All sample apps, but we found this because it happens in our react app on the most recent SDK versions of both JS and ios.

**Comment by mcorner** [comment] 2019-11-13 20:54
I can also confirm that this happens on Android->JS calls.

**Comment by mcorner** [comment] 2019-11-13 21:03
Possibly related to #170

**Comment by ceaglest** [comment] 2019-11-13 21:06
This may be related to a rendering bug in the JS example, or a symptom of #170. Both Chrome 78 and the iOS/Android Video SDKs support rotation tags in Peer-to-Peer Rooms and tag encoded video appropriately.

**Comment by DevelopersTopHat** [comment] 2019-12-05 15:11
I can confirm that this is also happening to me.

**Comment by mcorner** [comment] 2019-12-05 16:16
We had to put in a button to manually rotate the video to fix it.

**Comment by makarandp0** [comment] 2019-12-11 19:43
Thank you @mcorner for reporting this. We have a bug for tracking this issue in our internal database, We should get to that soon. (JSDK-2358)

**Comment by manjeshbhargav** [comment] 2020-06-23 20:07
Closing this since this is [fixed](https://github.com/twilio/twilio-video.js/issues/637#issuecomment-618077012) in iOS 13.

**Closed by manjeshbhargav** 2020-06-23 20:07 UTC
Labels: bug filed
