### ISSUE TITLE
Huge delay between trackSubscribed and trackStarted events.

### ISSUE THREAD

**Issue by sandeepnandula** [twilio/twilio-video.js#736] opened 2019-09-04 14:11 UTC
Hi, @twilio_team our clients are facing a screen share delay issue on group calls.

When a person does a screen share in group call on the receivers end it's taking a while to see that screen track.

Recently it occurred more than`5mins` delay in a group room having only two people, I’ve attached the room details & logs below for reference. Please let us know if you need any further information regarding this.

Twilio_sdk_version: 2.0.0-beta11

RoomSID: RM15f80605578b419ab91605cf2284d96a

No of participant : 2
log: [twilio_logs](https://connect-feedback-logs.storage.googleapis.com/generallog-f74cfc1f-6fad-4081-81f2-d79a8dff9faa.log)

**Note: We saw there is a huge delayed is occurring frequently between the trackSubscribed & trackStarted twilio_events for the tracks.**

**Comment by makarandp0** [comment] 2019-09-04 20:35
Thank you for writing about the issue @sandeepnandula, I do see the delayed start event from the logs you provided. I will look further into this and get back to you.

**Comment by makarandp0** [comment] 2019-09-05 00:01
@sandeepnandula, we are still investigating this. I found that some logs are missing for this room from our servers. Have you by any chance specified `insights: false` as one of the  [connectOption](https://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta13/docs/global.html#ConnectOptions) to `Video.connect` ? 

Thanks,
Makarand

**Comment by sandeepnandula** [comment] 2019-09-05 07:48
Hi @makarandp0 thank you for the quick response. Yeah, we made `insights: false` in the Twilio connection options.

**Comment by makarandp0** [comment] 2019-09-05 13:31
Thanks again for reporting this issue. We have identified the root cause, and filed a ticket to get it fixed. (VMS-2096). Will update when it gets resolved.

**Comment by sandeepnandula** [comment] 2019-09-05 14:25
Thank you @makarandp0 for the update 👍

**Comment by sandeepnandula** [comment] 2019-09-18 08:24
Hi @makarandp0, any updates regarding this bug?

**Comment by makarandp0** [comment] 2019-09-18 14:25
Hello @sandeepnandula, we are actively working on this - I will update once we have fix ready.

**Comment by sandeepnandula** [comment] 2019-09-19 03:57
Thank you for the update @makarandp0 👍

**Comment by kamesh-a** [comment] 2019-10-17 14:46
Hi @makarandp0 

We are getting more feedbacks related delayed starting of screen shares, even in our group call many screen shares didn't start immediately, we had to stop and start it again. Can we please take a look into this issue.

[Delayed-screen-share](https://connect-feedback-logs.storage.googleapis.com/generallog-f46bfb87-7f27-4177-b564-a8cf04a270da.log)

**Comment by mparis** [comment] 2019-10-17 16:31
Hello folks!!
First of all thanks for report this issue.
It might be an internal issue, so in order to allow us debugging it, could you please share the SIDs of the rooms which experimented the issue?
It would also interesting to have the specific participant SIDs and the Track SIDs in order to ease the troubleshooting.

Thanks in advance!!

**Comment by dreamerchandra** [comment] 2019-10-18 10:16
Hi @mparis 
```
track id: MTde5c85bb0ffbafc7914d224eb0eb0bfb
par id: PA96e8086e4544b191c2b5a12d0202f3da
room sid: RMb00deba10d9c71933c4cb1616bb6e069
```
Its an screen share track and the screen share never started 
[log of local](https://connect-feedback-logs.storage.googleapis.com/applog-a49fb205-2093-4807-8afe-412274d1820d.log), [log for remote](https://connect-feedback-logs.storage.googleapis.com/applog-236f9126-b669-4b12-8df4-26163c1c8f65.log)

**Comment by kamesh-a** [comment] 2019-10-21 10:28
Hello Twilio Team,

We have got separate logs from receiver and sender as well as respective screen shares. Screen share never started for the receiver.

Track ID: `MT8e8e1f0a797f30a230f8831b03430234`

Screen Share track Receiver : [logs](https://connect-feedback-logs.storage.googleapis.com/generallog-ffbd046b-044e-4073-969f-40b761f8122b.log)
Screen Share track Sender : [logs](https://connect-feedback-logs.storage.googleapis.com/generallog-297f43d1-509b-465d-bf38-242da811e585.log)

We have attached [screen shots](https://www.dropbox.com/s/0rz23n50403f1uw/MT8e8e1f0a797f30a230f8831b03430234_sender_and_receiver_screens.zip?dl=0) as well.

**Comment by mparis** [comment] 2019-10-21 14:04
Hello!!
Thanks to provide these SIDs, they were useful to dig into the issue using our infrastructure insights.

@dreamerchandra, regarding `MTde5c85bb0ffbafc7914d224eb0eb0bfb` (from room `RMb00deba10d9c71933c4cb1616bb6e069`), I saw the the video was 
forwarded to subscriber `PA96e8086e4544b191c2b5a12d0202f3da`  1.5 seconds after it was received from the publisher `PA554676569017d6c4ee12ee8e3a880d6e`
This should be normal depending on the network conditions and on the load of the clients, specifically of the Publisher to generate proper video key frames (needed to decode the first video frame).

@kamesh-a , regarding `MT8e8e1f0a797f30a230f8831b03430234` (from room `RMa8ffea419bd4ab74af5aff05c1bd61f8`), I saw the our infrastructure didn't receive video from the publisher during the whole room duration, so it is normal that any subscriber saw anything.

I hope this explanation is enough for you both, anyway, in order to allow us to dig even more into these and future issues it would be nice if you can enable video-insights at client side.

Kind regards :D

**Comment by kamesh-a** [comment] 2019-10-21 14:11
Hello @mparis 

We have downgraded the resolutions to `640x480` with insights turned on

Sender Screen Share log : https://connect-feedback-logs.storage.googleapis.com/generallog-7dbb9185-7f82-41e0-879b-2989c77c2b8a.log

Receiver Screen Share log : https://connect-feedback-logs.storage.googleapis.com/generallog-cd3c56df-3e89-47a5-9443-7c2d729bef43.log

TrackID: MTeb3875f12cd94ce31ed34bc8a0589332
Room SID: RM8060267ed9560740433b406d15c559f7

Hope these enabling insights is enough from our end.

**Comment by manjeshbhargav** [comment] 2019-10-21 22:21
Hi @kamesh-a ,

All of us are working as hard as we can into getting to the bottom of this, and I apologize for the trouble this is causing you. I was wondering if you are having similar problems with the camera track?

I also noticed that your media region is `us1`. That is, your media server instance is located in the United States. If you are experiencing delays in the camera track as well as the screenshare track, this may be the reason. We recently released a new feature called [GLL for Group Rooms](https://www.twilio.com/docs/video/tutorials/video-regions-and-global-low-latency#selecting-the-media-region), which will create the media server in a region closest to the first Participant which joins the Room.

Please let me know if this helps you in any way.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by kamesh-a** [comment] 2019-10-21 22:26
Hi @manjeshbhargav 

Thanks for update, It's great to know you guys on watch out for it. 
`I was wondering if you are having similar problems with the camera track?` - No camera track issues, not even once. How many times we try, camera is available. 

`GLL`: Sure we can make use of the GLL in our upcoming builds swapping out our nearest location finder based on latlong.

**Comment by manjeshbhargav** [comment] 2019-10-21 22:46
@kamesh-a ,

I have another request. We are trying to isolate the component in the Programmable Video infrastructure which may be causing this delay in the screen share track. So, can you run some tests in Peer-to-Peer Rooms as well?

Thank you so much for helping us by providing detailed logs and information.

Manjesh Malavalli
JSDK Team

**Comment by kamesh-a** [comment] 2019-10-22 20:51
Hello @manjeshbhargav 
I have checked it in peer-to-peer it does have the same effect on chrome 77 & 78 browser. In firefox screen tracks are fine with beta4.

beta12 - works with no issues in chrome 77 & chrome 78 and FF ( group calls  with screen shares )

OS: Mac OS Catalina and Mojave
Browser: Chrome 77.

I have changed the GLL settings.

Thanks.

**Comment by manjeshbhargav** [comment] 2020-01-21 03:07
Hi @kamesh-a , @sandeepnandula , @dreamerchandra ,

twilio-video.js@2.0 should have a fix for this. Please try it out and let me know if it helps.

Thanks,

Manjesh Malavalli
JSDK Team

**Closed by manjeshbhargav** 2020-01-21 03:07 UTC
Labels: bug filed

**Comment by algha** [comment] 2020-03-13 11:17
twilio-video": "^2.0.0"
still same problem...
such a big platform, I could think there is bug like this.
