### ISSUE TITLE
Disabling the Camera mutes de microphone.

### ISSUE THREAD

**Issue by JosepSalvat** [twilio/twilio-video.js#1870] opened 2022-08-31 15:27 UTC
For some reason, since 1 month ago (more or less). We've a problem in production. Every time that a user puts off his cam, when he activates again, the microphone is not working (like if it was a mute micro).

I'm checking the code, but we didn't change anything in the last year. We've only upgraded the version to 2.21.1 (I checked in last version and still happens)

Any clue that what is happening? What should I look for? I'm kinda lost here

 - [x ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

Log
https://pastebin.com/sFqV1RSw
-->

TODO

**Software versions:**

 - [ All browsers] Browser(s):
 - [All OS ] Operating System:
 - [ 2.21.1] twilio-video.js:
 - [ React ] Third-party libraries (e.g., Angular, React, etc.):

**Comment by JosepSalvat** [comment] 2022-09-01 07:50
I'm adding more logs, when this happens.

`2022-09-01T07:47:41.513Z debug [TwilioConnection #1: wss://global.vss.twilio.com/signaling] Outgoing: {"body":{"session":"b0ac123300e82642f50b45e0e781958908470734f0c72adf1f817a83dd13b7cbb404ca1904540b814be44c5e56aa271423eb1f6fb4a191d9b490b14c19b7c9b2","type":"update","version":2,"participant":{"revision":10,"tracks":[{"enabled":true,"id":"c5c69c57-4fde-41b0-9698-288ae5f555b0","kind":"audio","name":"575ed03f-c109-4e67-aa4c-6baa1d7806f1","priority":"standard"},{"enabled":true,"id":"37d7aaec-c989-4f05-b972-265750d719a3","kind":"video","name":"c79f37f8-bb3e-4e6a-bbd2-1190234d88bf","priority":"standard"}]}},"type":"msg"}
log.js:213 2022-09-01T07:47:41.522Z debug [TwilioConnection #1: wss://global.vss.twilio.com/signaling] Outgoing: {"body":{"session":"b0ac123300e82642f50b45e0e781958908470734f0c72adf1f817a83dd13b7cbb404ca1904540b814be44c5e56aa271423eb1f6fb4a191d9b490b14c19b7c9b2","type":"update","version":2,"peer_connections":[{"description":{"type":"offer","revision":29,"sdp":"v=0\r\no=- 7669892606560823012 31 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1 application0 4 5 audio0 video11 video12 audio1\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS\r\nm=audio 50214 UDP/TLS/RTP/SAVPF 111 0\r\nc=IN IP4 172.29.5.234\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=candidate:3193121426 1 udp 2122260223 172.29.5.234 50214 typ host generation 0 network-id 1 network-cost 10\r\na=ice-ufrag:GkeN\r\na=ice-pwd:ix6bJdSEAbG/Sk+1LQbeEZAZ\r\na=ice-options:trickle\r\na=fingerprint:sha-256 38:3F:71:D0:BA:0E:2D:F1:C9:82:AB:37:31:BF:7F:4B:86:B1:64:82:49:F8:C3:87:4E:6C:3E:78:21:32:FA:D6\r\na=setup:actpass\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=recvonly\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:0 PCMU/8000\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 108 114 116 97 109 115\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:GkeN\r\na=ice-pwd:ix6bJdSEAbG/Sk+1LQbeEZAZ\r\na=ice-options:trickle\r\na=fingerprint:sha-256 38:3F:71:D0:BA:0E:2D:F1:C9:82:AB:37:31:BF:7F:4B:86:B1:64:82:49:F8:C3:87:4E:6C:3E:78:21:32:FA:D6\r\na=setup:actpass\r\na=mid:1\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:14 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:13 urn:3gpp:video-orientation\r\na=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendrecv\r\na=msid:- 37d7aaec-c989-4f05-b972-265750d719a3\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtpmap:108 H264/90000\r\na=rtcp-fb:108 goog-remb\r\na=rtcp-fb:108 transport-cc\r\na=rtcp-fb:108 ccm fir\r\na=rtcp-fb:108 nack\r\na=rtcp-fb:108 nack pli\r\na=fmtp:108 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:114 red/90000\r\na=rtpmap:116 ulpfec/90000\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:109 rtx/90000\r\na=fmtp:109 apt=108\r\na=rtpmap:115 rtx/90000\r\na=fmtp:115 apt=114\r\na=ssrc-group:FID 102772829 2030705210\r\na=ssrc:102772829 cname:E86ZrCRjfBS6MEBT\r\na=ssrc:102772829 msid:- 37d7aaec-c989-4f05-b972-265750d719a3\r\na=ssrc:2030705210 cname:E86ZrCRjfBS6MEBT\r\na=ssrc:2030705210 msid:- 37d7aaec-c989-4f05-b972-265750d719a3\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:GkeN\r\na=ice-pwd:ix6bJdSEAbG/Sk+1LQbeEZAZ\r\na=ice-options:trickle\r\na=fingerprint:sha-256 38:3F:71:D0:BA:0E:2D:F1:C9:82:AB:37:31:BF:7F:4B:86:B1:64:82:49:F8:C3:87:4E:6C:3E:78:21:32:FA:D6\r\na=setup:actpass\r\na=mid:application0\r\na=sctp-port:5000\r\na=max-message-size:262144\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 0\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:GkeN\r\na=ice-pwd:ix6bJdSEAbG/Sk+1LQbeEZAZ\r\na=ice-options:trickle\r\na=fingerprint:sha-256 38:3F:71:D0:BA:0E:2D:F1:C9:82:AB:37:31:BF:7F:4B:86:B1:64:82:49:F8:C3:87:4E:6C:3E:78:21:32:FA:D6\r\na=setup:actpass\r\na=mid:4\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=sendrecv\r\na=msid:- c5c69c57-4fde-41b0-9698-288ae5f555b0\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:0 PCMU/8000\r\na=ssrc:709039347 cname:E86ZrCRjfBS6MEBT\r\na=ssrc:709039347 msid:- c5c69c57-4fde-41b0-9698-288ae5f555b0\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 108 114 116 97 109 115\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:GkeN\r\na=ice-pwd:ix6bJdSEAbG/Sk+1LQbeEZAZ\r\na=ice-options:trickle\r\na=fingerprint:sha-256 38:3F:71:D0:BA:0E:2D:F1:C9:82:AB:37:31:BF:7F:4B:86:B1:64:82:49:F8:C3:87:4E:6C:3E:78:21:32:FA:D6\r\na=setup:actpass\r\na=mid:5\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-exten
log.js:213 2022-09-01T07:47:41.674Z debug [TwilioConnection #1: wss://global.vss.twilio.com/signaling] Incoming: {"body":{"version":2,"type":"update","peer_connections":[{"id":"e95269d1-b97b-4702-ab6f-cb4eaf058ece","description":{"type":"answer","sdp":"v=0\r\no=- 3871007177 3871007205 IN IP4 0.0.0.0\r\ns=VMdfbfb25c3fdc9a7d76a7d12da9aef5a1\r\nc=IN IP4 0.0.0.0\r\nt=0 0\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS\r\na=ice-lite\r\na=group:BUNDLE 0 1 application0 4 5 audio0 audio1 video11 video12\r\na=msid-semantic:WMS *\r\nm=audio 1 UDP/TLS/RTP/SAVPF 111 0\r\nc=IN IP4 0.0.0.0\r\na=setup:active\r\na=inactive\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=mid:0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=rtpmap:111 opus/48000/2\r\na=rtpmap:0 PCMU/8000\r\na=rtcp-mux\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=ice-ufrag:qEJE\r\na=ice-pwd:kKcVkya/oP6D27/f7EIgGL\r\na=candidate:2 1 UDP 2013266430 3.235.111.152 19349 typ host\r\na=candidate:2 2 UDP 2013266429 3.235.111.152 19625 typ host\r\na=fingerprint:sha-256 74:E6:AA:9B:AE:C9:43:AC:06:79:5B:4A:50:22:CC:8D:74:1B:CB:09:0B:E8:3B:B1:98:5D:81:E2:06:C9:38:19\r\nm=video 1 UDP/TLS/RTP/SAVPF 96 108 114 116\r\nc=IN IP4 0.0.0.0\r\na=rtcp-rsize\r\na=setup:active\r\na=recvonly\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=mid:1\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=rtpmap:96 VP8/90000\r\na=rtpmap:108 H264/90000\r\na=rtpmap:114 red/90000\r\na=rtpmap:116 ulpfec/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtcp-fb:108 goog-remb\r\na=rtcp-fb:108 transport-cc\r\na=rtcp-fb:108 ccm fir\r\na=rtcp-fb:108 nack\r\na=rtcp-fb:108 nack pli\r\na=rtcp-mux\r\na=fmtp:108 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=ice-ufrag:qEJE\r\na=ice-pwd:kKcVkya/oP6D27/f7EIgGL\r\na=candidate:2 1 UDP 2013266430 3.235.111.152 19349 typ host\r\na=candidate:2 2 UDP 2013266429 3.235.111.152 19625 typ host\r\na=fingerprint:sha-256 74:E6:AA:9B:AE:C9:43:AC:06:79:5B:4A:50:22:CC:8D:74:1B:CB:09:0B:E8:3B:B1:98:5D:81:E2:06:C9:38:19\r\nm=application 1 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=setup:active\r\na=mid:application0\r\na=sctp-port:5000\r\na=ice-ufrag:qEJE\r\na=ice-pwd:kKcVkya/oP6D27/f7EIgGL\r\na=candidate:2 1 UDP 2013266430 3.235.111.152 19349 typ host\r\na=candidate:2 2 UDP 2013266429 3.235.111.152 19625 typ host\r\na=fingerprint:sha-256 74:E6:AA:9B:AE:C9:43:AC:06:79:5B:4A:50:22:CC:8D:74:1B:CB:09:0B:E8:3B:B1:98:5D:81:E2:06:C9:38:19\r\nm=audio 1 UDP/TLS/RTP/SAVPF 111 0\r\nc=IN IP4 0.0.0.0\r\na=setup:active\r\na=recvonly\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=mid:4\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=rtpmap:111 opus/48000/2\r\na=rtpmap:0 PCMU/8000\r\na=rtcp-mux\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=ice-ufrag:qEJE\r\na=ice-pwd:kKcVkya/oP6D27/f7EIgGL\r\na=candidate:2 1 UDP 2013266430 3.235.111.152 19349 typ host\r\na=candidate:2 2 UDP 2013266429 3.235.111.152 19625 typ host\r\na=fingerprint:sha-256 74:E6:AA:9B:AE:C9:43:AC:06:79:5B:4A:50:22:CC:8D:74:1B:CB:09:0B:E8:3B:B1:98:5D:81:E2:06:C9:38:19\r\nm=video 1 UDP/TLS/RTP/SAVPF 96 108 114 116\r\nc=IN IP4 0.0.0.0\r\na=rtcp-rsize\r\na=setup:active\r\na=inactive\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=mid:5\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=rtpmap:96 VP8/90000\r\na=rtpmap:108 H264/90000\r\na=rtpmap:114 red/90000\r\na=rtpmap:116 ulpfec/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtcp-fb:108 goog-remb\r\na=rtcp-fb:108 transport-cc\r\na=rtcp-fb:108 ccm fir\r\na=rtcp-fb:108 nack\r\na=rtcp-fb:108 nack pli\r\na=rtcp-mux\r\na=fmtp:108 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=ice-ufrag:qEJE\r\na=ice-pwd:kKcVkya/oP6D27/f7EIgGL\r\na=candidate:2 1 UDP 2013266430 3.235.111.152 19349 typ host\r\na=candidate:2 2 UDP 2013266429 3.235.111.152 19625 typ host\r\na=fingerprint:sha-256 74:E6:AA:9B:AE:C9:43:AC:06:79:5B:4A:50:22:CC:8D:74:1B:CB:09:0B:E8:3B:B1:98:5D:81:E2:06:C9:38:19\r\nm=audio 1 UDP/TLS/RTP/SAVPF 111\r\nc=IN IP4 0.0.0.0\r\na=mid:audio0\r\na=setup:active\r\na=sendonly\r\na=msid:default 8f9e76ca-6cec-4698-9b8f-eef725bdd533\r\na=ssrc:3465911976 cname:user1152079451@host-e0dcd906\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-mux\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=ice-ufrag:qEJE\r\na=ice-pwd:kKcVkya/oP6D27/f7EIgGL\r\na=candidate:2 1 UDP 2013266430 3.235.111.152 19349 typ host\r\na=candidate:2 2 UDP 2013266429 3.235.111.152 19625 typ host\r\na=fingerprint:sha-256 74:E6:AA:9B:AE:C9:43:AC:06:79:5B:4A:50:22:CC:8D:74:1B:CB:09:0B:E8:3B:B1:98:5D:81:E2:06:C9:38:19\r\nm=video 1 UDP/TLS/RTP/SAVPF 96 114 116\r\nc=IN IP4 0.0.0.0\r\na=mid:video11\r\na=rtcp-rsize\r\na=setup:acti
log.js:213 2022-09-01T07:47:41.675Z info [LocalParticipant #1: PAb404ca1904540b814be44c5e56aa2714] Added a new VideoTrackPublication: MT6c9133837b509ee9c47c17542b766748
log.js:213 2022-09-01T07:47:41.676Z debug [LocalParticipant #1: PAb404ca1904540b814be44c5e56aa2714] VideoTrackPublication: LocalVideoTrackPublication {trackName: 'c79f37f8-bb3e-4e6a-bbd2-1190234d88bf', trackSid: 'MT6c9133837b509ee9c47c17542b766748', kind: 'video', …}isTrackEnabled: (...)kind: "video"priority: (...)track: LocalVideoTrackdimensions: {width: 640, height: 480}id: "c79f37f8-bb3e-4e6a-bbd2-1190234d88bf"isEnabled: (...)isStarted: (...)isStopped: (...)kind: "video"mediaStreamTrack: (...)name: "c79f37f8-bb3e-4e6a-bbd2-1190234d88bf"processedTrack: nullprocessor: null_MediaStream: ƒ MediaStream()_attachments: Set(1) {video.video-preview}_captureTimeoutId: null_constraints: {deviceId: undefined}_didCallEnd: false_dummyEl: video_elShims: WeakMap {}_events: {enabled: Array(3), disabled: Array(3), started: Array(2), dimensionsChanged: ƒ, message: ƒ, …}_eventsCount: 8_gUMSilentTrackWorkaround: ƒ workaround(log, getUserMedia, constraints, n, timeout)_getUserMedia: ƒ getUserMedia(constraints)_inputFrame: null_instanceId: 18_isCapturing: false_isCreatedByCreateLocalTracks: true_isStarted: (...)_log: Log {_component: LocalVideoTrack, _logLevels: {…}, _warnings: Set(0), …}_maxListeners: undefined_outputFrame: null_playPausedElementsIfNotBackgrounded: false_processorEventObserver: VideoProcessorEventObserver {_events: {…}, _eventsCount: 6, _maxListeners: undefined, _lastStatsSaveTime: null, _lastStatsPublishTime: null, …}_shouldShimAttachedElements: false_trackSender: MediaTrackSender {_events: {…}, _eventsCount: 0, _maxListeners: undefined, id: 'c79f37f8-bb3e-4e6a-bbd2-1190234d88bf', kind: 'video', …}_unmuteHandler: null_unprocessedTrack: null_workaroundSilentLocalVideo: null_workaroundSilentLocalVideoCleanup: null_workaroundWebKitBug1208516: false_workaroundWebKitBug1208516Cleanup: nullget isEnabled: ƒ ()get isStarted: ƒ ()get isStopped: ƒ ()get mediaStreamTrack: ƒ ()get _isStarted: ƒ ()set _isStarted: ƒ (_isStarted)[[Prototype]]: LocalVideoTracktrackName: "c79f37f8-bb3e-4e6a-bbd2-1190234d88bf"trackSid: "MT6c9133837b509ee9c47c17542b766748"_events: {subscribed: ƒ, unsubscribed: ƒ}_eventsCount: 2_instanceId: 17_log: Log {_component: LocalVideoTrackPublication, _logLevels: {…}, _warnings: Set(0), …}_maxListeners: undefined_reemitTrackEvent: ƒ value()_signaling: LocalTrackPublicationV2 {_events: {…}, _eventsCount: 1, _maxListeners: undefined, kind: 'video', name: 'c79f37f8-bb3e-4e6a-bbd2-1190234d88bf', …}_unpublish: ƒ unpublish(publication)get isTrackEnabled: ƒ ()get priority: ƒ ()[[Prototype]]: LocalTrackPublication
VideoPublication.tsx:34 LocalVideoTrack {kind: 'video', name: 'c79f37f8-bb3e-4e6a-bbd2-1190234d88bf', processedTrack: null, …}dimensions: {width: 640, height: 480}id: "c79f37f8-bb3e-4e6a-bbd2-1190234d88bf"isEnabled: (...)isStarted: (...)isStopped: (...)kind: "video"mediaStreamTrack: (...)name: "c79f37f8-bb3e-4e6a-bbd2-1190234d88bf"processedTrack: nullprocessor: null_MediaStream: ƒ MediaStream()_attachments: Set(1) {video.video-preview}_captureTimeoutId: null_constraints: {deviceId: undefined}_didCallEnd: false_dummyEl: video_elShims: WeakMap {}_events: {enabled: Array(3), disabled: Array(3), started: Array(2), dimensionsChanged: ƒ, message: ƒ, …}_eventsCount: 8_gUMSilentTrackWorkaround: ƒ workaround(log, getUserMedia, constraints, n, timeout)_getUserMedia: ƒ getUserMedia(constraints)_inputFrame: null_instanceId: 18_isCapturing: false_isCreatedByCreateLocalTracks: true_isStarted: (...)_log: Log {_component: LocalVideoTrack, _logLevels: {…}, _warnings: Set(0), …}_maxListeners: undefined_outputFrame: null_playPausedElementsIfNotBackgrounded: false_processorEventObserver: VideoProcessorEventObserver {_events: {…}, _eventsCount: 6, _maxListeners: undefined, _lastStatsSaveTime: null, _lastStatsPublishTime: null, …}_shouldShimAttachedElements: false_trackSender: MediaTrackSender {_events: {…}, _eventsCount: 0, _maxListeners: undefined, id: 'c79f37f8-bb3e-4e6a-bbd2-1190234d88bf', kind: 'video', …}_unmuteHandler: null_unprocessedTrack: null_workaroundSilentLocalVideo: null_workaroundSilentLocalVideoCleanup: null_workaroundWebKitBug1208516: false_workaroundWebKitBug1208516Cleanup: nullget isEnabled: ƒ ()get isStarted: ƒ ()get isStopped: ƒ ()get mediaStreamTrack: ƒ ()get _isStarted: ƒ ()set _isStarted: ƒ (_isStarted)[[Prototype]]: LocalVideoTrack
VideoPublication.tsx:34 LocalVideoTrack {kind: 'video', name: 'c79f37f8-bb3e-4e6a-bbd2-1190234d88bf', processedTrack: null, …}`

**Comment by PikaJoyce** [comment] 2022-09-01 17:58
Hi @JosepSalvat,

Thanks for opening this issue with us. I have tested this out across our applications and I am unable to reproduce your issue. To help us debug further, I have a few requests: 
1. Could you please show us the code in which you handle this? 
2. Could you provide some room sids in which this is occuring?
3. If possible, could you please provide a test application in which this is happening?

Thanks!
Joyce

**Comment by JosepSalvat** [comment] 2022-09-02 08:33
hello @PikaJoyce ! Thanks for the answer.
I had the same problem that this issue: https://github.com/twilio/twilio-video.js/issues/1811
So I did the same thing, for now I'm not stopping the clones, and it worked.
Let's see how it goes. Now I'm experiencing something similar with share screen, but I've to replicate the problem first.
Thank you :)

**Comment by PikaJoyce** [comment] 2022-09-02 20:15
Thanks for the update @JosepSalvat !

Since it seems like you've resolved the issue, I'll be closing this thread now. But of course, feel free to respond here or open a new issue with us if you're experiencing any problems in the future!

Best,
Joyce

**Closed by PikaJoyce** 2022-09-02 20:15 UTC
