### ISSUE TITLE
2.17.0 screen sharing with very bad quality

### ISSUE THREAD

**Issue by BenAtCrikle** [twilio/twilio-video.js#1575] opened 2021-09-17 16:03 UTC
**Expected behavior:**

Good quality screen sharing quality out of the box.

**Actual behavior:**

Blurry screen sharing, low quality - with no way to control or rectify this behaviour using the API.

**Software versions:**

 - [] Browser(s): Chrome, Safari
 - [] Operating System: MacOS
 - [] twilio-video.js: 2.17.0
 - [] Third-party libraries (e.g., Angular, React, etc.):  React

(Rolling back the version from 2.17.0 to the previous version is a work around for now).

**Comment by makarandp0** [comment] 2021-09-17 17:00
Hello @BenAtCrikle, Thank you for reporting this issue. I have filed a ticket to address this (VIDEO-7000).  Will update you as we find more about this.
Thanks,
Makarand

**Comment by makarandp0** [comment] 2021-09-17 17:55
Hey @BenAtCrikle, can you share a  room where saw this issue? Thanks!

**Comment by guillo-crikle** [comment] 2021-09-17 21:41
Hi @makarandp0, I experienced it on Room SID: `RM88a7258dc83d782463fb982078028ac3`

**Comment by bobysf12** [comment] 2021-09-21 03:42
I also faced the same issue. This doesn't happen in `2.15.3`.

**Comment by guillo-crikle** [comment] 2021-10-04 10:37
Thanks @makarandp0!

**Comment by haveaguess** [comment] 2021-10-04 14:42
I'd also like to note that I did significant testing, reverse-engineering your case-study customer - Teleport - and their settings and discovered that screenshare  quality is significantly worse when using the new `contentPreferenceMode` vs the legacy settings with `renderDimension`

Actual local screenshot:

![image](https://user-images.githubusercontent.com/85821/135871528-af0ea7cb-6fe3-4cd0-93ab-2bcfa6d4fb7c.png)

Deprecated rendering settings:

![image](https://user-images.githubusercontent.com/85821/135871625-da7d6a64-98ce-4442-ab88-ccdef630375e.png)

New `contentPreferenceMode` defaults:

![image](https://user-images.githubusercontent.com/85821/135871684-3376150f-baa5-48a8-a8e8-176c672509eb.png)

... all after letting the quality 'settle' by leaving it for 10 seconds and not moving the screen/mouse to 'let it get crisp'

I'm happy to jump in a call with someone to demonstrate/explain, but this is easy to reproduce locally if you try with 2.17.1

This is _really important for us_ if you are going to deprecate the settings that work in favour of this broken new mode

**Comment by makarandp0** [comment] 2021-10-04 19:25
Hello @haveaguess, Sorry about the regression with screen share quality caused by `2.7.0`.  We are working on beefing up our stream quality tests to address such issues early on. 

And thank you for reporting your issue with `contentPreferenceMode` defaults - 
We use default `contentPreferenceMode` for our internal meetings and have not seen this issue. With `contentPreferenceMode` set to `auto` - The SDK uses the video element dimensions to dynamically adjust the video track quality where as renderDimenstions used to keep it fixed (with one specified at connect time). Can you share a room-sid with and without default `contentPreferenceMode` - I am mostly interested in understanding renderDimenstions that you set (which results in good screen share quality) and how it compares to the video element size that you use to render screen share tracks in (which results in bad screen share quality). 

If you can share client side logs with  contentPreferenceMode set to default would be very useful as well. 
Thanks,
Makarand

**Comment by haveaguess** [comment] 2021-10-05 13:37
Hi @makarandp0 

Thanks for your quick and thoughtful reply. 

I have done more testing today and cannot replicate the issues that we had previously, so am starting to wonder if it related to changes in `twilio-video` NPM package version or `getDisplayMedia` constraint changes that I was making around the same time (I thought I did it in a controlled / documented way but might have got confused) 

FYI my tests today were : 

## 'Legacy' `renderDimensions`

```
{
  "name": "RMb46dc5a1a2cd0c1bf922339d98cb5f3d",
  "audio": {
    "deviceId": "default"
  },
  "video": {
    "deviceId": {
      "exact": "f43bac18db795318d4c59c1d2f2cfa9586dc43632cfd85b71b2675980423efb6"
    }
  },
  "bandwidthProfile": {
    "video": {
      "mode": "presentation",
      "renderDimensions": {
        "high": {
          "height": 240,
          "width": 320
        },
        "standard": {
          "height": 240,
          "width": 320
        },
        "low": {
          "height": 240,
          "width": 320
        }
      },
      "clientTrackSwitchOffControl": "manual",
      "trackSwitchOffMode": "detected"
    }
  },
  "preferredVideoCodecs": [
    "VP8"
  ],
  "networkQuality": {
    "local": 3,
    "remote": 3
  }
}
```

## Default `contentPreferenceMode`

```
{
  "name": "RM45ba7768e0f9906f8730f778c409a839",
  "audio": {
    "deviceId": "default"
  },
  "video": {
    "deviceId": {
      "exact": "f43bac18db795318d4c59c1d2f2cfa9586dc43632cfd85b71b2675980423efb6"
    }
  },
  "bandwidthProfile": {
    "video": {
      "mode": "presentation"
    }
  },
  "preferredVideoCodecs": [
    "VP8"
  ],
  "networkQuality": {
    "local": 3,
    "remote": 3
  }
}
```

The constraint change that seemed to help us was setting the frame-rate to 5 that we passed to `getDisplayMedia` (testing on Chrome): 

```
{
        video: {
          width: 1920,
          height: 1080,
          aspectRatio: 1.777777778,
          frameRate: 5,
        },
}
```

Not sure if this is something that you do/recommend? 

I'll run with the legacy `renderDimensions` disabled on our staging environment and see how it plays out

Regards
Ben

**Comment by makarandp0** [comment] 2021-10-05 15:27
Thanks for the update @haveaguess, using framerate of 5 seems like a good choice for screen share track.  Your `renderDimensions` settings look bit off - as you are setting same dimensions for all priorities. - I think you would see better results with `clientTrackSwitchOffControl = auto`

Since the original issue is resolve, I will close this now. Please reopen new issue if you see any issues with screen share track quality.

**Closed by makarandp0** 2021-10-05 15:27 UTC
Labels: bug filed
